"use client";

import FractionText from "@/components/math/FractionText";

const Card=({value,label,tone="grape"})=><div className={`rounded-2xl border-2 p-4 text-center ${tone==="teal"?"border-teal bg-teal-soft":"border-grape bg-grape-soft"}`}><strong className="block font-display text-3xl text-ink"><FractionText>{value}</FractionText></strong><span className="mt-1 block text-xs font-bold text-muted"><FractionText>{label}</FractionText></span></div>;
function Ratio({v}){return <div><p className="text-center text-sm font-extrabold uppercase tracking-wide text-grape">Compara en el orden pedido</p><div className="mx-auto mt-5 grid max-w-md grid-cols-[1fr_auto_1fr] items-center gap-3"><Card {...v.left}/><span className="font-display text-3xl font-black text-honey-deep">:</span><Card {...v.right} tone="teal"/></div></div>}
function Table({v}){return <div><p className="text-center text-sm font-extrabold uppercase tracking-wide text-grape">Cada fila conserva la relación</p><div className="mx-auto mt-5 max-w-md overflow-hidden rounded-2xl border-2 border-night bg-white"><div className="grid grid-cols-2 bg-night text-center text-sm font-bold text-white">{v.headers.map(h=><span key={h} className="p-3"><FractionText>{h}</FractionText></span>)}</div>{v.rows.map((row,i)=><div key={i} className="grid grid-cols-2 border-t border-ink/10 text-center font-display text-xl font-bold text-ink">{row.map((x,j)=><span key={j} className="p-3"><FractionText>{x}</FractionText></span>)}</div>)}</div></div>}
function DoubleLine({v}){return <div><p className="text-center text-sm font-extrabold uppercase tracking-wide text-grape">Las dos escalas cambian juntas</p><div className="mx-auto mt-5 max-w-lg space-y-3">{[[v.top,v.labels?.[0]],[v.bottom,v.labels?.[1]]].map(([values,label],i)=><div key={label} className="grid grid-cols-[90px_1fr_auto_1fr] items-center gap-2"><span className="text-xs font-bold text-muted">{label}</span><Card value={values[0]} label="inicio" tone={i?"teal":"grape"}/><span className="text-2xl font-black text-honey-deep">→</span><Card value={values[1]} label="equivalente" tone={i?"teal":"grape"}/></div>)}</div></div>}
function Operation({v}){return <div><p className="text-center text-sm font-extrabold uppercase tracking-wide text-grape">Una relación por paso</p><div className="mx-auto mt-5 flex max-w-lg flex-col items-stretch gap-2 sm:flex-row sm:items-center sm:justify-center"><span className="rounded-2xl border-2 border-honey bg-honey-soft px-4 py-4 text-center font-display text-2xl font-bold text-night"><FractionText>{v.expression}</FractionText></span>{v.stages.map((s,i)=><div className="contents" key={i}><span className="rotate-90 text-2xl font-black text-grape sm:rotate-0">→</span><span className="rounded-2xl border-2 border-grape bg-grape-soft px-4 py-4 text-center font-display text-xl font-bold text-ink"><FractionText>{s}</FractionText></span></div>)}</div></div>}
function Equation({v}){return <div className="text-center"><p className="text-sm font-extrabold uppercase tracking-wide text-grape">La constante conecta x con y</p><div className="mx-auto mt-5 max-w-md rounded-2xl border-2 border-night bg-white px-5 py-6 font-display text-4xl font-bold text-ink"><FractionText>{v.expression}</FractionText></div><div className="mx-auto mt-4 max-w-sm rounded-2xl bg-grape-soft px-4 py-3 font-display text-xl font-bold text-grape"><FractionText>{v.values}</FractionText></div></div>}
function PercentGrid({p}){return <div className="text-center"><p className="text-sm font-extrabold uppercase tracking-wide text-grape">Cien casillas representan el total</p><div className="mx-auto mt-5 grid aspect-square max-w-[250px] grid-cols-10 overflow-hidden rounded-2xl border-2 border-night">{Array.from({length:100}).map((_,i)=><span key={i} className={`border-b border-r border-night/10 ${i<p?"bg-grape":"bg-white"}`}/>)}</div><p className="mt-4 font-display text-xl font-bold text-ink">{p} de 100 · {p}%</p></div>}
function Graph({v}){return <div className="text-center"><p className="text-sm font-extrabold uppercase tracking-wide text-grape">¿La relación atraviesa el origen?</p><div className="relative mx-auto mt-5 aspect-square max-w-[270px] border-b-4 border-l-4 border-night bg-white"><span className="absolute -bottom-6 -left-3 text-xs font-bold">0</span><div className={`absolute bottom-0 left-0 h-1 origin-left bg-grape ${v.proportional?"w-[125%] -rotate-45":"w-[110%] -rotate-[32deg] translate-y-8"}`}/>{!v.proportional&&<span className="absolute bottom-8 left-0 h-4 w-4 -translate-x-2 rounded-full bg-coral"/>}</div></div>}
function Change({v}){return <div className="text-center"><p className="text-sm font-extrabold uppercase tracking-wide text-grape">Separa valor inicial y cambio</p><div className="mx-auto mt-5 flex max-w-lg flex-col items-stretch gap-2 sm:flex-row sm:items-center"><Card value={v.start} label="inicial"/><span className="text-2xl font-black text-honey-deep">{v.kind==="aumenta"||v.kind==="impuesto"?"+":"−"}</span><Card value={`${v.p}%`} label={v.kind} tone="teal"/><span className="text-2xl font-black text-honey-deep">→</span><Card value={v.final} label="final"/></div></div>}
function ErrorModel({v}){return <div className="text-center"><p className="text-sm font-extrabold uppercase tracking-wide text-coral">No aceptes el resultado sin estimar</p><div className="mx-auto mt-5 max-w-md rounded-2xl border-2 border-coral bg-coral-soft p-4 font-display text-xl font-bold text-ink line-through decoration-coral"><FractionText>{v.claim}</FractionText></div><div className="mx-auto mt-4 max-w-md rounded-2xl border-2 border-grape bg-grape-soft p-4 font-bold text-grape"><FractionText>{v.check}</FractionText></div></div>}
export default function RatioReasoningBoard({question,step=0}){const v=question.visual;let scene=null;if(v.type==="ratio")scene=<Ratio v={v}/>;if(v.type==="table")scene=<Table v={v}/>;if(v.type==="double-line")scene=<DoubleLine v={v}/>;if(v.type==="operation")scene=<Operation v={v}/>;if(v.type==="equation")scene=<Equation v={v}/>;if(v.type==="percent-grid")scene=<PercentGrid p={v.percent}/>;if(v.type==="graph")scene=<Graph v={v}/>;if(v.type==="change")scene=<Change v={v}/>;if(v.type==="error")scene=<ErrorModel v={v}/>;if(["compare-rates","compare-ratios","compare-values"].includes(v.type))scene=<div className="grid gap-3 sm:grid-cols-2">{(v.rates||v.ratios||v.values).map((x,i)=><Card key={i} value={Array.isArray(x)?x.join(" : "):x} label={`opción ${i+1}`} tone={i?"teal":"grape"}/>)}</div>;return <div className="rounded-3xl border border-ink/10 bg-[#fbfaf6] px-4 py-6 sm:px-6 sm:py-8" role="img" aria-label={`Modelo visual para la pregunta: ${question.prompt}`}>{scene}{step>=3&&<div className="mt-5 rounded-2xl border-2 border-teal bg-teal-soft px-4 py-3 text-center font-display text-xl font-bold text-teal"><FractionText>{question.answer}</FractionText></div>}</div>}
