const step = (eyebrow, title, equation, text) => ({ eyebrow, title, equation, text });

function question(config) {
  return {
    ...config,
    options: config.choices.map((value) => ({ value, feedback: value === config.answer ? null : config.wrongFeedback })),
    choices: undefined,
    wrongFeedback: undefined,
  };
}

export const DECIMAL_OPERATION_FAMILIES = [
  { id: "decimal-add-subtract", label: "Suma y resta de decimales", short: "Sumar y restar" },
  { id: "decimal-multiply", label: "Multiplicación de decimales", short: "Multiplicar" },
  { id: "decimal-divide", label: "División de decimales", short: "Dividir" },
  { id: "powers-ten", label: "Potencias de diez", short: "× y ÷ por 10" },
  { id: "decimal-problems", label: "Problemas con decimales", short: "Problemas" },
  { id: "decimal-check", label: "Estimación y análisis de errores", short: "Comprobar" },
];

const questions = [
  question({
    id: "NO03-N1-01", family: "decimal-add-subtract", level: 1, title: "Alinear antes de sumar",
    prompt: "¿Cuánto es 3,4 + 2,15?", hint: "Escribe 3,4 como 3,40 para alinear las centésimas.",
    answer: "5,55", choices: ["5,19", "5,55", "23,9", "55,5"],
    wrongFeedback: "Alinea las comas: 3,40 + 2,15. Las décimas se suman con décimas y las centésimas con centésimas.",
    success: "3,40 + 2,15 = 5,55.",
    visual: { type: "decimal-column", rows: ["3,40", "2,15"], operation: "+" },
    steps: [
      step("Paso 1 · alinea", "Coloca coma bajo coma", "3,40 + 2,15", "El cero final no cambia 3,4; solo muestra las centésimas."),
      step("Paso 2 · suma", "Trabaja por posiciones", "0 + 5 = 5; 4 + 1 = 5", "Luego suma las unidades: 3 + 2 = 5."),
      step("Paso 3 · conserva la coma", "Escribe el resultado alineado", "3,40 + 2,15 = 5,55", "La coma queda en la misma columna."),
    ],
  }),
  question({
    id: "NO03-N1-02", family: "decimal-add-subtract", level: 1, title: "Restar con ceros útiles",
    prompt: "¿Cuál es el resultado de 8,7 − 3,25?", hint: "Convierte 8,7 en 8,70 antes de restar.",
    answer: "5,45", choices: ["5,45", "5,55", "6,55", "55,5"],
    wrongFeedback: "La resta alineada es 8,70 − 3,25. Necesitas reagrupar una décima para restar las centésimas.",
    success: "8,70 − 3,25 = 5,45.",
    visual: { type: "decimal-column", rows: ["8,70", "3,25"], operation: "−" },
    steps: [
      step("Paso 1 · completa", "Escribe una centésima visible", "8,7 = 8,70", "Agregar un cero al final no cambia el valor."),
      step("Paso 2 · resta", "Reagrupa una décima", "10 − 5 = 5; 6 − 2 = 4", "Después resta las unidades: 8 − 3 = 5."),
      step("Paso 3 · resultado", "Mantén la coma alineada", "8,70 − 3,25 = 5,45", "La diferencia es menor que 8,7, como debe ocurrir."),
    ],
  }),
  question({
    id: "NO03-N2-03", family: "decimal-add-subtract", level: 2, title: "Tres sumandos distintos",
    prompt: "Calcula 12,08 + 0,9 + 3,125.", hint: "Escribe todos los números con tres cifras decimales.",
    answer: "16,105", choices: ["15,205", "16,015", "16,105", "160,105"],
    wrongFeedback: "Alinea como 12,080 + 0,900 + 3,125. No unas las cifras sin respetar sus posiciones.",
    success: "12,080 + 0,900 + 3,125 = 16,105.",
    visual: { type: "decimal-column", rows: ["12,080", "0,900", "3,125"], operation: "+" },
    steps: [
      step("Paso 1 · iguala", "Completa hasta milésimas", "12,080; 0,900; 3,125", "Los ceros permiten ver cada columna."),
      step("Paso 2 · suma decimales", "Suma de derecha a izquierda", "0 + 0 + 5 = 5; 8 + 0 + 2 = 10", "Reagrupa cuando una columna supera nueve."),
      step("Paso 3 · termina", "Suma la parte entera", "12,080 + 0,900 + 3,125 = 16,105", "La estimación 12 + 1 + 3 ≈ 16 confirma la magnitud."),
    ],
  }),
  question({
    id: "NO03-N2-04", family: "decimal-add-subtract", level: 2, title: "Restar de un número entero",
    prompt: "¿Cuánto es 20 − 7,856?", hint: "Escribe 20 como 20,000.",
    answer: "12,144", choices: ["12,144", "13,244", "19,144", "127,144"],
    wrongFeedback: "La operación es 20,000 − 7,856. Reagrupa desde la parte entera hacia las posiciones decimales.",
    success: "20,000 − 7,856 = 12,144.",
    visual: { type: "decimal-column", rows: ["20,000", "7,856"], operation: "−" },
    steps: [
      step("Paso 1 · representa", "Convierte 20 a milésimas", "20 = 20,000", "El valor no cambia."),
      step("Paso 2 · reagrupa", "Lleva valor hasta las milésimas", "10 − 6 = 4; 9 − 5 = 4; 9 − 8 = 1", "La cadena de reagrupación atraviesa los ceros."),
      step("Paso 3 · completa", "Resta la parte entera", "20,000 − 7,856 = 12,144", "12,144 + 7,856 vuelve a producir 20."),
    ],
  }),
  question({
    id: "NO03-N1-05", family: "decimal-multiply", level: 1, title: "Tres grupos de 2,4",
    prompt: "¿Cuánto es 2,4 × 3?", hint: "Piensa en 24 décimas multiplicadas por 3.",
    answer: "7,2", choices: ["0,72", "5,4", "7,2", "72"],
    wrongFeedback: "24 décimas por 3 son 72 décimas, que equivalen a 7,2.",
    success: "2,4 × 3 = 7,2.",
    visual: { type: "decimal-product", factors: ["2,4", "3"], parts: ["2 × 3 = 6", "0,4 × 3 = 1,2"] },
    steps: [
      step("Paso 1 · descompón", "Separa unidades y décimas", "2,4 = 2 + 0,4", "Así podemos multiplicar cada parte."),
      step("Paso 2 · distribuye", "Multiplica ambas partes por 3", "6 + 1,2", "Dos por tres son seis; cuatro décimas por tres son doce décimas."),
      step("Paso 3 · reúne", "Suma los productos", "6 + 1,2 = 7,2", "El producto es mayor que 2,4 porque se forman tres grupos."),
    ],
  }),
  question({
    id: "NO03-N2-06", family: "decimal-multiply", level: 2, title: "Un producto que forma diez",
    prompt: "¿Cuál es el resultado de 1,25 × 8?", hint: "Puedes descomponer 1,25 en 1 + 0,25.",
    answer: "10", choices: ["1", "9", "10", "100"],
    wrongFeedback: "Ocho unidades más ocho cuartos de unidad son 8 + 2 = 10.",
    success: "1,25 × 8 = 10.",
    visual: { type: "decimal-product", factors: ["1,25", "8"], parts: ["1 × 8 = 8", "0,25 × 8 = 2"] },
    steps: [
      step("Paso 1 · descompón", "Uno coma veinticinco es uno y un cuarto", "1,25 = 1 + 0,25", "La descomposición facilita el cálculo mental."),
      step("Paso 2 · multiplica", "Calcula cada aporte", "1 × 8 = 8; 0,25 × 8 = 2", "Ocho cuartos forman dos unidades."),
      step("Paso 3 · suma", "Reúne las partes", "8 + 2 = 10", "El producto exacto es diez."),
    ],
  }),
  question({
    id: "NO03-N2-07", family: "decimal-multiply", level: 2, title: "Décimas por décimas",
    prompt: "Calcula 3,6 × 0,4.", hint: "36 décimas por 4 décimas produce centésimas.",
    answer: "1,44", choices: ["0,144", "1,44", "14,4", "144"],
    wrongFeedback: "36 × 4 = 144, pero entre los dos factores hay dos cifras decimales: el resultado es 1,44.",
    success: "3,6 × 0,4 = 1,44.",
    visual: { type: "decimal-product", factors: ["3,6", "0,4"], parts: ["36 × 4 = 144", "2 cifras decimales"] },
    steps: [
      step("Paso 1 · estima", "Cuatro décimas de 3,6 debe ser menor que 3,6", "3,6 × 0,4 < 3,6", "Esta idea evita colocar mal la coma."),
      step("Paso 2 · multiplica cifras", "Calcula como enteros", "36 × 4 = 144", "Luego debemos recuperar el valor decimal."),
      step("Paso 3 · coloca la coma", "Hay dos cifras decimales en total", "144 → 1,44", "El resultado cumple la estimación inicial."),
    ],
  }),
  question({
    id: "NO03-N3-08", family: "decimal-multiply", level: 3, title: "Producto menor que uno",
    prompt: "¿Cuánto es 0,75 × 1,2?", hint: "Multiplica 75 × 12 y recupera tres cifras decimales.",
    answer: "0,9", choices: ["0,09", "0,9", "9", "90"],
    wrongFeedback: "75 × 12 = 900. Los factores reúnen tres cifras decimales, así que 900 se interpreta como 0,900 = 0,9.",
    success: "0,75 × 1,2 = 0,90 = 0,9.",
    visual: { type: "decimal-product", factors: ["0,75", "1,2"], parts: ["75 × 12 = 900", "3 cifras decimales"] },
    steps: [
      step("Paso 1 · magnitud", "El resultado rondará una unidad", "0,75 × 1,2 ≈ 0,75", "Multiplicar por 1,2 aumenta un poco el primer factor."),
      step("Paso 2 · cifras", "Multiplica 75 por 12", "75 × 12 = 900", "Este es el producto sin interpretar aún la escala."),
      step("Paso 3 · escala decimal", "Recupera tres posiciones", "900 milésimas = 0,900 = 0,9", "La respuesta coincide con la estimación."),
    ],
  }),
  question({
    id: "NO03-N1-09", family: "decimal-divide", level: 1, title: "Repartir un decimal",
    prompt: "¿Cuánto es 8,4 ÷ 2?", hint: "Reparte ocho unidades y cuatro décimas en dos grupos.",
    answer: "4,2", choices: ["0,42", "4,2", "4,4", "42"],
    wrongFeedback: "Ocho unidades entre dos son cuatro y cuatro décimas entre dos son dos décimas.",
    success: "8,4 ÷ 2 = 4,2.",
    visual: { type: "decimal-division", dividend: "8,4", divisor: "2", quotient: "?", check: "? × 2 = 8,4" },
    steps: [
      step("Paso 1 · unidades", "Divide ocho entre dos", "8 ÷ 2 = 4", "Cada grupo recibe cuatro unidades."),
      step("Paso 2 · décimas", "Divide cuatro décimas entre dos", "0,4 ÷ 2 = 0,2", "Cada grupo recibe dos décimas."),
      step("Paso 3 · reúne", "Combina ambas partes", "4 + 0,2 = 4,2", "La comprobación 4,2 × 2 = 8,4 confirma el cociente."),
    ],
  }),
  question({
    id: "NO03-N2-10", family: "decimal-divide", level: 2, title: "Dividir entre medio",
    prompt: "¿Cuál es el resultado de 7,5 ÷ 0,5?", hint: "Pregunta cuántas medias unidades caben en 7,5.",
    answer: "15", choices: ["1,5", "3,75", "15", "150"],
    wrongFeedback: "En cada unidad caben dos medios. En 7,5 unidades caben quince grupos de 0,5.",
    success: "7,5 ÷ 0,5 = 15.",
    visual: { type: "decimal-division", dividend: "7,5", divisor: "0,5", quotient: "?", check: "15 × 0,5 = 7,5" },
    steps: [
      step("Paso 1 · interpreta", "Busca grupos de media unidad", "7,5 ÷ 0,5", "Dividir por un número menor que uno puede aumentar el cociente."),
      step("Paso 2 · transforma", "Multiplica ambos por diez", "75 ÷ 5", "La relación no cambia al escalar dividendo y divisor por igual."),
      step("Paso 3 · divide", "Setenta y cinco entre cinco", "75 ÷ 5 = 15", "Quince medias unidades forman 7,5."),
    ],
  }),
  question({
    id: "NO03-N2-11", family: "decimal-divide", level: 2, title: "Cociente mayor que el dividendo",
    prompt: "Calcula 12,6 ÷ 0,3.", hint: "Multiplica ambos números por 10 para eliminar las décimas del divisor.",
    answer: "42", choices: ["4,2", "12,3", "42", "420"],
    wrongFeedback: "12,6 ÷ 0,3 equivale a 126 ÷ 3. El cociente debe ser 42.",
    success: "12,6 ÷ 0,3 = 42.",
    visual: { type: "decimal-division", dividend: "12,6", divisor: "0,3", quotient: "?", check: "42 × 0,3 = 12,6" },
    steps: [
      step("Paso 1 · escala", "Elimina la coma del divisor", "12,6 ÷ 0,3 = 126 ÷ 3", "Multiplicamos ambos términos por diez."),
      step("Paso 2 · divide", "Calcula la división equivalente", "126 ÷ 3 = 42", "Ahora usamos una división de naturales."),
      step("Paso 3 · comprueba", "Multiplica cociente por divisor", "42 × 0,3 = 12,6", "La comprobación recupera el dividendo."),
    ],
  }),
  question({
    id: "NO03-N3-12", family: "decimal-divide", level: 3, title: "Centésimas en el divisor",
    prompt: "¿Cuánto es 0,96 ÷ 0,08?", hint: "Multiplica ambos términos por 100.",
    answer: "12", choices: ["0,12", "1,2", "12", "120"],
    wrongFeedback: "0,96 ÷ 0,08 equivale a 96 ÷ 8, porque ambos números se multiplican por 100.",
    success: "0,96 ÷ 0,08 = 96 ÷ 8 = 12.",
    visual: { type: "decimal-division", dividend: "0,96", divisor: "0,08", quotient: "?", check: "12 × 0,08 = 0,96" },
    steps: [
      step("Paso 1 · transforma", "Convierte el divisor en entero", "0,08 × 100 = 8", "Debemos escalar también el dividendo."),
      step("Paso 2 · equivalencia", "Escala ambos por cien", "0,96 ÷ 0,08 = 96 ÷ 8", "La cantidad de grupos no cambia."),
      step("Paso 3 · resuelve", "Divide noventa y seis entre ocho", "96 ÷ 8 = 12", "Doce grupos de 0,08 forman 0,96."),
    ],
  }),
  question({
    id: "NO03-N1-13", family: "powers-ten", level: 1, title: "Diez veces mayor",
    prompt: "¿Cuál es el resultado de 4,57 × 10?", hint: "Cada cifra pasa a una posición diez veces mayor.",
    answer: "45,7", choices: ["0,457", "4,570", "45,7", "457"],
    wrongFeedback: "Multiplicar por diez desplaza el valor de cada cifra una posición hacia la izquierda: 4,57 se convierte en 45,7.",
    success: "4,57 × 10 = 45,7.",
    visual: { type: "decimal-shift", start: "4,57", operation: "× 10", places: 1, result: "45,7", direction: "izquierda" },
    steps: [
      step("Paso 1 · interpreta", "Diez veces mayor", "4,57 × 10", "Cada cifra aumenta una posición de valor."),
      step("Paso 2 · desplaza valor", "Un lugar hacia la izquierda", "4,57 → 45,7", "No estamos moviendo una coma sin razón: cambian las posiciones de las cifras."),
      step("Paso 3 · comprueba", "El resultado debe ser mayor", "45,7 ÷ 10 = 4,57", "La operación inversa confirma 45,7."),
    ],
  }),
  question({
    id: "NO03-N2-14", family: "powers-ten", level: 2, title: "Cien veces menor",
    prompt: "Calcula 36,2 ÷ 100.", hint: "Cada cifra pasa dos posiciones hacia valores menores.",
    answer: "0,362", choices: ["0,0362", "0,362", "3,62", "362"],
    wrongFeedback: "Dividir entre cien reduce el número dos posiciones: 36,2 → 3,62 → 0,362.",
    success: "36,2 ÷ 100 = 0,362.",
    visual: { type: "decimal-shift", start: "36,2", operation: "÷ 100", places: 2, result: "0,362", direction: "derecha" },
    steps: [
      step("Paso 1 · significado", "Cien veces menor", "36,2 ÷ 100", "Cien equivale a dos factores de diez."),
      step("Paso 2 · dos cambios", "Reduce dos posiciones", "36,2 → 3,62 → 0,362", "El cero inicial conserva la posición de unidades."),
      step("Paso 3 · verifica", "Multiplica para volver", "0,362 × 100 = 36,2", "La respuesta correcta es 0,362."),
    ],
  }),
  question({
    id: "NO03-N3-15", family: "powers-ten", level: 3, title: "Mil veces mayor",
    prompt: "¿Cuánto es 0,508 × 1.000?", hint: "Mil equivale a tres cambios de posición.",
    answer: "508", choices: ["0,000508", "5,08", "50,8", "508"],
    wrongFeedback: "Multiplicar por mil hace que cada cifra ocupe una posición mil veces mayor: 0,508 → 508.",
    success: "0,508 × 1.000 = 508.",
    visual: { type: "decimal-shift", start: "0,508", operation: "× 1.000", places: 3, result: "508", direction: "izquierda" },
    steps: [
      step("Paso 1 · potencia", "Mil es diez por diez por diez", "1.000 = 10³", "Se producen tres cambios de posición."),
      step("Paso 2 · avanza", "Mueve el valor tres lugares", "0,508 → 5,08 → 50,8 → 508", "Cada paso multiplica por diez."),
      step("Paso 3 · comprueba", "Divide entre mil", "508 ÷ 1.000 = 0,508", "La operación inversa recupera el número inicial."),
    ],
  }),
  question({
    id: "NO03-N3-16", family: "powers-ten", level: 3, title: "Potencia desconocida",
    prompt: "¿Qué número completa 6,45 × ? = 645?", hint: "Compara la posición de las cifras en ambos números.",
    answer: "100", choices: ["10", "100", "1.000", "0,01"],
    wrongFeedback: "6,45 se convierte en 645 al aumentar dos posiciones de valor; eso corresponde a multiplicar por 100.",
    success: "6,45 × 100 = 645.",
    visual: { type: "decimal-shift", start: "6,45", operation: "× ?", places: 2, result: "645", direction: "izquierda" },
    steps: [
      step("Paso 1 · compara", "Observa el cambio de magnitud", "6,45 → 645", "El resultado es cien veces mayor, no diez veces mayor."),
      step("Paso 2 · cuenta posiciones", "Las cifras avanzaron dos lugares", "6,45 → 64,5 → 645", "Cada lugar representa un factor de diez."),
      step("Paso 3 · identifica", "Dos factores de diez forman cien", "10 × 10 = 100", "La potencia faltante es 100."),
    ],
  }),
  question({
    id: "NO03-N2-17", family: "decimal-problems", level: 2, title: "Peso total de frutas",
    prompt: "Una bolsa tiene 2,35 kg de manzanas y otra 1,8 kg. ¿Cuánto pesan juntas?", hint: "Alinea 1,8 como 1,80.",
    answer: "4,15 kg", choices: ["3,43 kg", "4,15 kg", "4,95 kg", "23,68 kg"],
    wrongFeedback: "La situación reúne dos pesos: 2,35 + 1,80 = 4,15.",
    success: "Las dos bolsas pesan 4,15 kg.",
    visual: { type: "decimal-story", labels: ["2,35 kg", "+", "1,80 kg"], result: "? kg" },
    steps: [
      step("Paso 1 · elige", "Los pesos se reúnen", "2,35 + 1,8", "La suma representa el peso total."),
      step("Paso 2 · alinea", "Completa las centésimas", "2,35 + 1,80", "Ahora cada posición coincide."),
      step("Paso 3 · suma", "Calcula el total", "2,35 + 1,80 = 4,15", "La unidad kg se conserva en la respuesta."),
    ],
  }),
  question({
    id: "NO03-N2-18", family: "decimal-problems", level: 2, title: "Cinta que queda",
    prompt: "De una cinta de 12,5 m se cortan 2,75 m. ¿Cuántos metros quedan?", hint: "La cantidad disminuye; escribe 12,5 como 12,50.",
    answer: "9,75 m", choices: ["9,25 m", "9,75 m", "10,25 m", "15,25 m"],
    wrongFeedback: "Debes restar la parte cortada: 12,50 − 2,75 = 9,75.",
    success: "Quedan 9,75 metros de cinta.",
    visual: { type: "decimal-story", labels: ["12,50 m", "−", "2,75 m"], result: "? m" },
    steps: [
      step("Paso 1 · cambio", "Cortar reduce la longitud", "12,5 − 2,75", "La operación adecuada es una resta."),
      step("Paso 2 · alinea", "Completa la centésima", "12,50 − 2,75", "Reagrupa para restar cinco centésimas de cero."),
      step("Paso 3 · responde", "Calcula lo que queda", "12,50 − 2,75 = 9,75", "La respuesta es menor que la cinta inicial."),
    ],
  }),
  question({
    id: "NO03-N3-19", family: "decimal-problems", level: 3, title: "Costo de varios cuadernos",
    prompt: "Cada cuaderno cuesta $1,85. ¿Cuánto cuestan 6 cuadernos?", hint: "Se repite seis veces el mismo precio.",
    answer: "$11,10", choices: ["$7,85", "$10,10", "$11,10", "$111,00"],
    wrongFeedback: "La situación requiere 1,85 × 6. El producto es 11,10, no una suma de los dos datos.",
    success: "Seis cuadernos cuestan $11,10.",
    visual: { type: "decimal-story", labels: ["6", "×", "$1,85"], result: "$ ?" },
    steps: [
      step("Paso 1 · estructura", "Hay seis grupos iguales", "6 × 1,85", "La multiplicación resume el precio repetido."),
      step("Paso 2 · calcula", "Multiplica 185 por 6", "185 × 6 = 1.110", "Como 1,85 tiene dos cifras decimales, recuperamos centésimas."),
      step("Paso 3 · expresa dinero", "Coloca la coma y conserva dos decimales", "1.110 centavos = $11,10", "El cero final es útil en una cantidad monetaria."),
    ],
  }),
  question({
    id: "NO03-N3-20", family: "decimal-problems", level: 3, title: "Repartir una capacidad",
    prompt: "Se reparten 18,6 litros por igual en 3 recipientes. ¿Cuánto recibe cada uno?", hint: "La palabra por igual indica una división.",
    answer: "6,2 L", choices: ["5,2 L", "6,2 L", "15,6 L", "55,8 L"],
    wrongFeedback: "Divide el total entre los tres recipientes: 18,6 ÷ 3 = 6,2.",
    success: "Cada recipiente recibe 6,2 litros.",
    visual: { type: "decimal-story", labels: ["18,6 L", "÷", "3 recipientes"], result: "? L cada uno" },
    steps: [
      step("Paso 1 · relación", "El total se reparte en tres partes iguales", "18,6 ÷ 3", "La división encuentra el contenido de cada recipiente."),
      step("Paso 2 · separa", "Divide unidades y décimas", "18 ÷ 3 = 6; 0,6 ÷ 3 = 0,2", "Ambas partes se reparten por igual."),
      step("Paso 3 · reúne", "Suma cada parte del cociente", "6 + 0,2 = 6,2", "Tres recipientes de 6,2 L recuperan 18,6 L."),
    ],
  }),
  question({
    id: "NO03-N1-21", family: "decimal-check", level: 1, title: "Estimar una suma",
    prompt: "¿Cuál es la mejor estimación de 19,8 + 30,3?", hint: "Redondea a números enteros cercanos.",
    answer: "50", choices: ["5", "40", "50", "500"],
    wrongFeedback: "19,8 está cerca de 20 y 30,3 está cerca de 30; 20 + 30 = 50.",
    success: "La mejor estimación es 50; el resultado exacto es 50,1.",
    visual: { type: "decimal-estimate", exact: "19,8 + 30,3", rounded: "20 + 30", estimate: "50" },
    steps: [
      step("Paso 1 · redondea", "Diecinueve coma ocho es casi veinte", "19,8 ≈ 20", "La diferencia es de dos décimas."),
      step("Paso 2 · redondea", "Treinta coma tres es casi treinta", "30,3 ≈ 30", "La diferencia es de tres décimas."),
      step("Paso 3 · estima", "Suma los valores cercanos", "20 + 30 = 50", "El exacto 50,1 está muy cerca."),
    ],
  }),
  question({
    id: "NO03-N2-22", family: "decimal-check", level: 2, title: "Resultado razonable",
    prompt: "¿Cuál resultado puede corresponder a 4,9 × 2,1?", hint: "Aproxima como 5 × 2.",
    answer: "10,29", choices: ["1,029", "10,29", "102,9", "1.029"],
    wrongFeedback: "4,9 × 2,1 debe estar cerca de 5 × 2 = 10. Solo 10,29 tiene esa magnitud.",
    success: "10,29 es razonable y es el producto exacto.",
    visual: { type: "decimal-estimate", exact: "4,9 × 2,1", rounded: "5 × 2", estimate: "≈ 10" },
    steps: [
      step("Paso 1 · aproxima", "Usa enteros cercanos", "4,9 ≈ 5; 2,1 ≈ 2", "La estimación conserva la magnitud."),
      step("Paso 2 · referencia", "Multiplica los aproximados", "5 × 2 = 10", "La respuesta correcta debe rondar diez."),
      step("Paso 3 · selecciona", "Diez coma veintinueve está cerca", "4,9 × 2,1 = 10,29", "Las demás opciones colocan mal la coma."),
    ],
  }),
  question({
    id: "NO03-N3-23", family: "decimal-check", level: 3, title: "Una suma mal alineada",
    prompt: "Sofía escribió 7,3 + 2,48 = 9,51. ¿Cuál es el resultado correcto?", hint: "Escribe 7,3 como 7,30.",
    answer: "9,78", choices: ["9,51", "9,78", "10,78", "97,8"],
    wrongFeedback: "La suma correcta es 7,30 + 2,48. Sofía no mantuvo cada cifra en su posición decimal.",
    success: "7,30 + 2,48 = 9,78.",
    visual: { type: "decimal-error", claim: "7,3 + 2,48 = 9,51", correction: "7,30 + 2,48" },
    steps: [
      step("Paso 1 · detecta", "Falta una centésima visible", "7,3 = 7,30", "Sin alinear la coma, se mezclan décimas y centésimas."),
      step("Paso 2 · suma posiciones", "Calcula centésimas y décimas", "0 + 8 = 8; 3 + 4 = 7", "Luego suma unidades: 7 + 2 = 9."),
      step("Paso 3 · corrige", "Conserva la coma", "7,30 + 2,48 = 9,78", "La estimación 7 + 2,5 ≈ 9,5 también descarta errores grandes."),
    ],
  }),
  question({
    id: "NO03-N3-24", family: "decimal-check", level: 3, title: "Una coma olvidada",
    prompt: "Diego afirma que 4,2 × 0,3 = 12,6. ¿Cuál es el producto correcto?", hint: "Multiplicar por 0,3 debe dar una parte de 4,2, no un número mayor.",
    answer: "1,26", choices: ["0,126", "1,26", "12,6", "126"],
    wrongFeedback: "42 × 3 = 126, pero los factores reúnen dos cifras decimales. Además, el resultado debe ser menor que 4,2.",
    success: "4,2 × 0,3 = 1,26.",
    visual: { type: "decimal-error", claim: "4,2 × 0,3 = 12,6", correction: "42 × 3 = 126; dos decimales" },
    steps: [
      step("Paso 1 · magnitud", "Tres décimas de 4,2 es menos que 4,2", "4,2 × 0,3 < 4,2", "La afirmación 12,6 no puede ser razonable."),
      step("Paso 2 · multiplica", "Calcula las cifras", "42 × 3 = 126", "Los factores tienen dos cifras decimales en total."),
      step("Paso 3 · coloca la coma", "Recupera dos posiciones", "126 → 1,26", "El producto correcto es 1,26."),
    ],
  }),
];

export const DECIMAL_OPERATION_QUESTIONS = questions.map((item, index) => ({
  ...item,
  number: index + 1,
  skillId: "NO03",
  familyLabel: DECIMAL_OPERATION_FAMILIES.find((family) => family.id === item.family)?.label,
  skillLabel: "Operaciones con decimales",
}));
