const family = (id, label, short) => ({ id, label, short });

export const FRACTION_SKILL_DEFINITIONS = [
  { id: "FR01", title: "Significado de las fracciones", short: "Significado", symbol: "½", description: "Conecta partes, repartos, conjuntos y puntos de la recta.", families: [family("part-whole", "Partes de un todo", "Parte–todo"), family("unit", "Fracciones unitarias", "Unitarias"), family("fraction-line", "Fracciones en la recta", "Recta"), family("quotient", "Fracción como reparto", "Repartos"), family("fraction-set", "Fracción de un conjunto", "Conjuntos"), family("mixed", "Impropias y números mixtos", "Mixtos")] },
  { id: "FR02", title: "Equivalencia y comparación", short: "Equivalencia", symbol: "≡", description: "Reconoce el mismo valor con particiones distintas y compara con evidencia.", families: [family("equivalent", "Fracciones equivalentes", "Equivalentes"), family("simplify", "Simplificación", "Simplificar"), family("compare", "Comparación de dos fracciones", "Comparar"), family("order", "Orden de fracciones", "Ordenar"), family("benchmark", "Referentes 0, 1/2 y 1", "Referentes"), family("missing", "Término desconocido", "Valor faltante")] },
  { id: "FR03", title: "Suma y resta de fracciones", short: "Suma y resta", symbol: "+/−", description: "Reúne o separa partes del mismo tamaño y justifica el denominador común.", families: [family("same-den", "Igual denominador", "Mismo denominador"), family("unlike-add", "Suma con denominadores distintos", "Sumar distintos"), family("unlike-subtract", "Resta con denominadores distintos", "Restar distintos"), family("mixed-add", "Operaciones con números mixtos", "Números mixtos"), family("missing-addend", "Término faltante", "Valor faltante"), family("fraction-problem", "Problemas de suma y resta", "Problemas")] },
  { id: "FR04", title: "Multiplicación de fracciones", short: "Multiplicación", symbol: "×", description: "Interpreta una fracción de otra cantidad mediante escala, área y contexto.", families: [family("whole-times", "Entero por fracción", "Entero × fracción"), family("fraction-of", "Fracción de una cantidad", "Fracción de"), family("fraction-times", "Fracción por fracción", "Fracción × fracción"), family("area-model", "Modelo de área", "Área"), family("product-simplify", "Simplificar productos", "Simplificar"), family("fraction-product-problem", "Problemas multiplicativos", "Problemas")] },
  { id: "FR05", title: "División de fracciones", short: "División", symbol: "÷", description: "Decide cuántos grupos caben o cuánto recibe cada grupo.", families: [family("whole-by-fraction", "Entero entre fracción", "Entero ÷ fracción"), family("fraction-by-whole", "Fracción entre entero", "Fracción ÷ entero"), family("fraction-by-fraction", "Fracción entre fracción", "Fracción ÷ fracción"), family("groups", "Medición por grupos", "Cuántos caben"), family("share", "Reparto en partes iguales", "Repartir"), family("division-check", "Comprobación y errores", "Comprobar")] },
  { id: "FR06", title: "Fracciones y decimales", short: "Fracción–decimal", symbol: "0,5", description: "Cambia de representación sin cambiar el valor ni la magnitud.", families: [family("to-decimal", "Fracción a decimal", "A decimal"), family("to-fraction", "Decimal a fracción", "A fracción"), family("decimal-compare", "Comparar representaciones", "Comparar"), family("decimal-order", "Orden mixto", "Ordenar"), family("decimal-line", "Ubicación en la recta", "Recta"), family("decimal-context", "Dinero y medición", "Contextos")] },
];

const gcd = (a, b) => (b ? gcd(b, a % b) : Math.abs(a));
const simp = (n, d) => { const g = gcd(n, d); return [n / g, d / g]; };
const frac = (n, d, simplify = true) => { const [a, b] = simplify ? simp(n, d) : [n, d]; return b === 1 ? `${a}` : `${a}/${b}`; };
const decimal = (value) => Number(value.toFixed(4)).toString().replace(".", ",");
const mixed = (n, d) => { const whole = Math.floor(n / d); const rest = n % d; return rest ? `${whole} ${frac(rest, d)}` : `${whole}`; };

function makeQuestion(skillId, number, familyId, level, title, prompt, hint, answer, distractors, visual, models) {
  const definition = FRACTION_SKILL_DEFINITIONS.find((item) => item.id === skillId);
  const choices = [...new Set([answer, ...distractors])].slice(0, 4);
  while (choices.length < 4) choices.push(`${choices.length + 1}/${choices.length + 2}`);
  const shift = number % choices.length;
  const ordered = [...choices.slice(shift), ...choices.slice(0, shift)];
  return {
    id: `${skillId}-N${level}-${String(number).padStart(2, "0")}`,
    number, skillId, skillLabel: definition.title, family: familyId,
    familyLabel: definition.families.find((item) => item.id === familyId)?.label,
    level, title, prompt, hint, answer, visual,
    options: ordered.map((value) => ({ value, feedback: value === answer ? null : `Vuelve al modelo: ${models[0]}. Después ${models[1]}.` })),
    success: `${models[2]}. La representación y el cálculo expresan la misma cantidad.`,
    steps: models.map((equation, index) => ({
      eyebrow: `Paso ${index + 1} · ${index === 0 ? "representa" : index === 1 ? "relaciona" : "comprueba"}`,
      title: index === 0 ? "Haz visible la unidad" : index === 1 ? "Opera cantidades comparables" : "Conserva el valor",
      equation,
      text: index === 0 ? hint : index === 1 ? "Trabaja con partes del mismo tamaño y simplifica cuando sea posible." : `El resultado esperado es ${answer}.`,
    })),
  };
}

function buildFR01() {
  const result = [];
  const parts = [[3,4],[2,5],[5,6],[3,8]];
  parts.forEach(([n,d], j) => result.push(makeQuestion("FR01", j+1, "part-whole", j<2?1:2, "Leer una parte sombreada", `Una unidad se divide en ${d} partes iguales y se sombrean ${n}. ¿Qué fracción está sombreada?`, "El denominador cuenta todas las partes iguales; el numerador, las seleccionadas.", frac(n,d,false), [frac(d-n,d,false), frac(d,n,false), frac(n,d+1,false)], {type:"bar", numerator:n, denominator:d}, [`total de partes = ${d}`, `partes sombreadas = ${n}`, `fracción = ${n}/${d}`])));
  [3,4,6,8].forEach((d,j)=>result.push(makeQuestion("FR01",j+5,"unit",1,"El tamaño de una parte",`Si una unidad se reparte en ${d} partes iguales, ¿qué fracción representa cada parte?`,"Una fracción unitaria tiene numerador uno.",`1/${d}`,[`${d}/1`,`1/${d+1}`,`${d-1}/${d}`],{type:"bar",numerator:1,denominator:d},[`una unidad completa`,`se forman ${d} partes iguales`,`cada parte = 1/${d}`])));
  [[1,4],[3,5],[5,8],[7,6]].forEach(([n,d],j)=>result.push(makeQuestion("FR01",j+9,"fraction-line",j===3?3:2,"Ubicar una fracción",`¿Qué número representa el punto situado en la marca ${n} cuando cada unidad se divide en ${d} partes iguales?`,"Cuenta desde cero usando intervalos del mismo tamaño.",frac(n,d,false),[frac(n+1,d,false),frac(n,d+1,false),frac(d,n,false)],{type:"line",numerator:n,denominator:d},[`cada salto = 1/${d}`,`${n} saltos desde 0`,`coordenada = ${n}/${d}`])));
  [[1,3],[2,5],[3,4],[5,2]].forEach(([items,people],j)=>result.push(makeQuestion("FR01",j+13,"quotient",j<2?1:2,"Repartir sin perder la unidad",`${items} ${items===1?"pizza se reparte":"pizzas se reparten"} por igual entre ${people} personas. ¿Qué cantidad recibe cada una?`,"La fracción también representa una división.",frac(items,people),[frac(people,items),frac(items,items+people),frac(people-items,people)],{type:"operation",expression:`${items} ÷ ${people}`,stages:[`${items}/${people}`,frac(items,people)]},[`${items} unidades entre ${people}`,`${items} ÷ ${people} = ${items}/${people}`,`cada persona recibe ${frac(items,people)}`])));
  [[3,8],[5,10],[4,12],[9,15]].forEach(([selected,total],j)=>{const answer=frac(selected,total);result.push(makeQuestion("FR01",j+17,"fraction-set",j<2?1:2,"Fracción de un conjunto",`De ${total} fichas, ${selected} son moradas. ¿Qué fracción del conjunto es morada?`,"El conjunto completo es la unidad.",answer,[frac(total-selected,total),frac(total,selected),frac(selected,total,false)],{type:"set",selected,total},[`total = ${total} fichas`,`seleccionadas = ${selected}`,`${selected}/${total} = ${answer}`]));});
  [[7,3],[9,4],[11,5],[14,6]].forEach(([n,d],j)=>result.push(makeQuestion("FR01",j+21,"mixed",j<2?2:3,"De impropia a mixta",`Convierte ${n}/${d} en número mixto.`,"Busca cuántas unidades completas contiene la fracción.",mixed(n,d),[`${Math.floor(n/d)} ${d}/${n%d||1}`,`${n-d}/${d}`,frac(n,d)],{type:"operation",expression:`${n} ÷ ${d}`,stages:[`${Math.floor(n/d)} enteros`,`residuo ${n%d}`]},[`${n} ÷ ${d} = ${Math.floor(n/d)} y sobra ${n%d}`,`resto = ${n%d}/${d}`,`${n}/${d} = ${mixed(n,d)}`])));
  return result;
}

function buildFR02() {
  const result=[];
  [[1,2,3],[2,3,4],[3,5,2],[4,7,3]].forEach(([n,d,k],j)=>result.push(makeQuestion("FR02",j+1,"equivalent",j<2?1:2,"Ampliar sin cambiar",`¿Cuál fracción es equivalente a ${n}/${d} al multiplicar numerador y denominador por ${k}?`,"Multiplica ambas partes por el mismo factor.",`${n*k}/${d*k}`,[`${n*k}/${d}`,`${n}/${d*k}`,`${n+k}/${d+k}`],{type:"compare-bars",fractions:[[n,d],[n*k,d*k]]},[`${n}/${d} × ${k}/${k}`,`${n*k}/${d*k}`,`ambas representan ${n}/${d}`])));
  [[6,8],[12,18],[15,25],[21,28]].forEach(([n,d],j)=>{const answer=frac(n,d);const g=gcd(n,d);result.push(makeQuestion("FR02",j+5,"simplify",j<2?1:2,"Reducir a términos mínimos",`Simplifica ${n}/${d}.`,"Divide numerador y denominador por su máximo factor común.",answer,[frac(n/g+1,d/g),`${n/g}/${d}`,`${n}/${d/g}`],{type:"operation",expression:`${n}/${d} ÷ ${g}/${g}`,stages:[`${n/g}/${d/g}`,answer]},[`factor común = ${g}`,`${n} ÷ ${g} y ${d} ÷ ${g}`,`${n}/${d} = ${answer}`]));});
  [[[3,4],[2,3]],[[5,8],[3,4]],[[7,10],[2,5]],[[5,6],[8,9]]].forEach(([a,b],j)=>{const av=a[0]/a[1],bv=b[0]/b[1],answer=av>bv?`${frac(...a)} > ${frac(...b)}`:`${frac(...a)} < ${frac(...b)}`;result.push(makeQuestion("FR02",j+9,"compare",j<2?2:3,"Comparar dos fracciones",`Completa correctamente la comparación entre ${frac(...a)} y ${frac(...b)}.`,"Usa productos cruzados o un denominador común.",answer,[answer.replace(">","TEMP").replace("<",">").replace("TEMP","<"),`${frac(...a)} = ${frac(...b)}`,"No se puede comparar"],{type:"compare-bars",fractions:[a,b]},[`${a[0]} × ${b[1]} = ${a[0]*b[1]}`,`${b[0]} × ${a[1]} = ${b[0]*a[1]}`,answer]))});
  [[[1,2],[2,3],[3,4]],[[1,3],[3,5],[5,6]],[[2,5],[3,4],[7,10]],[[5,8],[4,5],[2,3]]].forEach((list,j)=>{const ordered=[...list].sort((a,b)=>a[0]/a[1]-b[0]/b[1]).map(x=>frac(...x)).join(", ");result.push(makeQuestion("FR02",j+13,"order",j<2?2:3,"Orden ascendente",`Ordena de menor a mayor: ${list.map(x=>frac(...x)).join(", ")}.`,"Compara todas respecto de la misma unidad.",ordered,[list.map(x=>frac(...x)).reverse().join(", "),list.map(x=>frac(...x)).join(", "),`${frac(...list[1])}, ${frac(...list[0])}, ${frac(...list[2])}`],{type:"multi-bars",fractions:list},["construye valores comparables","ubica de izquierda a derecha",`orden: ${ordered}`]))});
  [[3,8,"menor"],[5,8,"mayor"],[7,12,"mayor"],[4,10,"menor"]].forEach(([n,d,relation],j)=>result.push(makeQuestion("FR02",j+17,"benchmark",j<2?1:2,"Comparar con un medio",`¿${frac(n,d,false)} es mayor o menor que 1/2?`,"Compara el numerador con la mitad del denominador.",`${relation} que 1/2`,[`${relation==="mayor"?"menor":"mayor"} que 1/2`,`igual a 1/2`,`mayor que 1`],{type:"compare-bars",fractions:[[n,d],[1,2]]},[`mitad de ${d} = ${d/2}`,`${n} ${n>d/2?">":"<"} ${d/2}`,`${n}/${d} es ${relation} que 1/2`])));
  [[1,3,4],[2,5,3],[3,4,5],[5,6,2]].forEach(([n,d,k],j)=>result.push(makeQuestion("FR02",j+21,"missing",j<2?2:3,"Numerador desconocido",`Completa: ${n}/${d} = ?/${d*k}.`,"El denominador se multiplicó; aplica el mismo factor arriba.",`${n*k}`,[`${n+k}`,`${d*k}`,`${n}`],{type:"operation",expression:`${n}/${d} = ?/${d*k}`,stages:[`factor ${k}`,`${n} × ${k}`]},[`${d} × ${k} = ${d*k}`,`${n} × ${k} = ${n*k}`,`valor faltante = ${n*k}`])));
  return result;
}

function buildFR03(){
  const result=[];
  [[2,5,1],[3,8,2],[5,9,1],[7,12,3]].forEach(([a,d,b],j)=>{const ans=frac(a+b,d);result.push(makeQuestion("FR03",j+1,"same-den",j<2?1:2,"Reunir partes iguales",`Calcula ${a}/${d} + ${b}/${d}.`,"Las partes ya tienen el mismo tamaño.",ans,[frac(a+b,d*2),frac(a*b,d),`${a+b}/${d+1}`],{type:"operation",expression:`${a}/${d} + ${b}/${d}`,stages:[`${a+b}/${d}`,ans]},[`denominador común = ${d}`,`${a} + ${b} = ${a+b}`,`resultado = ${ans}`]))});
  [[1,2,1,3],[2,3,1,4],[3,5,1,2],[5,6,2,9]].forEach(([a,b,c,d],j)=>{const ans=frac(a*d+c*b,b*d);result.push(makeQuestion("FR03",j+5,"unlike-add",j<2?2:3,"Sumar partes distintas",`Calcula ${a}/${b} + ${c}/${d}.`,"Construye un denominador común antes de sumar.",ans,[frac(a+c,b+d),frac(a+c,b*d),frac(a*d+c*b,b+d)],{type:"operation",expression:`${a}/${b} + ${c}/${d}`,stages:[`denominador ${b*d}`,`${a*d}/${b*d} + ${c*b}/${b*d}`,ans]},[`denominador común = ${b*d}`,`${a*d} + ${c*b} = ${a*d+c*b}`,`resultado = ${ans}`]))});
  [[3,4,1,6],[5,6,1,4],[7,8,2,3],[11,12,3,8]].forEach(([a,b,c,d],j)=>{const ans=frac(a*d-c*b,b*d);result.push(makeQuestion("FR03",j+9,"unlike-subtract",j<2?2:3,"Restar con denominador común",`Calcula ${a}/${b} − ${c}/${d}.`,"Transforma ambas fracciones en partes del mismo tamaño.",ans,[frac(a-c,b-d||1),frac(a*d-c*b,b+d),frac(a-c,b*d)],{type:"operation",expression:`${a}/${b} − ${c}/${d}`,stages:[`denominador ${b*d}`,`${a*d}/${b*d} − ${c*b}/${b*d}`,ans]},[`denominador común = ${b*d}`,`${a*d} − ${c*b} = ${a*d-c*b}`,`resultado = ${ans}`]))});
  [[1,1,2,2,1,4],[2,1,3,1,2,3],[3,3,4,1,5,8],[4,1,6,2,2,3]].forEach(([w1,n1,d1,w2,n2,d2],j)=>{const total1=w1+n1/d1,total2=w2+n2/d2,ans=frac(Math.round((total1+total2)*d1*d2),d1*d2);result.push(makeQuestion("FR03",j+13,"mixed-add",j<2?2:3,"Sumar números mixtos",`Calcula ${w1} ${n1}/${d1} + ${w2} ${n2}/${d2}.`,"Convierte a impropias o suma enteros y fracciones por separado.",mixed(Math.round((total1+total2)*d1*d2),d1*d2),[`${w1+w2} ${frac(n1+n2,d1+d2)}`,ans,`${w1+w2}`],{type:"operation",expression:`${w1} ${n1}/${d1} + ${w2} ${n2}/${d2}`,stages:[frac(w1*d1+n1,d1),frac(w2*d2+n2,d2),ans]},["convierte cada mixto","suma las impropias",`resultado = ${mixed(Math.round((total1+total2)*d1*d2),d1*d2)}`]))});
  [[1,4,3,4],[2,5,4,5],[1,3,5,6],[3,8,7,8]].forEach(([a,b,c,d],j)=>{const target=c/d,start=a/b,ans=frac(Math.round((target-start)*b*d),b*d);result.push(makeQuestion("FR03",j+17,"missing-addend",j<2?2:3,"Sumando desconocido",`Completa: ${a}/${b} + ? = ${c}/${d}.`,"Resta la parte conocida al total.",ans,[frac(c-a,d),frac(a+c,b+d),frac(c*b-a*d,b*d+1)],{type:"operation",expression:`? = ${c}/${d} − ${a}/${b}`,stages:["denominador común",ans,`${a}/${b} + ${ans}`]},[`? = total − parte conocida`,`calcula ${c}/${d} − ${a}/${b}`,`valor faltante = ${ans}`]))});
  [
    { prompt:"De una cinta de 3/4 de metro se cortan 1/6 de metro. ¿Cuánta cinta queda?", a:3,b:4,c:1,d:6,op:"−" },
    { prompt:"En la mañana se recorre 2/5 de una ruta y en la tarde 1/4. ¿Qué fracción de la ruta se recorre en total?", a:2,b:5,c:1,d:4,op:"+" },
    { prompt:"Una jarra contiene 5/6 de litro y se sirven 1/3 de litro. ¿Cuánto queda en la jarra?", a:5,b:6,c:1,d:3,op:"−" },
    { prompt:"El lunes se lee 3/8 de un libro y el martes 5/12. ¿Qué fracción se lee entre los dos días?", a:3,b:8,c:5,d:12,op:"+" },
  ].forEach(({prompt,a,b,c,d,op},j)=>{const subtract=op==="−",ans=subtract?frac(a*d-c*b,b*d):frac(a*d+c*b,b*d);result.push(makeQuestion("FR03",j+21,"fraction-problem",j<2?2:3,"Elegir la operación",prompt,"Decide si la situación reúne cantidades o encuentra lo restante.",ans,[frac(a+c,b+d),frac(Math.abs(a*d-c*b),b*d),frac(a*d+c*b,b+d)],{type:"operation",expression:`${a}/${b} ${op} ${c}/${d}`,stages:[`operación: ${op}`,"denominador común",ans]},[`traduce con ${op}`,"iguala denominadores",`resultado = ${ans}`]))});
  return result;
}

function buildFR04(){
  const result=[];
  [[3,2,5],[4,3,7],[6,5,8],[9,2,3]].forEach(([whole,n,d],j)=>{const ans=frac(whole*n,d);result.push(makeQuestion("FR04",j+1,"whole-times",j<2?1:2,"Varios grupos fraccionarios",`Calcula ${whole} × ${n}/${d}.`,"Multiplica el entero por el numerador.",ans,[frac(whole+n,d),frac(whole*n,d*whole),frac(whole,d*n)],{type:"operation",expression:`${whole} × ${n}/${d}`,stages:[`${whole*n}/${d}`,ans]},[`${whole} grupos de ${n}/${d}`,`${whole} × ${n} = ${whole*n}`,`resultado = ${ans}`]))});
  [[1,2,18],[2,3,24],[3,5,40],[5,8,64]].forEach(([n,d,total],j)=>{const ans=`${total*n/d}`;result.push(makeQuestion("FR04",j+5,"fraction-of",j<2?1:2,"Una fracción de una cantidad",`¿Cuánto es ${n}/${d} de ${total}?`,"Divide la cantidad en tantas partes como indica el denominador.",ans,[`${total/d}`,`${total*d/n}`,`${total-n}`],{type:"set",selected:total*n/d,total},[`${total} ÷ ${d} = ${total/d}`,`${total/d} × ${n}`,`${n}/${d} de ${total} = ${ans}`]))});
  [[1,2,3,4],[2,3,3,5],[4,7,7,8],[5,6,9,10]].forEach(([a,b,c,d],j)=>{const ans=frac(a*c,b*d);result.push(makeQuestion("FR04",j+9,"fraction-times",j<2?2:3,"Una parte de otra parte",`Calcula ${a}/${b} × ${c}/${d}.`,"Multiplica numeradores y denominadores; después simplifica.",ans,[frac(a+c,b+d),frac(a*d,b*c),frac(a*c,b+d)],{type:"area",fractions:[[a,b],[c,d]]},[`${a} × ${c} = ${a*c}`,`${b} × ${d} = ${b*d}`,`${a*c}/${b*d} = ${ans}`]))});
  [[1,3,2,5],[3,4,2,3],[5,6,3,5],[7,8,4,7]].forEach(([a,b,c,d],j)=>{const ans=frac(a*c,b*d);result.push(makeQuestion("FR04",j+13,"area-model",j<2?2:3,"Superposición de áreas",`Un rectángulo sombrea ${a}/${b} en una dirección y ${c}/${d} en la otra. ¿Qué fracción queda superpuesta?`,"La intersección representa el producto.",ans,[frac(a+c,b+d),frac(a*c,b+d),frac(a+c,b*d)],{type:"area",fractions:[[a,b],[c,d]]},[`${b} × ${d} partes pequeñas`,`${a} × ${c} superpuestas`, `área = ${ans}`]))});
  [[6,8,2,3],[9,10,5,6],[14,15,3,7],[8,21,7,16]].forEach(([a,b,c,d],j)=>{const ans=frac(a*c,b*d);result.push(makeQuestion("FR04",j+17,"product-simplify",j<2?2:3,"Simplificar antes de multiplicar",`Calcula y simplifica ${a}/${b} × ${c}/${d}.`,"Busca factores que se cancelen entre numeradores y denominadores.",ans,[frac(a*c,b+d),frac(a+c,b*d),frac(a*d,b*c)],{type:"operation",expression:`${a}/${b} × ${c}/${d}`,stages:["cancela factores comunes",`${a*c}/${b*d}`,ans]},["simplifica en cruz",`producto = ${a*c}/${b*d}`,`forma mínima = ${ans}`]))});
  [["Una receta",3,4,2],["Un terreno",2,5,3],["Una botella",5,6,4],["Un camino",7,8,3]].forEach(([context,n,d,factor],j)=>{const ans=frac(n*factor,d);result.push(makeQuestion("FR04",j+21,"fraction-product-problem",j<2?2:3,"Escalar una cantidad",`${context} usa ${n}/${d} de unidad por grupo. ¿Cuánto se usa en ${factor} grupos?`,"La misma cantidad se repite varias veces.",ans,[frac(n+factor,d),frac(n,d*factor),frac(n*factor,d*factor)],{type:"operation",expression:`${factor} × ${n}/${d}`,stages:[`${factor} grupos`,`${factor*n}/${d}`,ans]},[`modelo = ${factor} × ${n}/${d}`,"multiplica y simplifica",`total = ${ans}`]))});
  return result;
}

function buildFR05(){
  const result=[];
  [[2,1,2],[3,1,3],[4,2,5],[5,5,8]].forEach(([whole,n,d],j)=>{const ans=frac(whole*d,n);result.push(makeQuestion("FR05",j+1,"whole-by-fraction",j<2?1:2,"Cuántas fracciones caben",`¿Cuánto es ${whole} ÷ ${n}/${d}?`,"Pregunta cuántos grupos de esa fracción caben en el entero.",ans,[frac(whole*n,d),frac(d,whole*n),frac(whole,d)],{type:"operation",expression:`${whole} ÷ ${n}/${d}`,stages:[`recíproco ${d}/${n}`,`${whole} × ${d}/${n}`,ans]},["convierte la división en medición","multiplica por el recíproco",`resultado = ${ans}`]))});
  [[3,4,2],[5,6,3],[7,8,4],[9,10,5]].forEach(([n,d,whole],j)=>{const ans=frac(n,d*whole);result.push(makeQuestion("FR05",j+5,"fraction-by-whole",j<2?1:2,"Repartir una fracción",`Calcula ${n}/${d} ÷ ${whole}.`,"Repartir en más grupos produce partes más pequeñas.",ans,[frac(n*whole,d),frac(n,d+whole),frac(whole*n,d*whole)],{type:"operation",expression:`${n}/${d} ÷ ${whole}`,stages:[`${n}/${d} × 1/${whole}`,`${n}/${d*whole}`,ans]},["cada grupo recibe una parte","multiplica por 1 sobre el entero",`resultado = ${ans}`]))});
  [[3,4,1,2],[2,3,4,5],[5,6,5,12],[7,8,14,15]].forEach(([a,b,c,d],j)=>{const ans=frac(a*d,b*c);result.push(makeQuestion("FR05",j+9,"fraction-by-fraction",j<2?2:3,"Dividir dos fracciones",`Calcula ${a}/${b} ÷ ${c}/${d}.`,"Conserva la primera fracción y multiplica por el recíproco de la segunda.",ans,[frac(a*c,b*d),frac(a*d,b+c),frac(c*b,d*a)],{type:"operation",expression:`${a}/${b} ÷ ${c}/${d}`,stages:[`recíproco ${d}/${c}`,`${a}/${b} × ${d}/${c}`,ans]},["invierte solo el divisor","multiplica numeradores y denominadores",`resultado = ${ans}`]))});
  [[2,1,4],[3,3,8],[4,2,3],[5,5,6]].forEach(([total,n,d],j)=>{const ans=frac(total*d,n);result.push(makeQuestion("FR05",j+13,"groups",j<2?2:3,"Medir cuántos grupos",`Hay ${total} unidades. ¿Cuántos grupos de ${n}/${d} caben?`,"La pregunta busca cantidad de grupos, no tamaño de cada grupo.",ans,[frac(total*n,d),frac(total,d),frac(d,total*n)],{type:"operation",expression:`${total} ÷ ${n}/${d}`,stages:[`tamaño de grupo ${n}/${d}`,`multiplica por ${d}/${n}`,ans]},["identifica el tamaño de cada grupo","divide el total por ese tamaño",`caben ${ans} grupos`]))});
  [[3,4,2],[5,6,4],[7,8,3],[11,12,5]].forEach(([n,d,people],j)=>{const ans=frac(n,d*people);result.push(makeQuestion("FR05",j+17,"share",j<2?2:3,"Repartir entre personas",`${n}/${d} de litro se reparte por igual entre ${people} personas. ¿Cuánto recibe cada una?`,"Divide la cantidad total entre el número de personas.",ans,[frac(n*people,d),frac(n,d+people),frac(people,n*d)],{type:"operation",expression:`${n}/${d} ÷ ${people}`,stages:[`× 1/${people}`,`${n}/${d*people}`,ans]},["total entre personas","multiplica por la fracción unitaria",`cada una recibe ${ans}`]))});
  [["2 ÷ 1/4 = 1/2","8"],["3/5 ÷ 2 = 6/5","3/10"],["2/3 ÷ 4/5 = 8/15","5/6"],["5/6 ÷ 5/12 = 25/72","2"]].forEach(([claim,answer],j)=>result.push(makeQuestion("FR05",j+21,"division-check",j<2?2:3,"Detectar una división incorrecta",`Se afirmó que ${claim}. ¿Cuál es el resultado correcto?`,"Comprueba multiplicando el cociente por el divisor.",answer,[claim.split(" = ")[1],frac(j+1,j+3),`${Number(j)+1}`],{type:"error",claim,check:"multiplica por el recíproco y verifica"},["identifica el divisor","usa su recíproco",`resultado correcto = ${answer}`])));
  return result;
}

function buildFR06(){
  const result=[];
  [[1,2],[3,4],[2,5],[7,8]].forEach(([n,d],j)=>{const ans=decimal(n/d);result.push(makeQuestion("FR06",j+1,"to-decimal",j<2?1:2,"Convertir a decimal",`¿Qué decimal equivale a ${n}/${d}?`,"Divide el numerador entre el denominador.",ans,[decimal(d/n),decimal((n+1)/d),decimal(n/(d*10))],{type:"decimal",value:n/d,label:`${n}/${d}`},[`${n} ÷ ${d}`,`cociente = ${ans}`,`${n}/${d} = ${ans}`]))});
  [[0.3,3,10],[0.45,45,100],[0.625,625,1000],[1.25,125,100]].forEach(([value,n,d],j)=>{const ans=frac(n,d);result.push(makeQuestion("FR06",j+5,"to-fraction",j<2?1:2,"Escribir decimal como fracción",`Convierte ${decimal(value)} en una fracción simplificada.`,"Usa 10, 100 o 1.000 según la cantidad de cifras decimales.",ans,[`${n}/${d}`,frac(n+1,d),frac(n,d*10)],{type:"decimal",value:value%1,label:decimal(value)},[`${decimal(value)} = ${n}/${d}`,"simplifica numerador y denominador",`forma mínima = ${ans}`]))});
  [[[1,2],0.45],[[3,4],0.8],[[2,5],0.35],[[7,8],0.82]].forEach(([f,v],j)=>{const fv=f[0]/f[1],sign=fv>v?">":"<",ans=`${frac(...f)} ${sign} ${decimal(v)}`;result.push(makeQuestion("FR06",j+9,"decimal-compare",j<2?2:3,"Comparar formatos distintos",`Completa la comparación entre ${frac(...f)} y ${decimal(v)}.`,"Convierte ambos a la misma representación.",ans,[ans.replace(">","TEMP").replace("<",">").replace("TEMP","<"),`${frac(...f)} = ${decimal(v)}`,"No se puede comparar"],{type:"compare-mixed",fraction:f,decimal:v},[`${frac(...f)} = ${decimal(fv)}`,`${decimal(fv)} ${sign} ${decimal(v)}`,ans]))});
  [[[1,2],0.25,[3,4]],[[2,5],0.6,[4,5]],[[1,8],0.5,[7,8]],[[3,10],0.35,[2,5]]].forEach((list,j)=>{const vals=[{s:frac(...list[0]),v:list[0][0]/list[0][1]},{s:decimal(list[1]),v:list[1]},{s:frac(...list[2]),v:list[2][0]/list[2][1]}];const ans=vals.sort((a,b)=>a.v-b.v).map(x=>x.s).join(", ");result.push(makeQuestion("FR06",j+13,"decimal-order",j<2?2:3,"Orden mixto",`Ordena de menor a mayor: ${frac(...list[0])}, ${decimal(list[1])}, ${frac(...list[2])}.`,"Convierte temporalmente a decimales comparables.",ans,[ans.split(", ").reverse().join(", "),`${frac(...list[0])}, ${decimal(list[1])}, ${frac(...list[2])}`,"Todos son iguales"],{type:"multi-mixed",values:vals},["convierte cada cantidad","compara de izquierda a derecha",`orden = ${ans}`]))});
  [[1,4],[3,5],[7,10],[9,8]].forEach(([n,d],j)=>result.push(makeQuestion("FR06",j+17,"decimal-line",j<2?2:3,"Dos nombres para un punto",`¿Qué decimal corresponde al punto ${n}/${d} en la recta?`,"La coordenada no cambia al cambiar de notación.",decimal(n/d),[decimal((n+1)/d),decimal(n/(d+1)),decimal(d/n)],{type:"line",numerator:n,denominator:d},[`${n}/${d} = ${n} ÷ ${d}`,`cociente = ${decimal(n/d)}`,`misma coordenada = ${decimal(n/d)}`])));
  [["metro",3,4],["dólar",1,2],["litro",2,5],["kilogramo",7,10]].forEach(([unit,n,d],j)=>result.push(makeQuestion("FR06",j+21,"decimal-context",j<2?1:2,"Cambiar de representación",`Una medida es ${n}/${d} de ${unit}. ¿Cómo se escribe en decimal?`,"Divide para expresar la misma parte con notación decimal.",decimal(n/d),[decimal(d/n),decimal((n+1)/d),`${n},${d}`],{type:"decimal",value:n/d,label:`${n}/${d} de ${unit}`},[`${n} ÷ ${d}`,`decimal = ${decimal(n/d)}`,`medida = ${decimal(n/d)} de ${unit}`])));
  return result;
}

export const FRACTION_SKILLS = FRACTION_SKILL_DEFINITIONS.map((definition, index) => ({
  ...definition,
  questions: [buildFR01, buildFR02, buildFR03, buildFR04, buildFR05, buildFR06][index](),
}));

export const FRACTION_QUESTIONS = FRACTION_SKILLS.flatMap((skill) => skill.questions);
