import { GEOMETRY_QUESTIONS as ANGLE_QUESTIONS } from "./geometryQuestions.js";

const step = (eyebrow, title, equation, text) => ({ eyebrow, title, equation, text });

function question(config) {
  return {
    ...config,
    options: config.choices.map((value) => ({
      value,
      feedback: value === config.answer ? null : config.wrongFeedback,
    })),
    choices: undefined,
    wrongFeedback: undefined,
  };
}

export const GEOMETRY_SKILLS = [
  { id: "GM01", label: "Unidades, conversiones y escala", short: "Unidades y escala", symbol: "↔" },
  { id: "GM02", label: "Perímetro, área y volumen", short: "Área y volumen", symbol: "▱" },
  { id: "GM03", label: "Ángulos y triángulos", short: "Ángulos", symbol: "△" },
];

export const GEOMETRY_MVP_FAMILIES = [
  { id: "unit-choice", skillId: "GM01", label: "Elegir la unidad", short: "Unidad" },
  { id: "length-conversion", skillId: "GM01", label: "Conversiones de longitud", short: "Convertir" },
  { id: "mixed-measures", skillId: "GM01", label: "Medidas combinadas", short: "Combinar" },
  { id: "scale-drawings", skillId: "GM01", label: "Planos y modelos a escala", short: "Escala" },
  { id: "map-routes", skillId: "GM01", label: "Mapas y recorridos", short: "Mapas" },
  { id: "measure-reasoning", skillId: "GM01", label: "Razonamiento con medidas", short: "Razonar" },
  { id: "perimeter", skillId: "GM02", label: "Perímetros", short: "Perímetro" },
  { id: "basic-area", skillId: "GM02", label: "Áreas fundamentales", short: "Área" },
  { id: "composite-area", skillId: "GM02", label: "Figuras compuestas", short: "Compuestas" },
  { id: "inverse-measure", skillId: "GM02", label: "Encontrar una medida", short: "Inversas" },
  { id: "volume", skillId: "GM02", label: "Volumen", short: "Volumen" },
  { id: "measure-combined", skillId: "GM02", label: "Problemas de varios pasos", short: "Problemas" },
  { id: "classify", skillId: "GM03", label: "Reconocer ángulos", short: "Reconocer" },
  { id: "triangle-sum", skillId: "GM03", label: "Suma del triángulo", short: "Triángulos" },
  { id: "angle-pairs", skillId: "GM03", label: "Pares de ángulos", short: "Pares" },
  { id: "intersections", skillId: "GM03", label: "Rectas que se cruzan", short: "Rectas" },
  { id: "special-triangles", skillId: "GM03", label: "Triángulos especiales", short: "Especiales" },
  { id: "combined", skillId: "GM03", label: "Razonamiento combinado", short: "Razonamiento" },
];

const GM01_QUESTIONS = [
  question({
    id: "GM01-N1-01", skillId: "GM01", family: "unit-choice", level: 1,
    title: "El largo de un lápiz", prompt: "¿Cuál es la unidad más adecuada para medir un lápiz?",
    hint: "Piensa en una medida que permita expresar aproximadamente 18 unidades.",
    answer: "Centímetros", choices: ["Milímetros", "Centímetros", "Metros", "Kilómetros"],
    wrongFeedback: "La unidad debe corresponder al tamaño del objeto: un lápiz suele medir varias decenas de centímetros.",
    success: "Los centímetros describen el largo de un lápiz con un número cómodo.",
    visual: { type: "measurement-card", kind: "pencil", caption: "Largo de un lápiz", estimate: "aprox. 18 ?" },
    steps: [
      step("Paso 1 · estima", "Un lápiz cabe sobre una mesa", "aprox. 18 unidades", "No es tan pequeño como para necesitar solo milímetros ni tan largo como para usar metros."),
      step("Paso 2 · compara unidades", "Un centímetro es una referencia útil", "1 cm = 10 mm", "Con centímetros obtenemos una cantidad fácil de leer y suficientemente precisa."),
      step("Paso 3 · elige", "La unidad adecuada es el centímetro", "lápiz → centímetros", "Un resultado razonable sería aproximadamente 18 cm."),
    ],
  }),
  question({
    id: "GM01-N1-02", skillId: "GM01", family: "unit-choice", level: 1,
    title: "El ancho de una habitación", prompt: "¿En qué unidad conviene medir el ancho de una habitación?",
    hint: "Una habitación suele medir entre 2 y 10 de estas unidades.",
    answer: "Metros", choices: ["Milímetros", "Centímetros", "Metros", "Kilómetros"],
    wrongFeedback: "Busca una unidad apropiada para distancias de varios pasos; centímetros darían un número innecesariamente grande.",
    success: "Los metros son adecuados para dimensiones de una habitación.",
    visual: { type: "measurement-card", kind: "room", caption: "Ancho de la habitación", estimate: "aprox. 4 ?" },
    steps: [
      step("Paso 1 · estima", "El ancho equivale a varios pasos", "aprox. 4 unidades", "La medida es mayor que un objeto de escritorio y mucho menor que una distancia entre ciudades."),
      step("Paso 2 · relaciona", "Un paso se aproxima a un metro", "habitación ≈ pocos metros", "Los metros producen una cantidad manejable para espacios interiores."),
      step("Paso 3 · responde", "Usa metros", "4 m", "Expresarlo como 400 cm sería correcto, pero menos natural para este contexto."),
    ],
  }),
  question({
    id: "GM01-N1-03", skillId: "GM01", family: "unit-choice", level: 1,
    title: "Entre dos ciudades", prompt: "¿Qué unidad usarías para la distancia por carretera entre dos ciudades?",
    hint: "Se trata de una distancia que puede tomar varias horas de viaje.",
    answer: "Kilómetros", choices: ["Milímetros", "Centímetros", "Metros", "Kilómetros"],
    wrongFeedback: "Para recorridos largos se utiliza una unidad mayor; expresar cientos de kilómetros en metros produciría números enormes.",
    success: "Las distancias entre ciudades se expresan normalmente en kilómetros.",
    visual: { type: "measurement-card", kind: "cities", caption: "Ciudad A — Ciudad B", estimate: "aprox. 420 ?" },
    steps: [
      step("Paso 1 · reconoce la escala", "Es un recorrido largo", "varias horas de viaje", "No estamos midiendo un objeto ni una habitación."),
      step("Paso 2 · usa una unidad grande", "Mil metros forman un kilómetro", "1 km = 1.000 m", "El kilómetro evita escribir cientos de miles de metros."),
      step("Paso 3 · elige", "La distancia se expresa en kilómetros", "aprox. 420 km", "La unidad concuerda con la magnitud del recorrido."),
    ],
  }),
  question({
    id: "GM01-N1-04", skillId: "GM01", family: "unit-choice", level: 1,
    title: "El grosor de una moneda", prompt: "¿Cuál es la unidad más práctica para medir el grosor de una moneda?",
    hint: "La medida es menor que un centímetro.",
    answer: "Milímetros", choices: ["Milímetros", "Centímetros", "Metros", "Kilómetros"],
    wrongFeedback: "Para espesores muy pequeños conviene dividir el centímetro en diez partes llamadas milímetros.",
    success: "El grosor de una moneda se describe bien con unos pocos milímetros.",
    visual: { type: "measurement-card", kind: "coin", caption: "Grosor de una moneda", estimate: "aprox. 2 ?" },
    steps: [
      step("Paso 1 · observa el tamaño", "Es menor que un centímetro", "grosor < 1 cm", "Necesitamos una unidad pequeña que evite usar un decimal incómodo."),
      step("Paso 2 · divide el centímetro", "Cada centímetro contiene 10 milímetros", "1 cm = 10 mm", "Un grosor cercano a 0,2 cm se expresa mejor como 2 mm."),
      step("Paso 3 · responde", "Usa milímetros", "aprox. 2 mm", "La medida queda precisa y fácil de interpretar."),
    ],
  }),
  question({
    id: "GM01-N1-05", skillId: "GM01", family: "length-conversion", level: 1,
    title: "De metros a centímetros", prompt: "¿Cuántos centímetros son 3,4 metros?",
    hint: "Cada metro contiene 100 centímetros.",
    answer: "340 cm", choices: ["34 cm", "340 cm", "3.400 cm", "0,034 cm"],
    wrongFeedback: "Al pasar de metros a una unidad más pequeña, la cantidad aumenta: multiplica 3,4 por 100.",
    success: "3,4 × 100 = 340 centímetros.",
    visual: { type: "conversion-bar", from: "3,4 m", to: "? cm", factor: "× 100" },
    steps: [
      step("Paso 1 · recuerda", "Un metro tiene 100 centímetros", "1 m = 100 cm", "Los centímetros son unidades más pequeñas."),
      step("Paso 2 · convierte", "Multiplica por 100", "3,4 × 100", "La coma se desplaza dos lugares hacia la derecha."),
      step("Paso 3 · concluye", "La longitud es 340 cm", "3,4 m = 340 cm", "Ambas expresiones representan exactamente la misma distancia."),
    ],
  }),
  question({
    id: "GM01-N2-06", skillId: "GM01", family: "length-conversion", level: 2,
    title: "De centímetros a metros", prompt: "Convierte 275 centímetros a metros.",
    hint: "Ahora pasas a una unidad 100 veces mayor.",
    answer: "2,75 m", choices: ["0,275 m", "2,75 m", "27,5 m", "275 m"],
    wrongFeedback: "Como 100 cm forman 1 m, divide 275 entre 100 y conserva el valor de la longitud.",
    success: "275 ÷ 100 = 2,75 metros.",
    visual: { type: "conversion-bar", from: "275 cm", to: "? m", factor: "÷ 100" },
    steps: [
      step("Paso 1 · relaciona", "Cien centímetros forman un metro", "100 cm = 1 m", "Vamos de una unidad pequeña a una mayor."),
      step("Paso 2 · divide", "Divide entre 100", "275 ÷ 100 = 2,75", "La cantidad numérica disminuye porque cada unidad ahora es mayor."),
      step("Paso 3 · escribe la unidad", "El resultado es 2,75 m", "275 cm = 2,75 m", "La conversión no cambia la longitud real."),
    ],
  }),
  question({
    id: "GM01-N2-07", skillId: "GM01", family: "length-conversion", level: 2,
    title: "Kilómetros en metros", prompt: "Una ruta mide 4,8 km. ¿Cuántos metros son?",
    hint: "Un kilómetro contiene 1.000 metros.",
    answer: "4.800 m", choices: ["480 m", "4.800 m", "48.000 m", "0,0048 m"],
    wrongFeedback: "Para convertir kilómetros a metros multiplica por 1.000: la distancia sigue siendo la misma.",
    success: "4,8 × 1.000 = 4.800 metros.",
    visual: { type: "conversion-bar", from: "4,8 km", to: "? m", factor: "× 1.000" },
    steps: [
      step("Paso 1 · usa la equivalencia", "Un kilómetro son mil metros", "1 km = 1.000 m", "Los metros son más pequeños que los kilómetros."),
      step("Paso 2 · multiplica", "Escala 4,8 por mil", "4,8 × 1.000 = 4.800", "Multiplicar conserva la distancia al cambiar la unidad."),
      step("Paso 3 · responde", "La ruta mide 4.800 m", "4,8 km = 4.800 m", "El número mayor compensa la unidad más pequeña."),
    ],
  }),
  question({
    id: "GM01-N1-08", skillId: "GM01", family: "length-conversion", level: 1,
    title: "Milímetros en centímetros", prompt: "¿A cuántos centímetros equivalen 860 milímetros?",
    hint: "Diez milímetros forman un centímetro.",
    answer: "86 cm", choices: ["8,6 cm", "86 cm", "860 cm", "8.600 cm"],
    wrongFeedback: "Para pasar de milímetros a centímetros divide entre 10, porque la nueva unidad es diez veces mayor.",
    success: "860 ÷ 10 = 86 centímetros.",
    visual: { type: "conversion-bar", from: "860 mm", to: "? cm", factor: "÷ 10" },
    steps: [
      step("Paso 1 · recuerda", "Diez milímetros hacen un centímetro", "10 mm = 1 cm", "Los centímetros agrupan los milímetros de diez en diez."),
      step("Paso 2 · divide", "Forma grupos de diez", "860 ÷ 10 = 86", "Cada grupo representa un centímetro."),
      step("Paso 3 · concluye", "Son 86 cm", "860 mm = 86 cm", "La igualdad conserva la misma longitud."),
    ],
  }),
  question({
    id: "GM01-N2-09", skillId: "GM01", family: "mixed-measures", level: 2,
    title: "Comparar con una sola unidad", prompt: "¿Cuál longitud es mayor: 1,8 m o 175 cm?",
    hint: "Convierte las dos medidas a centímetros.",
    answer: "1,8 m", choices: ["1,8 m", "175 cm", "Son iguales", "No se pueden comparar"],
    wrongFeedback: "Convierte 1,8 m a 180 cm. Después compara 180 con 175.",
    success: "1,8 m equivale a 180 cm, que supera 175 cm por 5 cm.",
    visual: { type: "compare-bars", bars: [{ label: "1,8 m", ratio: 1 }, { label: "175 cm", ratio: 0.972 }] },
    steps: [
      step("Paso 1 · unifica", "Expresa ambas en centímetros", "1,8 m = 180 cm", "No comparamos directamente números escritos en unidades distintas."),
      step("Paso 2 · compara", "Ciento ochenta supera a 175", "180 cm > 175 cm", "La diferencia es de 5 cm."),
      step("Paso 3 · responde", "La mayor es 1,8 m", "1,8 m > 175 cm", "El número 1,8 parece menor, pero su unidad es mucho mayor."),
    ],
  }),
  question({
    id: "GM01-N2-10", skillId: "GM01", family: "mixed-measures", level: 2,
    title: "Dos tramos de cinta", prompt: "Una cinta mide 1 m 25 cm y otra 85 cm. ¿Cuánto miden juntas?",
    hint: "Convierte primero 1 m 25 cm a centímetros.",
    answer: "210 cm", choices: ["110 cm", "200 cm", "210 cm", "1.110 cm"],
    wrongFeedback: "1 m 25 cm son 125 cm. Suma después 125 cm + 85 cm.",
    success: "125 cm + 85 cm = 210 cm.",
    visual: { type: "compare-bars", mode: "sum", bars: [{ label: "1 m 25 cm", ratio: 0.68 }, { label: "85 cm", ratio: 0.46 }] },
    steps: [
      step("Paso 1 · convierte", "Escribe el primer tramo en centímetros", "1 m 25 cm = 125 cm", "Un metro aporta 100 cm y añadimos los otros 25 cm."),
      step("Paso 2 · suma", "Une las longitudes", "125 cm + 85 cm", "Ahora las dos cantidades usan la misma unidad."),
      step("Paso 3 · calcula", "Juntas miden 210 cm", "125 + 85 = 210", "También podríamos expresarlo como 2 m 10 cm."),
    ],
  }),
  question({
    id: "GM01-N3-11", skillId: "GM01", family: "mixed-measures", level: 3,
    title: "Diferencia entre dos recorridos", prompt: "Una ruta mide 2,4 km y otra 650 m menos. ¿Cuánto mide la segunda?",
    hint: "Convierte 2,4 km a metros antes de restar.",
    answer: "1,75 km", choices: ["1,75 km", "1,85 km", "2,335 km", "1.750 km"],
    wrongFeedback: "2,4 km son 2.400 m. Resta 650 m y luego vuelve a expresar el resultado en kilómetros.",
    success: "2.400 m − 650 m = 1.750 m = 1,75 km.",
    visual: { type: "compare-bars", mode: "difference", bars: [{ label: "2,4 km", ratio: 1 }, { label: "650 m menos", ratio: 0.73 }] },
    steps: [
      step("Paso 1 · unifica", "Convierte kilómetros a metros", "2,4 km = 2.400 m", "La diferencia ya está expresada en metros."),
      step("Paso 2 · resta", "Quita los 650 m", "2.400 − 650 = 1.750 m", "Esta es la longitud de la segunda ruta."),
      step("Paso 3 · vuelve a kilómetros", "Divide entre mil", "1.750 m = 1,75 km", "El punto separa miles y la coma expresa la parte decimal."),
    ],
  }),
  question({
    id: "GM01-N2-12", skillId: "GM01", family: "mixed-measures", level: 2,
    title: "Cinta que queda", prompt: "De una cinta de 3 m se cortan 75 cm. ¿Cuántos centímetros quedan?",
    hint: "Tres metros equivalen a 300 centímetros.",
    answer: "225 cm", choices: ["75 cm", "225 cm", "275 cm", "325 cm"],
    wrongFeedback: "Convierte 3 m en 300 cm y resta el tramo cortado: 300 − 75.",
    success: "Después de cortar 75 cm quedan 225 cm.",
    visual: { type: "compare-bars", mode: "cut", bars: [{ label: "3 m", ratio: 1 }, { label: "75 cm", ratio: 0.25 }] },
    steps: [
      step("Paso 1 · convierte", "Expresa todo en centímetros", "3 m = 300 cm", "Así la longitud total y el corte usan la misma unidad."),
      step("Paso 2 · representa el corte", "Quita 75 cm", "300 cm − 75 cm", "No sumamos porque ese tramo deja de pertenecer a la cinta."),
      step("Paso 3 · calcula", "Quedan 225 cm", "300 − 75 = 225", "Esto equivale a 2 m 25 cm."),
    ],
  }),
  question({
    id: "GM01-N2-13", skillId: "GM01", family: "scale-drawings", level: 2,
    title: "Un salón en el plano", prompt: "En un plano, 1 cm representa 4 m. Una pared mide 6 cm. ¿Cuánto mide realmente?",
    hint: "Cada centímetro del dibujo vale cuatro metros reales.",
    answer: "24 m", choices: ["10 m", "20 m", "24 m", "240 m"],
    wrongFeedback: "Multiplica los 6 cm dibujados por 4 m reales por cada centímetro.",
    success: "6 × 4 = 24 metros reales.",
    visual: { type: "scale-plan", mode: "segment", width: 6, scale: "1 cm → 4 m", labels: ["6 cm", "? m"] },
    steps: [
      step("Paso 1 · lee la escala", "Cada centímetro representa 4 m", "1 cm → 4 m", "La escala conecta la medida del dibujo con la real."),
      step("Paso 2 · cuenta unidades", "Hay seis grupos de 4 m", "6 × 4 m", "La pared del plano ocupa 6 cm."),
      step("Paso 3 · calcula", "La pared real mide 24 m", "6 × 4 = 24", "La unidad final debe ser metros, no centímetros."),
    ],
  }),
  question({
    id: "GM01-N2-14", skillId: "GM01", family: "scale-drawings", level: 2,
    title: "Del tamaño real al plano", prompt: "La escala es 1 cm por cada 5 m. ¿Cuántos centímetros representarán una pared de 35 m?",
    hint: "Esta vez conoces la medida real y buscas la del dibujo.",
    answer: "7 cm", choices: ["5 cm", "7 cm", "30 cm", "175 cm"],
    wrongFeedback: "Divide los 35 m reales en grupos de 5 m; cada grupo ocupa 1 cm en el plano.",
    success: "35 ÷ 5 = 7 centímetros en el plano.",
    visual: { type: "scale-plan", mode: "segment", width: 7, scale: "1 cm → 5 m", labels: ["? cm", "35 m reales"] },
    steps: [
      step("Paso 1 · interpreta", "Cinco metros caben en cada centímetro", "5 m → 1 cm", "Ahora recorremos la escala desde la realidad hacia el dibujo."),
      step("Paso 2 · forma grupos", "Divide 35 m entre 5 m", "35 ÷ 5", "El cociente indica cuántos centímetros necesitamos."),
      step("Paso 3 · responde", "En el plano serán 7 cm", "35 ÷ 5 = 7", "Siete centímetros representan los 35 metros reales."),
    ],
  }),
  question({
    id: "GM01-N3-15", skillId: "GM01", family: "scale-drawings", level: 3,
    title: "Área real de un plano", prompt: "Un patio mide 8 cm por 5 cm en un plano donde 1 cm representa 2 m. ¿Cuál es su área real?",
    hint: "Convierte por separado el largo y el ancho antes de calcular el área.",
    answer: "160 m²", choices: ["40 m²", "80 m²", "160 m²", "320 m²"],
    wrongFeedback: "Las dimensiones reales son 16 m y 10 m. El área requiere multiplicarlas, no multiplicar el área dibujada solo por 2.",
    success: "16 m × 10 m = 160 m².",
    visual: { type: "scale-plan", mode: "rectangle", width: 8, height: 5, scale: "1 cm → 2 m", labels: ["8 cm", "5 cm"] },
    steps: [
      step("Paso 1 · convierte el largo", "Ocho centímetros representan 16 m", "8 × 2 = 16 m", "Aplicamos la escala a la primera dimensión."),
      step("Paso 2 · convierte el ancho", "Cinco centímetros representan 10 m", "5 × 2 = 10 m", "La escala también se aplica a la segunda dimensión."),
      step("Paso 3 · calcula el área", "Multiplica las dimensiones reales", "16 m × 10 m = 160 m²", "En áreas, el factor de escala actúa sobre ambas dimensiones."),
    ],
  }),
  question({
    id: "GM01-N3-16", skillId: "GM01", family: "scale-drawings", level: 3,
    title: "Altura de una maqueta", prompt: "Una maqueta está a escala 1:50. Si mide 3,2 cm de alto, ¿cuál es la altura real?",
    hint: "Cada centímetro de la maqueta representa 50 cm reales.",
    answer: "1,6 m", choices: ["0,16 m", "1,6 m", "16 m", "160 m"],
    wrongFeedback: "Multiplica 3,2 cm por 50 y convierte los 160 cm resultantes a metros.",
    success: "3,2 × 50 = 160 cm = 1,6 m.",
    visual: { type: "scale-plan", mode: "model", height: 3.2, scale: "Escala 1:50", labels: ["3,2 cm", "? m"] },
    steps: [
      step("Paso 1 · interpreta 1:50", "Una unidad representa cincuenta", "1 cm → 50 cm", "La medida real utiliza la misma unidad antes de convertir."),
      step("Paso 2 · amplía", "Multiplica la altura de la maqueta", "3,2 × 50 = 160 cm", "La realidad es cincuenta veces más grande."),
      step("Paso 3 · cambia la unidad", "Pasa 160 cm a metros", "160 cm = 1,6 m", "La altura real es 1,6 metros."),
    ],
  }),
  question({
    id: "GM01-N2-17", skillId: "GM01", family: "map-routes", level: 2,
    title: "Ruta medida en el mapa", prompt: "En un mapa, 1 cm representa 2 km. Una ruta mide 7,5 cm. ¿Cuál es la distancia real?",
    hint: "Multiplica la longitud del mapa por los kilómetros de cada centímetro.",
    answer: "15 km", choices: ["5,5 km", "9,5 km", "15 km", "150 km"],
    wrongFeedback: "Cada uno de los 7,5 cm representa 2 km: calcula 7,5 × 2.",
    success: "7,5 × 2 = 15 kilómetros.",
    visual: { type: "route-map", scale: "1 cm → 2 km", labels: ["7,5 cm", "? km"], points: [[0, 0], [2, 1], [4, 0], [6, 2]] },
    steps: [
      step("Paso 1 · lee la leyenda", "Cada centímetro vale 2 km", "1 cm → 2 km", "La línea del mapa es una representación reducida."),
      step("Paso 2 · escala la ruta", "Multiplica 7,5 por 2", "7,5 × 2", "Usamos la misma relación para toda la longitud."),
      step("Paso 3 · responde", "La distancia real es 15 km", "7,5 × 2 = 15", "El resultado se expresa en kilómetros reales."),
    ],
  }),
  question({
    id: "GM01-N2-18", skillId: "GM01", family: "map-routes", level: 2,
    title: "Comprender una escala numérica", prompt: "En un mapa a escala 1:100.000, ¿qué distancia real representan 4 cm?",
    hint: "100.000 cm reales equivalen a 1 km.",
    answer: "4 km", choices: ["400 m", "4 km", "40 km", "400 km"],
    wrongFeedback: "Un centímetro del mapa representa 100.000 cm reales, es decir, 1 km. Multiplica por 4.",
    success: "A escala 1:100.000, 4 cm representan 4 km.",
    visual: { type: "route-map", scale: "Escala 1:100.000", labels: ["4 cm", "? km"], points: [[0, 0], [3, 0.5], [6, 0]] },
    steps: [
      step("Paso 1 · expande la escala", "Un centímetro representa 100.000 cm", "1 cm → 100.000 cm", "Ambos lados comienzan en la misma unidad."),
      step("Paso 2 · convierte la realidad", "Cien mil centímetros son un kilómetro", "100.000 cm = 1 km", "Así podemos leer la escala como 1 cm por 1 km."),
      step("Paso 3 · aplica a cuatro", "Cuatro centímetros representan 4 km", "4 × 1 km = 4 km", "La distancia real es cuatro kilómetros."),
    ],
  }),
  question({
    id: "GM01-N3-19", skillId: "GM01", family: "map-routes", level: 3,
    title: "Recorrido con tres tramos", prompt: "Una ruta tiene tramos de 3 cm, 4 cm y 2 cm. Si 1 cm representa 1,5 km, ¿cuánto mide en realidad?",
    hint: "Suma primero la longitud total dibujada.",
    answer: "13,5 km", choices: ["9 km", "10,5 km", "13,5 km", "15 km"],
    wrongFeedback: "Los tramos suman 9 cm. Después multiplica 9 por 1,5 km por centímetro.",
    success: "(3 + 4 + 2) × 1,5 = 13,5 km.",
    visual: { type: "route-map", scale: "1 cm → 1,5 km", labels: ["3 cm", "4 cm", "2 cm"], points: [[0, 0], [2, 1.5], [5, 0.5], [6.5, 2.2]] },
    steps: [
      step("Paso 1 · suma el dibujo", "Reúne los tres tramos", "3 + 4 + 2 = 9 cm", "La escala se aplica a la longitud total de la ruta."),
      step("Paso 2 · aplica la escala", "Cada centímetro vale 1,5 km", "9 × 1,5 km", "Hay nueve grupos de un kilómetro y medio."),
      step("Paso 3 · calcula", "La ruta real mide 13,5 km", "9 × 1,5 = 13,5", "La suma y la escala se aplican en ese orden."),
    ],
  }),
  question({
    id: "GM01-N2-20", skillId: "GM01", family: "map-routes", level: 2,
    title: "Dibujar una ruta conocida", prompt: "Una ruta real mide 12 km. Si 1 cm representa 3 km, ¿cuánto debe medir en el mapa?",
    hint: "Divide la distancia real en grupos de 3 km.",
    answer: "4 cm", choices: ["3 cm", "4 cm", "9 cm", "36 cm"],
    wrongFeedback: "Cada centímetro contiene 3 km reales. Divide 12 km entre 3 km por centímetro.",
    success: "12 ÷ 3 = 4 centímetros en el mapa.",
    visual: { type: "route-map", scale: "1 cm → 3 km", labels: ["? cm", "12 km reales"], points: [[0, 0], [2, 1], [4, 0.2], [6, 1.3]] },
    steps: [
      step("Paso 1 · identifica la dirección", "Vamos de lo real al mapa", "3 km → 1 cm", "Por eso necesitamos dividir, no multiplicar."),
      step("Paso 2 · forma grupos", "Separa 12 km en grupos de 3", "12 ÷ 3", "Cada grupo ocupará un centímetro."),
      step("Paso 3 · responde", "La línea debe medir 4 cm", "12 ÷ 3 = 4", "Cuatro centímetros representan los doce kilómetros."),
    ],
  }),
  question({
    id: "GM01-N3-21", skillId: "GM01", family: "measure-reasoning", level: 3,
    title: "Detectar una conversión imposible", prompt: "Sofía afirma que 2,5 m equivalen a 2.500 cm. ¿Cuál corrección es válida?",
    hint: "Cada metro contiene 100 centímetros, no 1.000.",
    answer: "2,5 m = 250 cm", choices: ["2,5 m = 25 cm", "2,5 m = 250 cm", "2,5 m = 2.500 cm", "2,5 m = 25.000 cm"],
    wrongFeedback: "Multiplica 2,5 por 100 porque la equivalencia correcta es 1 m = 100 cm.",
    success: "La conversión correcta es 2,5 × 100 = 250 cm.",
    visual: { type: "conversion-bar", from: "2,5 m", to: "2.500 cm", factor: "¿correcto?", error: true },
    steps: [
      step("Paso 1 · revisa el factor", "Un metro no tiene mil centímetros", "1 m = 100 cm", "Sofía utilizó el factor de kilómetros a metros."),
      step("Paso 2 · convierte", "Multiplica 2,5 por cien", "2,5 × 100 = 250", "El valor numérico aumenta dos posiciones."),
      step("Paso 3 · corrige", "La igualdad válida usa 250 cm", "2,5 m = 250 cm", "2.500 cm equivaldrían a 25 metros."),
    ],
  }),
  question({
    id: "GM01-N3-22", skillId: "GM01", family: "measure-reasoning", level: 3,
    title: "Convertir unidades cuadradas", prompt: "¿Cuántos centímetros cuadrados hay en 1 m²?",
    hint: "Un metro tiene 100 cm tanto de largo como de ancho.",
    answer: "10.000 cm²", choices: ["100 cm²", "1.000 cm²", "10.000 cm²", "100.000 cm²"],
    wrongFeedback: "En una superficie el factor 100 aparece en dos dimensiones: calcula 100 cm × 100 cm.",
    success: "1 m² = 100 cm × 100 cm = 10.000 cm².",
    visual: { type: "scale-plan", mode: "square-units", width: 1, height: 1, scale: "1 m = 100 cm", labels: ["1 m", "1 m"] },
    steps: [
      step("Paso 1 · dibuja el metro cuadrado", "Tiene un metro por cada lado", "1 m × 1 m", "El exponente 2 indica que medimos una superficie."),
      step("Paso 2 · convierte ambos lados", "Cada lado mide 100 cm", "100 cm × 100 cm", "No basta multiplicar por 100 una sola vez."),
      step("Paso 3 · calcula", "Hay diez mil centímetros cuadrados", "100 × 100 = 10.000 cm²", "El factor de conversión queda elevado al cuadrado."),
    ],
  }),
  question({
    id: "GM01-N3-23", skillId: "GM01", family: "measure-reasoning", level: 3,
    title: "Suma con metros y centímetros", prompt: "Una tabla mide 2 m 30 cm y otra 1,75 m. ¿Cuánto miden juntas en metros?",
    hint: "Expresa 30 cm como 0,30 m.",
    answer: "4,05 m", choices: ["3,05 m", "3,105 m", "4,05 m", "4,75 m"],
    wrongFeedback: "Primero convierte 2 m 30 cm en 2,30 m. Después suma 2,30 + 1,75.",
    success: "2,30 m + 1,75 m = 4,05 m.",
    visual: { type: "compare-bars", mode: "sum", bars: [{ label: "2 m 30 cm", ratio: 0.92 }, { label: "1,75 m", ratio: 0.7 }] },
    steps: [
      step("Paso 1 · transforma centímetros", "Treinta centímetros son 0,30 m", "30 cm = 0,30 m", "Cien centímetros forman un metro."),
      step("Paso 2 · unifica", "La primera tabla mide 2,30 m", "2 m 30 cm = 2,30 m", "Ahora ambas longitudes usan metros."),
      step("Paso 3 · suma", "Juntas miden 4,05 m", "2,30 + 1,75 = 4,05", "La coma decimal debe quedar alineada al sumar."),
    ],
  }),
  question({
    id: "GM01-N3-24", skillId: "GM01", family: "measure-reasoning", level: 3,
    title: "Perímetro desde un plano", prompt: "Un jardín mide 3 cm por 5 cm en un plano donde 1 cm representa 4 m. ¿Cuál es su perímetro real?",
    hint: "Convierte las dos dimensiones y después rodea el rectángulo.",
    answer: "64 m", choices: ["32 m", "60 m", "64 m", "240 m"],
    wrongFeedback: "Las dimensiones reales son 12 m y 20 m. El perímetro es 2 × (12 + 20).",
    success: "2 × (12 m + 20 m) = 64 m.",
    visual: { type: "scale-plan", mode: "rectangle", width: 5, height: 3, scale: "1 cm → 4 m", labels: ["5 cm", "3 cm"] },
    steps: [
      step("Paso 1 · convierte", "Obtén las dimensiones reales", "5 × 4 = 20 m; 3 × 4 = 12 m", "La escala se aplica al largo y al ancho."),
      step("Paso 2 · plantea el contorno", "Suma los cuatro lados", "20 + 12 + 20 + 12", "El perímetro mide el borde, no la superficie."),
      step("Paso 3 · calcula", "El perímetro es 64 m", "2 × (20 + 12) = 64 m", "La unidad final es lineal: metros."),
    ],
  }),
];

const GM02_QUESTIONS = [
  question({
    id: "GM02-N1-01", skillId: "GM02", family: "perimeter", level: 1,
    title: "Rodear un rectángulo", prompt: "Un rectángulo mide 8 cm de largo y 5 cm de ancho. ¿Cuál es su perímetro?",
    hint: "El perímetro suma sus cuatro lados.", answer: "26 cm", choices: ["13 cm", "26 cm", "40 cm", "80 cm"],
    wrongFeedback: "Suma dos largos y dos anchos: 8 + 5 + 8 + 5.", success: "8 + 5 + 8 + 5 = 26 cm.",
    visual: { type: "rectangle-measure", width: 8, height: 5, labels: ["8 cm", "5 cm"], focus: "perimeter" },
    steps: [step("Paso 1 · identifica", "El perímetro es el borde", "cuatro lados", "No necesitamos cubrir la superficie interior."), step("Paso 2 · agrupa", "Hay dos largos y dos anchos", "2 × 8 + 2 × 5", "Los lados opuestos del rectángulo son iguales."), step("Paso 3 · suma", "El contorno mide 26 cm", "16 + 10 = 26 cm", "La unidad permanece lineal." )],
  }),
  question({
    id: "GM02-N1-02", skillId: "GM02", family: "perimeter", level: 1,
    title: "El borde de un cuadrado", prompt: "Un cuadrado tiene lados de 7 m. ¿Cuánto mide su perímetro?",
    hint: "Sus cuatro lados tienen la misma longitud.", answer: "28 m", choices: ["14 m", "28 m", "49 m", "343 m"],
    wrongFeedback: "Para el perímetro multiplica la medida de un lado por cuatro.", success: "4 × 7 m = 28 m.",
    visual: { type: "rectangle-measure", width: 7, height: 7, labels: ["7 m", "7 m"], focus: "perimeter", square: true },
    steps: [step("Paso 1 · usa la igualdad", "Los cuatro lados miden 7 m", "7 + 7 + 7 + 7", "Un cuadrado tiene todos sus lados iguales."), step("Paso 2 · simplifica", "Multiplica por cuatro", "4 × 7 m", "La multiplicación reúne las cuatro longitudes."), step("Paso 3 · calcula", "El perímetro es 28 m", "4 × 7 = 28 m", "No usamos 7 × 7 porque eso calcularía el área." )],
  }),
  question({
    id: "GM02-N2-03", skillId: "GM02", family: "perimeter", level: 2,
    title: "Una figura irregular", prompt: "¿Cuál es el perímetro de la figura con lados 4, 6, 3, 5 y 7 cm?",
    hint: "Recorre una sola vez todo el contorno.", answer: "25 cm", choices: ["18 cm", "21 cm", "25 cm", "420 cm"],
    wrongFeedback: "El perímetro de un polígono irregular se obtiene sumando todos los lados: 4 + 6 + 3 + 5 + 7.", success: "La suma de los cinco lados es 25 cm.",
    visual: { type: "polygon-perimeter", points: [[0,0],[4,0],[5,2],[3,4],[-1,3]], labels: ["4 cm","3 cm","5 cm","7 cm","6 cm"] },
    steps: [step("Paso 1 · sigue el borde", "Incluye los cinco lados", "4, 6, 3, 5 y 7", "Ningún lado del contorno puede quedar fuera."), step("Paso 2 · suma por partes", "Agrupa para evitar errores", "(4 + 6) + (3 + 5 + 7)", "Los grupos suman 10 y 15."), step("Paso 3 · totaliza", "El perímetro es 25 cm", "10 + 15 = 25 cm", "No multiplicamos porque los lados son diferentes." )],
  }),
  question({
    id: "GM02-N2-04", skillId: "GM02", family: "perimeter", level: 2,
    title: "Un lado desconocido", prompt: "Un rectángulo tiene perímetro de 30 cm y ancho de 5 cm. ¿Cuánto mide su largo?",
    hint: "La mitad del perímetro contiene un largo y un ancho.", answer: "10 cm", choices: ["5 cm", "10 cm", "15 cm", "20 cm"],
    wrongFeedback: "Divide 30 cm entre 2 para obtener largo + ancho; luego resta los 5 cm del ancho.", success: "30 ÷ 2 − 5 = 10 cm.",
    visual: { type: "rectangle-measure", width: 10, height: 5, labels: ["? cm", "5 cm"], total: "P = 30 cm", focus: "perimeter" },
    steps: [step("Paso 1 · reduce el contorno", "Toma la mitad del perímetro", "30 ÷ 2 = 15 cm", "Esa mitad contiene un largo y un ancho."), step("Paso 2 · quita el ancho", "Resta los 5 cm conocidos", "15 − 5 = 10 cm", "Lo que queda corresponde al largo."), step("Paso 3 · comprueba", "Dos largos y dos anchos suman 30", "10 + 5 + 10 + 5 = 30", "El largo mide 10 cm." )],
  }),
  question({
    id: "GM02-N1-05", skillId: "GM02", family: "basic-area", level: 1,
    title: "Cubrir un rectángulo", prompt: "¿Cuál es el área de un rectángulo de 9 cm por 4 cm?",
    hint: "Multiplica cuántas unidades hay a lo largo y a lo ancho.", answer: "36 cm²", choices: ["13 cm²", "26 cm²", "36 cm²", "72 cm²"],
    wrongFeedback: "El área del rectángulo se calcula con largo × ancho: 9 × 4.", success: "9 × 4 = 36 centímetros cuadrados.",
    visual: { type: "rectangle-measure", width: 9, height: 4, labels: ["9 cm", "4 cm"], focus: "area", grid: true },
    steps: [step("Paso 1 · interpreta", "El área cubre la superficie", "filas × columnas", "Imaginamos cuadrados de 1 cm por lado."), step("Paso 2 · multiplica", "Hay 9 por 4 cuadrados", "9 × 4", "Cada fila contiene nueve y hay cuatro filas."), step("Paso 3 · expresa", "El área es 36 cm²", "9 × 4 = 36 cm²", "Usamos unidades cuadradas porque cubrimos una superficie." )],
  }),
  question({
    id: "GM02-N1-06", skillId: "GM02", family: "basic-area", level: 1,
    title: "Área de un cuadrado", prompt: "Un cuadrado tiene lado de 6 m. ¿Cuál es su área?",
    hint: "Multiplica el lado por sí mismo.", answer: "36 m²", choices: ["12 m²", "24 m²", "36 m²", "216 m²"],
    wrongFeedback: "El área utiliza dos dimensiones: 6 m × 6 m.", success: "6 × 6 = 36 metros cuadrados.",
    visual: { type: "rectangle-measure", width: 6, height: 6, labels: ["6 m", "6 m"], focus: "area", square: true, grid: true },
    steps: [step("Paso 1 · reconoce", "Largo y ancho son iguales", "lado = 6 m", "En un cuadrado ambas dimensiones tienen la misma medida."), step("Paso 2 · multiplica", "Lado por lado", "6 m × 6 m", "No sumamos los lados porque buscamos superficie."), step("Paso 3 · calcula", "El área es 36 m²", "6² = 36 m²", "El exponente 2 recuerda que usamos dos dimensiones." )],
  }),
  question({
    id: "GM02-N2-07", skillId: "GM02", family: "basic-area", level: 2,
    title: "Área de un triángulo", prompt: "Un triángulo tiene base de 10 cm y altura de 6 cm. ¿Cuál es su área?",
    hint: "Un triángulo ocupa la mitad del rectángulo con la misma base y altura.", answer: "30 cm²", choices: ["16 cm²", "30 cm²", "60 cm²", "120 cm²"],
    wrongFeedback: "Multiplica base por altura y divide entre 2: (10 × 6) ÷ 2.", success: "(10 × 6) ÷ 2 = 30 cm².",
    visual: { type: "triangle-measure", shape: "triangle", base: 10, height: 6, labels: ["10 cm", "6 cm"] },
    steps: [step("Paso 1 · forma el rectángulo", "Base por altura da 60", "10 × 6 = 60 cm²", "Ese sería el área de un rectángulo completo."), step("Paso 2 · toma la mitad", "El triángulo ocupa la mitad", "60 ÷ 2", "La diagonal divide el rectángulo en dos triángulos iguales."), step("Paso 3 · calcula", "El área es 30 cm²", "(10 × 6) ÷ 2 = 30", "La altura debe ser perpendicular a la base." )],
  }),
  question({
    id: "GM02-N2-08", skillId: "GM02", family: "basic-area", level: 2,
    title: "Área de un paralelogramo", prompt: "La base de un paralelogramo mide 8 m y su altura perpendicular 5 m. ¿Cuál es su área?",
    hint: "La inclinación del lado no sustituye a la altura.", answer: "40 m²", choices: ["13 m²", "20 m²", "40 m²", "80 m²"],
    wrongFeedback: "Usa base × altura perpendicular: 8 × 5. No necesitas la longitud inclinada.", success: "8 × 5 = 40 metros cuadrados.",
    visual: { type: "triangle-measure", shape: "parallelogram", base: 8, height: 5, labels: ["8 m", "5 m"] },
    steps: [step("Paso 1 · elige medidas", "Usa base y altura perpendicular", "b = 8 m; h = 5 m", "La altura forma 90° con la base."), step("Paso 2 · reorganiza", "El paralelogramo equivale a un rectángulo", "área = b × h", "Mover el triángulo lateral no cambia la superficie."), step("Paso 3 · multiplica", "El área es 40 m²", "8 × 5 = 40 m²", "La inclinación no cambia esta fórmula." )],
  }),
  question({
    id: "GM02-N2-09", skillId: "GM02", family: "composite-area", level: 2,
    title: "Una figura en forma de L", prompt: "Un rectángulo de 8 × 6 cm pierde una esquina de 3 × 2 cm. ¿Qué área queda?",
    hint: "Calcula el rectángulo completo y resta el recorte.", answer: "42 cm²", choices: ["36 cm²", "42 cm²", "48 cm²", "54 cm²"],
    wrongFeedback: "El área completa es 48 cm² y el recorte ocupa 6 cm²: resta 48 − 6.", success: "48 − 6 = 42 cm².",
    visual: { type: "composite-shape", kind: "cutout", outer: [8,6], inner: [3,2], labels: ["8 cm","6 cm","3 cm","2 cm"] },
    steps: [step("Paso 1 · completa", "Área del rectángulo exterior", "8 × 6 = 48 cm²", "Imaginamos primero la esquina todavía presente."), step("Paso 2 · mide el recorte", "La esquina ocupa 6 cm²", "3 × 2 = 6 cm²", "Esa superficie no pertenece a la figura."), step("Paso 3 · resta", "Quedan 42 cm²", "48 − 6 = 42 cm²", "Descomponer evita sumar lados como si fueran áreas." )],
  }),
  question({
    id: "GM02-N2-10", skillId: "GM02", family: "composite-area", level: 2,
    title: "Dos rectángulos unidos", prompt: "Una figura está formada por rectángulos de 5 × 4 cm y 3 × 2 cm sin superponerse. ¿Cuál es su área?",
    hint: "Calcula cada área y luego súmalas.", answer: "26 cm²", choices: ["14 cm²", "20 cm²", "26 cm²", "30 cm²"],
    wrongFeedback: "Las áreas son 20 cm² y 6 cm². Como no se superponen, se suman.", success: "20 + 6 = 26 cm².",
    visual: { type: "composite-shape", kind: "joined", rectangles: [[5,4],[3,2]], labels: ["5 × 4 cm","3 × 2 cm"] },
    steps: [step("Paso 1 · primera parte", "Área del rectángulo grande", "5 × 4 = 20 cm²", "Calculamos solo la primera región."), step("Paso 2 · segunda parte", "Área del rectángulo pequeño", "3 × 2 = 6 cm²", "No hay superposición entre ambas regiones."), step("Paso 3 · reúne", "El área total es 26 cm²", "20 + 6 = 26 cm²", "Las áreas sí pueden sumarse porque usan la misma unidad cuadrada." )],
  }),
  question({
    id: "GM02-N3-11", skillId: "GM02", family: "composite-area", level: 3,
    title: "Un marco rectangular", prompt: "Un marco mide 10 × 8 cm por fuera y tiene un espacio interior de 6 × 4 cm. ¿Cuál es el área del marco?",
    hint: "Resta el espacio vacío al rectángulo exterior.", answer: "56 cm²", choices: ["24 cm²", "48 cm²", "56 cm²", "80 cm²"],
    wrongFeedback: "El exterior ocupa 80 cm² y el hueco 24 cm². El material del marco es la diferencia.", success: "80 − 24 = 56 cm².",
    visual: { type: "composite-shape", kind: "frame", outer: [10,8], inner: [6,4], labels: ["10 × 8 cm","6 × 4 cm"] },
    steps: [step("Paso 1 · área exterior", "Calcula todo el rectángulo", "10 × 8 = 80 cm²", "Esto incluye temporalmente el espacio vacío."), step("Paso 2 · área interior", "Calcula el hueco", "6 × 4 = 24 cm²", "El interior no forma parte del marco."), step("Paso 3 · diferencia", "El marco ocupa 56 cm²", "80 − 24 = 56 cm²", "La resta aísla únicamente el material." )],
  }),
  question({
    id: "GM02-N3-12", skillId: "GM02", family: "composite-area", level: 3,
    title: "Rectángulo con techo triangular", prompt: "Una figura combina un rectángulo de 12 × 7 m y un triángulo de base 4 m y altura 3 m. ¿Cuál es el área total?",
    hint: "El triángulo utiliza la mitad de base por altura.", answer: "90 m²", choices: ["84 m²", "87 m²", "90 m²", "96 m²"],
    wrongFeedback: "El rectángulo ocupa 84 m² y el triángulo 6 m²: (4 × 3) ÷ 2.", success: "84 + 6 = 90 m².",
    visual: { type: "composite-shape", kind: "rect-triangle", rectangle: [12,7], triangle: [4,3], labels: ["12 × 7 m","b = 4 m","h = 3 m"] },
    steps: [step("Paso 1 · rectángulo", "Calcula la parte inferior", "12 × 7 = 84 m²", "Esta región usa largo por ancho."), step("Paso 2 · triángulo", "Calcula la parte superior", "(4 × 3) ÷ 2 = 6 m²", "Dividimos entre dos porque es triangular."), step("Paso 3 · suma", "El total es 90 m²", "84 + 6 = 90 m²", "Las dos regiones no se superponen." )],
  }),
  question({
    id: "GM02-N2-13", skillId: "GM02", family: "inverse-measure", level: 2,
    title: "Encontrar el largo", prompt: "Un rectángulo tiene área de 54 cm² y ancho de 6 cm. ¿Cuánto mide su largo?",
    hint: "Deshaz la multiplicación dividiendo el área entre el ancho.", answer: "9 cm", choices: ["8 cm", "9 cm", "48 cm", "324 cm"],
    wrongFeedback: "Como largo × 6 = 54, divide 54 entre 6.", success: "54 ÷ 6 = 9 cm.",
    visual: { type: "rectangle-measure", width: 9, height: 6, labels: ["? cm","6 cm"], total: "A = 54 cm²", focus: "area" },
    steps: [step("Paso 1 · plantea", "Área es largo por ancho", "largo × 6 = 54", "Conocemos el producto y uno de sus factores."), step("Paso 2 · invierte", "Divide entre el ancho", "54 ÷ 6", "La división deshace la multiplicación por 6."), step("Paso 3 · responde", "El largo mide 9 cm", "9 × 6 = 54 cm²", "La comprobación recupera el área dada." )],
  }),
  question({
    id: "GM02-N2-14", skillId: "GM02", family: "inverse-measure", level: 2,
    title: "Altura de un triángulo", prompt: "Un triángulo tiene área de 24 cm² y base de 8 cm. ¿Cuál es su altura?",
    hint: "Duplica primero el área porque la fórmula divide entre dos.", answer: "6 cm", choices: ["3 cm", "6 cm", "8 cm", "16 cm"],
    wrongFeedback: "Usa 24 = (8 × altura) ÷ 2. Duplica 24 y divide entre 8.", success: "48 ÷ 8 = 6 cm de altura.",
    visual: { type: "triangle-measure", shape: "triangle", base: 8, height: 6, labels: ["8 cm","? cm"], total: "A = 24 cm²" },
    steps: [step("Paso 1 · escribe la fórmula", "Área es base por altura entre dos", "24 = (8 × h) ÷ 2", "La altura es la única medida desconocida."), step("Paso 2 · elimina la mitad", "Duplica ambos lados", "48 = 8 × h", "Multiplicar por dos deshace la división."), step("Paso 3 · divide", "La altura es 6 cm", "h = 48 ÷ 8 = 6", "Con base 8 y altura 6, el área vuelve a ser 24 cm²." )],
  }),
  question({
    id: "GM02-N2-15", skillId: "GM02", family: "inverse-measure", level: 2,
    title: "Lado desde el área", prompt: "Un cuadrado tiene área de 81 m². ¿Cuánto mide cada lado?",
    hint: "Busca el número que multiplicado por sí mismo produce 81.", answer: "9 m", choices: ["8 m", "9 m", "20,25 m", "40,5 m"],
    wrongFeedback: "El lado del cuadrado cumple lado × lado = 81. La raíz cuadrada de 81 es 9.", success: "9 m × 9 m = 81 m².",
    visual: { type: "rectangle-measure", width: 9, height: 9, labels: ["? m","? m"], total: "A = 81 m²", focus: "area", square: true },
    steps: [step("Paso 1 · usa la forma", "Los lados son iguales", "lado² = 81", "No tenemos dos medidas diferentes."), step("Paso 2 · busca el factor", "¿Qué número por sí mismo da 81?", "9 × 9 = 81", "Esta operación es la raíz cuadrada."), step("Paso 3 · responde", "Cada lado mide 9 m", "√81 = 9 m", "La unidad vuelve a ser lineal al encontrar el lado." )],
  }),
  question({
    id: "GM02-N3-16", skillId: "GM02", family: "inverse-measure", level: 3,
    title: "Ancho y perímetro desde el área", prompt: "Un rectángulo tiene área de 96 cm² y largo de 12 cm. ¿Cuál es su perímetro?",
    hint: "Primero encuentra el ancho y después suma el contorno.", answer: "40 cm", choices: ["20 cm", "32 cm", "40 cm", "108 cm"],
    wrongFeedback: "El ancho es 96 ÷ 12 = 8 cm. Luego calcula 2 × (12 + 8).",
    success: "El ancho mide 8 cm y el perímetro es 40 cm.",
    visual: { type: "rectangle-measure", width: 12, height: 8, labels: ["12 cm","? cm"], total: "A = 96 cm²", focus: "both" },
    steps: [step("Paso 1 · encuentra el ancho", "Divide área entre largo", "96 ÷ 12 = 8 cm", "Ahora conocemos las dos dimensiones."), step("Paso 2 · cambia de concepto", "El perímetro recorre el borde", "2 × (12 + 8)", "No debemos responder con el área dada."), step("Paso 3 · calcula", "El perímetro es 40 cm", "2 × 20 = 40 cm", "La respuesta usa centímetros lineales." )],
  }),
  question({
    id: "GM02-N1-17", skillId: "GM02", family: "volume", level: 1,
    title: "Capacidad de un prisma", prompt: "Una caja mide 4 cm × 3 cm × 5 cm. ¿Cuál es su volumen?",
    hint: "Multiplica largo, ancho y altura.", answer: "60 cm³", choices: ["12 cm³", "20 cm³", "47 cm³", "60 cm³"],
    wrongFeedback: "El volumen utiliza las tres dimensiones: 4 × 3 × 5.", success: "4 × 3 × 5 = 60 cm³.",
    visual: { type: "prism-volume", dimensions: [4,3,5], labels: ["4 cm","3 cm","5 cm"] },
    steps: [step("Paso 1 · cuenta dimensiones", "La caja tiene largo, ancho y alto", "4, 3 y 5 cm", "El volumen ocupa espacio tridimensional."), step("Paso 2 · multiplica la base", "La base tiene 12 cm²", "4 × 3 = 12 cm²", "Cada capa contiene doce cubos unitarios."), step("Paso 3 · apila capas", "Cinco capas producen 60 cm³", "12 × 5 = 60 cm³", "La unidad cúbica representa tres dimensiones." )],
  }),
  question({
    id: "GM02-N1-18", skillId: "GM02", family: "volume", level: 1,
    title: "Volumen de un cubo", prompt: "Un cubo tiene aristas de 4 m. ¿Cuál es su volumen?",
    hint: "Las tres dimensiones del cubo son iguales.", answer: "64 m³", choices: ["12 m³", "16 m³", "64 m³", "256 m³"],
    wrongFeedback: "Multiplica 4 × 4 × 4; el volumen requiere tres factores.", success: "4³ = 64 metros cúbicos.",
    visual: { type: "prism-volume", dimensions: [4,4,4], labels: ["4 m","4 m","4 m"], cube: true },
    steps: [step("Paso 1 · reconoce", "Todas las aristas miden 4 m", "largo = ancho = alto", "Un cubo es un prisma con tres dimensiones iguales."), step("Paso 2 · eleva al cubo", "Multiplica tres veces", "4 × 4 × 4", "El exponente 3 representa las tres dimensiones."), step("Paso 3 · calcula", "El volumen es 64 m³", "4³ = 64 m³", "No confundas 4², que solo mediría una cara." )],
  }),
  question({
    id: "GM02-N3-19", skillId: "GM02", family: "volume", level: 3,
    title: "Altura desconocida", prompt: "Una caja tiene volumen de 120 cm³ y base de 5 cm × 4 cm. ¿Cuál es su altura?",
    hint: "Calcula primero el área de la base.", answer: "6 cm", choices: ["5 cm", "6 cm", "20 cm", "24 cm"],
    wrongFeedback: "La base ocupa 5 × 4 = 20 cm². Divide el volumen 120 cm³ entre 20 cm².", success: "120 ÷ 20 = 6 cm de altura.",
    visual: { type: "prism-volume", dimensions: [5,4,6], labels: ["5 cm","4 cm","? cm"], total: "V = 120 cm³" },
    steps: [step("Paso 1 · base", "Calcula el área inferior", "5 × 4 = 20 cm²", "Cada capa de la caja contiene veinte centímetros cuadrados."), step("Paso 2 · relaciona", "Volumen es base por altura", "120 = 20 × h", "Conocemos el total y el tamaño de cada capa."), step("Paso 3 · divide", "La altura mide 6 cm", "h = 120 ÷ 20 = 6", "Seis capas de 20 cm³ completan 120 cm³." )],
  }),
  question({
    id: "GM02-N3-20", skillId: "GM02", family: "volume", level: 3,
    title: "Dos prismas apilados", prompt: "Dos prismas de base 3 cm × 2 cm tienen alturas de 4 cm y 2 cm. ¿Cuál es el volumen total?",
    hint: "Puedes sumar las alturas porque comparten la misma base.", answer: "36 cm³", choices: ["24 cm³", "30 cm³", "36 cm³", "48 cm³"],
    wrongFeedback: "La base mide 6 cm² y la altura total es 6 cm. Multiplica 6 × 6.", success: "3 × 2 × (4 + 2) = 36 cm³.",
    visual: { type: "prism-volume", dimensions: [3,2,6], labels: ["3 cm","2 cm","4 cm + 2 cm"], stacked: true },
    steps: [step("Paso 1 · base común", "Ambos tienen base de 6 cm²", "3 × 2 = 6 cm²", "La misma base permite pensar en una sola columna."), step("Paso 2 · suma alturas", "La altura total es 6 cm", "4 + 2 = 6 cm", "Apilar no crea superposición de volumen."), step("Paso 3 · calcula", "El total es 36 cm³", "6 cm² × 6 cm = 36 cm³", "También obtendríamos 24 + 12 = 36 cm³." )],
  }),
  question({
    id: "GM02-N3-21", skillId: "GM02", family: "measure-combined", level: 3,
    title: "Cerca con una entrada", prompt: "Un jardín de 10 m × 6 m tendrá una cerca, excepto en una entrada de 2 m. ¿Cuántos metros de cerca se necesitan?",
    hint: "Calcula todo el perímetro y después descuenta la entrada.", answer: "30 m", choices: ["28 m", "30 m", "32 m", "58 m"],
    wrongFeedback: "El perímetro completo es 2 × (10 + 6) = 32 m. Resta los 2 m sin cerca.", success: "32 m − 2 m = 30 m de cerca.",
    visual: { type: "rectangle-measure", width: 10, height: 6, labels: ["10 m","6 m"], focus: "perimeter", gap: "2 m" },
    steps: [step("Paso 1 · contorno completo", "Calcula el perímetro", "2 × (10 + 6) = 32 m", "Esto supone inicialmente una cerca sin aberturas."), step("Paso 2 · representa la entrada", "Dos metros quedan abiertos", "32 m − 2 m", "La entrada pertenece al borde, pero no necesita cerca."), step("Paso 3 · concluye", "Se requieren 30 m", "32 − 2 = 30 m", "La superficie del jardín no interviene." )],
  }),
  question({
    id: "GM02-N2-22", skillId: "GM02", family: "measure-combined", level: 2,
    title: "Baldosas para un piso", prompt: "Un piso rectangular mide 12 m por 8 m. Si cada baldosa cubre 1 m², ¿cuántas se necesitan?",
    hint: "Cada baldosa corresponde a una unidad cuadrada.", answer: "96 baldosas", choices: ["20 baldosas", "40 baldosas", "96 baldosas", "192 baldosas"],
    wrongFeedback: "Calcula el área del piso: 12 m × 8 m. Cada metro cuadrado requiere una baldosa.", success: "El piso tiene 96 m² y necesita 96 baldosas.",
    visual: { type: "rectangle-measure", width: 12, height: 8, labels: ["12 m","8 m"], focus: "area", grid: true },
    steps: [step("Paso 1 · identifica", "Las baldosas cubren superficie", "necesitamos el área", "El perímetro no indica cuántas caben dentro."), step("Paso 2 · calcula el piso", "Multiplica largo por ancho", "12 × 8 = 96 m²", "Hay 96 regiones de un metro cuadrado."), step("Paso 3 · traduce", "Una baldosa por cada m²", "96 m² → 96 baldosas", "No añadimos desperdicio porque el problema no lo solicita." )],
  }),
  question({
    id: "GM02-N3-23", skillId: "GM02", family: "measure-combined", level: 3,
    title: "Una caja a la mitad", prompt: "Una caja de 6 cm × 5 cm × 4 cm está llena hasta la mitad. ¿Qué volumen ocupa el contenido?",
    hint: "Calcula primero la capacidad completa.", answer: "60 cm³", choices: ["30 cm³", "60 cm³", "120 cm³", "240 cm³"],
    wrongFeedback: "La caja completa tiene 6 × 5 × 4 = 120 cm³. Toma después la mitad.", success: "La mitad de 120 cm³ es 60 cm³.",
    visual: { type: "prism-volume", dimensions: [6,5,4], labels: ["6 cm","5 cm","4 cm"], halfFull: true },
    steps: [step("Paso 1 · volumen total", "Multiplica las tres dimensiones", "6 × 5 × 4 = 120 cm³", "Ese es el espacio interior completo."), step("Paso 2 · interpreta la mitad", "Solo se ocupa el 50 %", "120 ÷ 2", "La forma de la caja no cambia, solo la cantidad llena."), step("Paso 3 · calcula", "El contenido ocupa 60 cm³", "120 ÷ 2 = 60 cm³", "No confundas volumen ocupado con capacidad total." )],
  }),
  question({
    id: "GM02-N3-24", skillId: "GM02", family: "measure-combined", level: 3,
    title: "Mismo perímetro, distinta forma", prompt: "Un rectángulo de 8 × 4 cm y un cuadrado de lado 6 cm: ¿cómo se comparan sus perímetros?",
    hint: "Calcula por separado el contorno de cada figura.", answer: "Son iguales", choices: ["El rectángulo es mayor", "El cuadrado es mayor", "Son iguales", "No se pueden comparar"],
    wrongFeedback: "El rectángulo mide 2 × (8 + 4) y el cuadrado 4 × 6. Compara los dos resultados.", success: "Ambos perímetros miden 24 cm, aunque sus áreas son distintas.",
    visual: { type: "shape-comparison", rectangle: [8,4], square: 6, labels: ["8 × 4 cm","lado 6 cm"] },
    steps: [step("Paso 1 · rectángulo", "Suma sus cuatro lados", "2 × (8 + 4) = 24 cm", "El rectángulo tiene dos lados de cada medida."), step("Paso 2 · cuadrado", "Multiplica el lado por cuatro", "4 × 6 = 24 cm", "Sus cuatro lados son iguales."), step("Paso 3 · compara", "Los perímetros coinciden", "24 cm = 24 cm", "Tener la misma frontera no significa tener la misma área." )],
  }),
];

const normalizedAngles = ANGLE_QUESTIONS.map((item) => ({ ...item, skillId: "GM03" }));
const rawQuestions = [...GM01_QUESTIONS, ...GM02_QUESTIONS, ...normalizedAngles];

export const GEOMETRY_MVP_QUESTIONS = rawQuestions.map((item, index) => ({
  ...item,
  number: index + 1,
  skillLabel: GEOMETRY_SKILLS.find((skill) => skill.id === item.skillId)?.label,
  familyLabel: GEOMETRY_MVP_FAMILIES.find((family) => family.id === item.family)?.label,
}));
