const degrees = (value) => `${value}°`;

function numericOptions(answer, values, errors) {
  return values.map((value) => {
    const label = degrees(value);
    return {
      value: label,
      feedback: value === answer ? null : errors[label],
    };
  });
}

function classifyOptions(answer, errors) {
  return ["Agudo", "Recto", "Obtuso", "Llano"].map((value) => ({
    value,
    feedback: value === answer ? null : errors[value],
  }));
}

export const GEOMETRY_FAMILIES = [
  { id: "classify", label: "Reconocer ángulos", short: "Reconocer" },
  { id: "triangle-sum", label: "Suma del triángulo", short: "Triángulos" },
  { id: "angle-pairs", label: "Pares de ángulos", short: "Pares" },
  { id: "intersections", label: "Rectas que se cruzan", short: "Rectas" },
  { id: "special-triangles", label: "Triángulos especiales", short: "Especiales" },
  { id: "combined", label: "Razonamiento combinado", short: "Razonamiento" },
];

const questions = [
  {
    id: "GM03-N1-01",
    family: "classify",
    level: 1,
    title: "Una abertura pequeña",
    prompt: "¿Cómo se clasifica el ángulo dibujado?",
    hint: "Compáralo mentalmente con una esquina de 90°.",
    answer: "Agudo",
    options: classifyOptions("Agudo", {
      Recto: "Un ángulo recto mide exactamente 90°; esta abertura es menor.",
      Obtuso: "Un ángulo obtuso es mayor que 90°; aquí la abertura todavía no llega a una esquina.",
      Llano: "Un ángulo llano forma una línea de 180°; estos rayos no están alineados.",
    }),
    success: "Es agudo porque mide menos de 90°.",
    visual: { type: "single-angle", degrees: 35 },
    steps: [
      { eyebrow: "Paso 1 · encuentra la referencia", title: "Una esquina mide 90°", equation: "ángulo recto = 90°", text: "Usamos la esquina como referencia visual para comparar la abertura." },
      { eyebrow: "Paso 2 · compara", title: "La abertura es menor", equation: "35° < 90°", text: "El segundo rayo aparece antes de completar una esquina." },
      { eyebrow: "Paso 3 · clasifica", title: "Los menores de 90° son agudos", equation: "35° → agudo", text: "No hace falta juzgar por intuición: la medida confirma la clasificación." },
    ],
  },
  {
    id: "GM03-N1-02",
    family: "classify",
    level: 1,
    title: "La esquina exacta",
    prompt: "¿Qué tipo de ángulo señalan los dos rayos?",
    hint: "Busca la pequeña marca cuadrada en el vértice.",
    answer: "Recto",
    options: classifyOptions("Recto", {
      Agudo: "Los agudos son menores de 90°; la marca cuadrada indica exactamente 90°.",
      Obtuso: "Los obtusos superan 90°; esta abertura no pasa de la esquina.",
      Llano: "Los llanos miden 180° y forman una línea; aquí los rayos son perpendiculares.",
    }),
    success: "La marca cuadrada confirma que mide 90°: es recto.",
    visual: { type: "single-angle", degrees: 90, rightMark: true },
    steps: [
      { eyebrow: "Paso 1 · observa la marca", title: "El cuadrado tiene un significado", equation: "□ = 90°", text: "En geometría, una marca cuadrada en el vértice indica un ángulo de 90°." },
      { eyebrow: "Paso 2 · reconoce la medida", title: "La abertura es una esquina", equation: "90°", text: "Los rayos son perpendiculares: se encuentran formando una esquina exacta." },
      { eyebrow: "Paso 3 · clasifica", title: "Noventa grados es un ángulo recto", equation: "90° → recto", text: "La clasificación depende de la medida, no de cómo esté girada la figura." },
    ],
  },
  {
    id: "GM03-N1-03",
    family: "classify",
    level: 1,
    title: "Más abierto que una esquina",
    prompt: "¿Cómo se clasifica este ángulo?",
    hint: "Compara su abertura con 90° y con una línea de 180°.",
    answer: "Obtuso",
    options: classifyOptions("Obtuso", {
      Agudo: "Los agudos son menores de 90°; este ángulo abre más que una esquina.",
      Recto: "Solo sería recto si midiera exactamente 90°.",
      Llano: "Todavía no forma una línea de 180°, por eso no es llano.",
    }),
    success: "Mide más de 90° y menos de 180°: es obtuso.",
    visual: { type: "single-angle", degrees: 128 },
    steps: [
      { eyebrow: "Paso 1 · fija los límites", title: "Compara con 90° y 180°", equation: "90° < ? < 180°", text: "Un obtuso queda entre una esquina y una línea recta." },
      { eyebrow: "Paso 2 · revela la medida", title: "La abertura mide 128°", equation: "90° < 128° < 180°", text: "Supera los 90°, pero aún no llega a los 180°." },
      { eyebrow: "Paso 3 · clasifica", title: "Está en el intervalo obtuso", equation: "128° → obtuso", text: "La comparación con los dos límites evita clasificar por apariencia." },
    ],
  },
  {
    id: "GM03-N1-04",
    family: "classify",
    level: 1,
    title: "Dos rayos alineados",
    prompt: "¿Qué tipo de ángulo forma esta línea?",
    hint: "Los rayos apuntan en direcciones completamente opuestas.",
    answer: "Llano",
    options: classifyOptions("Llano", {
      Agudo: "Un agudo es menor de 90° y no puede formar una línea.",
      Recto: "Un recto forma una esquina de 90°, no una línea completa.",
      Obtuso: "Un obtuso es menor de 180°; aquí los rayos están totalmente alineados.",
    }),
    success: "Los rayos opuestos forman 180°: es un ángulo llano.",
    visual: { type: "single-angle", degrees: 180 },
    steps: [
      { eyebrow: "Paso 1 · mira las direcciones", title: "Los rayos son opuestos", equation: "← O →", text: "Ambos parten del mismo vértice y forman una línea completa." },
      { eyebrow: "Paso 2 · asocia la medida", title: "Media vuelta son 180°", equation: "media vuelta = 180°", text: "Pasar de un rayo al otro equivale a girar media vuelta." },
      { eyebrow: "Paso 3 · clasifica", title: "Ciento ochenta grados es llano", equation: "180° → llano", text: "Un ángulo llano siempre se reconoce por sus rayos opuestos." },
    ],
  },
  {
    id: "GM03-N2-05",
    family: "triangle-sum",
    level: 2,
    title: "Dos ángulos conocidos",
    prompt: "¿Cuánto mide el ángulo faltante?",
    hint: "Los tres ángulos interiores de un triángulo suman 180°.",
    answer: "65°",
    options: numericOptions(65, [55, 60, 65, 75], {
      "55°": "45° + 70° es 115°, no 125°. Revisa esa suma antes de restar.",
      "60°": "Sesenta completaría 175°, así que todavía faltarían 5°.",
      "75°": "Con 75° la suma sería 190°, mayor que los 180° del triángulo.",
    }),
    success: "45° + 70° + 65° completa exactamente 180°.",
    visual: { type: "triangle", angles: [45, 70, 65], missing: 2 },
    steps: [
      { eyebrow: "Paso 1 · usa los datos", title: "Suma los ángulos conocidos", equation: "45° + 70° = 115°", text: "Primero reunimos las dos medidas visibles." },
      { eyebrow: "Paso 2 · aplica la regla", title: "Todo triángulo suma 180°", equation: "115° + ? = 180°", text: "La forma puede cambiar, pero esta suma siempre se conserva." },
      { eyebrow: "Paso 3 · encuentra el faltante", title: "Resta lo que ya conoces", equation: "180° − 115° = 65°", text: "La comprobación es 45° + 70° + 65° = 180°." },
    ],
  },
  {
    id: "GM03-N2-06",
    family: "triangle-sum",
    level: 2,
    title: "Una suma equilibrada",
    prompt: "Encuentra la medida del ángulo C.",
    hint: "Suma primero 52° y 58°.",
    answer: "70°",
    options: numericOptions(70, [68, 70, 72, 110], {
      "68°": "Esa respuesta no completa 180°: 52° + 58° + 68° = 178°.",
      "72°": "Con 72° obtendrías 182°; el triángulo debe sumar exactamente 180°.",
      "110°": "110° es la suma de los dos datos conocidos, no el ángulo faltante.",
    }),
    success: "Los dos conocidos suman 110° y faltan 70° para llegar a 180°.",
    visual: { type: "triangle", angles: [52, 58, 70], missing: 2 },
    steps: [
      { eyebrow: "Paso 1 · reúne los datos", title: "Suma 52° y 58°", equation: "52° + 58° = 110°", text: "Esta suma representa la parte de los 180° que ya conocemos." },
      { eyebrow: "Paso 2 · plantea el total", title: "Incluye el ángulo C", equation: "110° + C = 180°", text: "Los tres interiores deben completar 180°." },
      { eyebrow: "Paso 3 · calcula", title: "Resta la parte conocida", equation: "C = 180° − 110° = 70°", text: "Comprobamos: 52° + 58° + 70° = 180°." },
    ],
  },
  {
    id: "GM03-N2-07",
    family: "triangle-sum",
    level: 2,
    title: "Dentro de un triángulo rectángulo",
    prompt: "¿Cuánto mide el ángulo A?",
    hint: "Uno de los ángulos ya ocupa 90°.",
    answer: "35°",
    options: numericOptions(35, [35, 45, 55, 90], {
      "45°": "Un triángulo rectángulo no siempre tiene dos ángulos de 45°; eso solo ocurre en uno isósceles.",
      "55°": "55° ya es otro ángulo visible; repetirlo llevaría la suma a 200°.",
      "90°": "Ya hay un ángulo recto. Dos ángulos de 90° no dejarían espacio para el tercero.",
    }),
    success: "90° + 55° dejan 35° para completar el triángulo.",
    visual: { type: "triangle", angles: [35, 90, 55], missing: 0, rightIndex: 1 },
    steps: [
      { eyebrow: "Paso 1 · reconoce el recto", title: "Un ángulo ya mide 90°", equation: "90° + 55° = 145°", text: "Sumamos el ángulo recto y el otro dato conocido." },
      { eyebrow: "Paso 2 · completa el triángulo", title: "El total sigue siendo 180°", equation: "145° + A = 180°", text: "Ser rectángulo no cambia la suma de sus ángulos interiores." },
      { eyebrow: "Paso 3 · resta", title: "Encuentra el ángulo A", equation: "A = 180° − 145° = 35°", text: "La suma final es 35° + 90° + 55° = 180°." },
    ],
  },
  {
    id: "GM03-N2-08",
    family: "triangle-sum",
    level: 2,
    title: "El ángulo del lado derecho",
    prompt: "¿Cuál es la medida del ángulo B?",
    hint: "La suma de 72° y 62° representa lo que ya conoces.",
    answer: "46°",
    options: numericOptions(46, [44, 46, 62, 72], {
      "44°": "Con 44° la suma quedaría en 178°; faltan 2°.",
      "62°": "62° es el ángulo C. Los ángulos del dibujo no son necesariamente iguales.",
      "72°": "72° es el ángulo A; repetirlo haría que el total fuera 206°.",
    }),
    success: "72° + 62° = 134° y 180° − 134° = 46°.",
    visual: { type: "triangle", angles: [72, 46, 62], missing: 1 },
    steps: [
      { eyebrow: "Paso 1 · suma", title: "Combina A y C", equation: "72° + 62° = 134°", text: "Esos son los dos ángulos que conocemos." },
      { eyebrow: "Paso 2 · usa la propiedad", title: "Los tres suman 180°", equation: "134° + B = 180°", text: "Ahora sabemos cuánto espacio angular queda para B." },
      { eyebrow: "Paso 3 · resuelve", title: "Resta 134°", equation: "B = 180° − 134° = 46°", text: "La comprobación 72° + 46° + 62° da 180°." },
    ],
  },
  {
    id: "GM03-N2-09",
    family: "angle-pairs",
    level: 2,
    title: "Completar una esquina",
    prompt: "¿Cuánto mide el ángulo faltante?",
    hint: "Los dos ángulos juntos forman 90°.",
    answer: "52°",
    options: numericOptions(52, [42, 48, 52, 142], {
      "42°": "38° + 42° suma 80°, por lo que no completa la esquina.",
      "48°": "38° + 48° da 86°; todavía faltarían 4°.",
      "142°": "Eso corresponde a restar de 180°, pero aquí el total marcado es 90°.",
    }),
    success: "38° y 52° son complementarios porque suman 90°.",
    visual: { type: "angle-pair", total: 90, known: 38, missing: 52 },
    steps: [
      { eyebrow: "Paso 1 · identifica el total", title: "La marca forma una esquina", equation: "total = 90°", text: "El cuadrado exterior indica que ambos ángulos completan un recto." },
      { eyebrow: "Paso 2 · plantea la suma", title: "Separa la esquina en dos partes", equation: "38° + ? = 90°", text: "El faltante es la parte necesaria para completar 90°." },
      { eyebrow: "Paso 3 · resta", title: "Calcula el complemento", equation: "90° − 38° = 52°", text: "Comprobación: 38° + 52° = 90°." },
    ],
  },
  {
    id: "GM03-N2-10",
    family: "angle-pairs",
    level: 2,
    title: "Otra parte de la esquina",
    prompt: "Encuentra el complemento de 27°.",
    hint: "Complementarios significa que suman 90°.",
    answer: "63°",
    options: numericOptions(63, [53, 63, 73, 153], {
      "53°": "27° + 53° suma 80°, no 90°.",
      "73°": "27° + 73° suma 100°, diez grados de más.",
      "153°": "153° es el suplemento hasta 180°, no el complemento hasta 90°.",
    }),
    success: "El complemento es 63° porque 27° + 63° = 90°.",
    visual: { type: "angle-pair", total: 90, known: 27, missing: 63 },
    steps: [
      { eyebrow: "Paso 1 · traduce la palabra", title: "Complementarios suman 90°", equation: "27° + ? = 90°", text: "La palabra complemento nos dice cuál debe ser el total." },
      { eyebrow: "Paso 2 · aísla lo desconocido", title: "Quita 27° del total", equation: "? = 90° − 27°", text: "Restamos la parte que ya está ocupada." },
      { eyebrow: "Paso 3 · comprueba", title: "El faltante mide 63°", equation: "27° + 63° = 90°", text: "La suma recupera exactamente la esquina completa." },
    ],
  },
  {
    id: "GM03-N2-11",
    family: "angle-pairs",
    level: 2,
    title: "Sobre una línea recta",
    prompt: "¿Cuánto mide el ángulo que falta?",
    hint: "Los dos ángulos adyacentes forman una línea de 180°.",
    answer: "62°",
    options: numericOptions(62, [52, 62, 72, 118], {
      "52°": "118° + 52° suma 170°; una línea completa necesita 180°.",
      "72°": "Con 72° la suma sería 190°, diez grados de más.",
      "118°": "Los ángulos adyacentes de una línea no tienen que ser iguales.",
    }),
    success: "118° + 62° forma el ángulo llano de 180°.",
    visual: { type: "angle-pair", total: 180, known: 118, missing: 62 },
    steps: [
      { eyebrow: "Paso 1 · reconoce la figura", title: "Una línea representa 180°", equation: "total = 180°", text: "Los rayos exteriores apuntan en direcciones opuestas." },
      { eyebrow: "Paso 2 · plantea", title: "Las dos partes completan la línea", equation: "118° + ? = 180°", text: "Estos ángulos son suplementarios." },
      { eyebrow: "Paso 3 · calcula", title: "Resta el ángulo conocido", equation: "180° − 118° = 62°", text: "La suma 118° + 62° confirma los 180°." },
    ],
  },
  {
    id: "GM03-N2-12",
    family: "angle-pairs",
    level: 2,
    title: "La parte grande de la línea",
    prompt: "Encuentra el suplemento de 47°.",
    hint: "Suplementarios significa que suman 180°.",
    answer: "133°",
    options: numericOptions(133, [43, 133, 137, 227], {
      "43°": "43° completaría 90°, pero aquí buscamos una línea de 180°.",
      "137°": "47° + 137° da 184°; revisa la resta desde 180°.",
      "227°": "Sumar 180° a 47° no encuentra la parte faltante de la línea.",
    }),
    success: "El suplemento de 47° es 133°.",
    visual: { type: "angle-pair", total: 180, known: 47, missing: 133 },
    steps: [
      { eyebrow: "Paso 1 · interpreta", title: "Suplemento significa 180°", equation: "47° + ? = 180°", text: "Buscamos la segunda parte de un ángulo llano." },
      { eyebrow: "Paso 2 · resta", title: "Separa la parte desconocida", equation: "? = 180° − 47°", text: "La operación correcta es quitar 47° del total." },
      { eyebrow: "Paso 3 · verifica", title: "El suplemento es 133°", equation: "47° + 133° = 180°", text: "La suma produce una línea completa." },
    ],
  },
  {
    id: "GM03-N2-13",
    family: "intersections",
    level: 2,
    title: "Ángulos enfrentados",
    prompt: "¿Cuánto mide el ángulo opuesto?",
    hint: "Los ángulos opuestos por el vértice tienen la misma medida.",
    answer: "68°",
    options: numericOptions(68, [22, 68, 112, 292], {
      "22°": "No necesitamos completar 90°; las rectas no están marcadas como perpendiculares.",
      "112°": "112° es el ángulo adyacente: 180° − 68°. El solicitado está enfrente.",
      "292°": "Restar de 360° reúne tres regiones, no el ángulo opuesto señalado.",
    }),
    success: "El ángulo opuesto mide lo mismo: 68°.",
    visual: { type: "intersection", known: 68, missing: 68, relation: "vertical" },
    steps: [
      { eyebrow: "Paso 1 · ubica las regiones", title: "Los ángulos están enfrentados", equation: "uno ↔ otro", text: "Comparten el vértice, pero no comparten un lado." },
      { eyebrow: "Paso 2 · usa la propiedad", title: "Los opuestos son iguales", equation: "ángulo opuesto = 68°", text: "Al cruzarse dos rectas, cada pareja enfrentada conserva su medida." },
      { eyebrow: "Paso 3 · concluye", title: "No hace falta restar", equation: "? = 68°", text: "El ángulo resaltado tiene la misma abertura que el conocido." },
    ],
  },
  {
    id: "GM03-N2-14",
    family: "intersections",
    level: 2,
    title: "El obtuso de enfrente",
    prompt: "Determina la medida del ángulo señalado.",
    hint: "Mira si comparte un lado con 112° o si está justo enfrente.",
    answer: "112°",
    options: numericOptions(112, [68, 90, 112, 248], {
      "68°": "68° corresponde a un ángulo adyacente, porque 180° − 112° = 68°.",
      "90°": "Las rectas se cruzan, pero no son perpendiculares; no todos los cruces forman 90°.",
      "248°": "360° − 112° abarca tres ángulos, no solo la región señalada.",
    }),
    success: "Está opuesto a 112°, por eso también mide 112°.",
    visual: { type: "intersection", known: 112, missing: 112, relation: "vertical" },
    steps: [
      { eyebrow: "Paso 1 · distingue", title: "Está al otro lado del vértice", equation: "112° ↔ ?", text: "No es el vecino del ángulo conocido, sino su opuesto." },
      { eyebrow: "Paso 2 · aplica", title: "Los opuestos por el vértice son congruentes", equation: "medidas iguales", text: "La intersección genera dos pares de ángulos iguales." },
      { eyebrow: "Paso 3 · responde", title: "Conserva los 112°", equation: "? = 112°", text: "Ambos son obtusos y tienen exactamente la misma abertura." },
    ],
  },
  {
    id: "GM03-N3-15",
    family: "intersections",
    level: 3,
    title: "El vecino del ángulo obtuso",
    prompt: "¿Cuánto mide el ángulo opuesto al vecino de 124°?",
    hint: "Primero encuentra el vecino que forma una línea; después mira su opuesto.",
    answer: "56°",
    options: numericOptions(56, [34, 56, 124, 236], {
      "34°": "124° + 34° suma 158°, así que no completa una línea.",
      "124°": "124° corresponde al opuesto del ángulo dado, no al opuesto de su vecino.",
      "236°": "Restar de 360° cubre más de una región; el par lineal suma 180°.",
    }),
    success: "El vecino mide 56° y su ángulo opuesto conserva esos 56°.",
    visual: { type: "intersection", known: 124, missing: 56, relation: "opposite-adjacent" },
    steps: [
      { eyebrow: "Paso 1 · resuelve el vecino", title: "El par lineal suma 180°", equation: "180° − 124° = 56°", text: "El ángulo vecino de 124° mide 56°." },
      { eyebrow: "Paso 2 · cambia de región", title: "Busca el opuesto de ese vecino", equation: "56° ↔ ?", text: "La pregunta no señala el vecino, sino el ángulo que está enfrente de él." },
      { eyebrow: "Paso 3 · conserva la medida", title: "Los opuestos son iguales", equation: "? = 56°", text: "Usamos primero el par lineal y después la propiedad de ángulos opuestos." },
    ],
  },
  {
    id: "GM03-N3-16",
    family: "intersections",
    level: 3,
    title: "El vecino grande",
    prompt: "Encuentra el ángulo opuesto al vecino de 37°.",
    hint: "Necesitas usar una suma de 180° y después la igualdad de los opuestos.",
    answer: "143°",
    options: numericOptions(143, [37, 53, 143, 323], {
      "37°": "37° corresponde al opuesto del ángulo dado, no al opuesto de su vecino.",
      "53°": "Eso completaría 90°, pero no hay marca de perpendicularidad.",
      "323°": "360° − 37° incluye tres de los cuatro ángulos del cruce.",
    }),
    success: "El vecino mide 143° y el ángulo enfrentado también mide 143°.",
    visual: { type: "intersection", known: 37, missing: 143, relation: "opposite-adjacent" },
    steps: [
      { eyebrow: "Paso 1 · encuentra el vecino", title: "Completa la línea", equation: "180° − 37° = 143°", text: "El ángulo que comparte lado con 37° mide 143°." },
      { eyebrow: "Paso 2 · sigue la instrucción", title: "Ahora localiza su opuesto", equation: "143° ↔ ?", text: "La región señalada está al otro lado del vértice." },
      { eyebrow: "Paso 3 · usa la igualdad", title: "Los enfrentados miden lo mismo", equation: "? = 143°", text: "La respuesta requiere encadenar las dos relaciones." },
    ],
  },
  {
    id: "GM03-N1-17",
    family: "special-triangles",
    level: 1,
    title: "Tres lados iguales",
    prompt: "¿Cuánto mide cada ángulo de un triángulo equilátero?",
    hint: "Sus tres lados y sus tres ángulos son iguales.",
    answer: "60°",
    options: numericOptions(60, [45, 60, 90, 180], {
      "45°": "Tres ángulos de 45° sumarían 135°, no 180°.",
      "90°": "Tres ángulos rectos sumarían 270°, imposible para un triángulo.",
      "180°": "180° es la suma de los tres ángulos, no la medida de cada uno.",
    }),
    success: "180° repartidos en tres ángulos iguales dan 60°.",
    visual: { type: "special-triangle", kind: "equilateral", angles: [60, 60, 60], missing: 2 },
    steps: [
      { eyebrow: "Paso 1 · interpreta las marcas", title: "Los tres lados son iguales", equation: "lado = lado = lado", text: "Las mismas marcas en los lados indican igualdad." },
      { eyebrow: "Paso 2 · conecta lados y ángulos", title: "También tiene tres ángulos iguales", equation: "A = B = C", text: "Un triángulo equilátero reparte la suma por igual." },
      { eyebrow: "Paso 3 · divide el total", title: "Reparte 180° entre tres", equation: "180° ÷ 3 = 60°", text: "Cada ángulo interior mide 60°." },
    ],
  },
  {
    id: "GM03-N3-18",
    family: "special-triangles",
    level: 3,
    title: "Dos lados iguales",
    prompt: "El ángulo superior mide 40°. ¿Cuánto mide cada ángulo de la base?",
    hint: "Los dos ángulos de la base son iguales.",
    answer: "70°",
    options: numericOptions(70, [40, 60, 70, 140], {
      "40°": "Los ángulos de la base son iguales entre sí, pero no tienen que igualar al superior.",
      "60°": "Eso ocurre en un equilátero; aquí solo hay dos lados marcados como iguales.",
      "140°": "140° es lo que queda entre ambos ángulos de la base, no la medida de cada uno.",
    }),
    success: "Quedan 140° y se reparten por igual: 70° y 70°.",
    visual: { type: "special-triangle", kind: "isosceles", angles: [70, 70, 40], missing: 0 },
    steps: [
      { eyebrow: "Paso 1 · resta el superior", title: "Quita 40° del total", equation: "180° − 40° = 140°", text: "Los 140° restantes pertenecen a los dos ángulos de la base." },
      { eyebrow: "Paso 2 · usa la igualdad", title: "Las marcas indican dos lados iguales", equation: "ángulo A = ángulo B", text: "En un isósceles, los ángulos opuestos a los lados iguales también son iguales." },
      { eyebrow: "Paso 3 · reparte", title: "Divide los 140° en dos", equation: "140° ÷ 2 = 70°", text: "Cada ángulo de la base mide 70°." },
    ],
  },
  {
    id: "GM03-N1-19",
    family: "special-triangles",
    level: 1,
    title: "Ángulos de la misma base",
    prompt: "Si el triángulo es isósceles, ¿cuánto mide el ángulo B?",
    hint: "Las marcas muestran que los dos lados inclinados son iguales.",
    answer: "54°",
    options: numericOptions(54, [54, 72, 108, 126], {
      "72°": "72° es el ángulo superior que resultaría después; primero usa la igualdad de la base.",
      "108°": "Eso duplica 54°, pero la pregunta solicita un solo ángulo.",
      "126°": "126° es el suplemento de 54°, no el otro ángulo de la base.",
    }),
    success: "Los ángulos de la base de un isósceles son iguales: B mide 54°.",
    visual: { type: "special-triangle", kind: "isosceles", angles: [54, 54, 72], missing: 1 },
    steps: [
      { eyebrow: "Paso 1 · lee las marcas", title: "Los lados inclinados son iguales", equation: "AC = BC", text: "Las pequeñas rayas sobre ambos lados comunican esa igualdad." },
      { eyebrow: "Paso 2 · conecta la propiedad", title: "Los ángulos de la base coinciden", equation: "A = B", text: "Cada uno está opuesto a uno de los lados iguales." },
      { eyebrow: "Paso 3 · transfiere la medida", title: "B tiene la misma medida que A", equation: "B = 54°", text: "Después podríamos comprobar que el superior mide 72°." },
    ],
  },
  {
    id: "GM03-N3-20",
    family: "special-triangles",
    level: 3,
    title: "El vértice del isósceles",
    prompt: "Los dos ángulos de la base miden 68°. ¿Cuánto mide el ángulo C?",
    hint: "Suma primero los dos ángulos iguales.",
    answer: "44°",
    options: numericOptions(44, [34, 44, 68, 136], {
      "34°": "180° − 136° es 44°, no 34°.",
      "68°": "El ángulo superior no tiene que ser igual a los de la base; solo dos lados están marcados.",
      "136°": "136° es la suma de los ángulos de la base, no el faltante.",
    }),
    success: "68° + 68° = 136°; el vértice mide los 44° restantes.",
    visual: { type: "special-triangle", kind: "isosceles", angles: [68, 68, 44], missing: 2 },
    steps: [
      { eyebrow: "Paso 1 · reúne los iguales", title: "Suma los ángulos de la base", equation: "68° + 68° = 136°", text: "Las marcas del isósceles justifican que ambos tienen esa medida." },
      { eyebrow: "Paso 2 · completa el total", title: "Los tres forman 180°", equation: "136° + C = 180°", text: "El ángulo del vértice ocupa lo que falta." },
      { eyebrow: "Paso 3 · resta", title: "Calcula el vértice", equation: "C = 180° − 136° = 44°", text: "La suma 68° + 68° + 44° confirma el resultado." },
    ],
  },
  {
    id: "GM03-N3-21",
    family: "combined",
    level: 3,
    title: "El ángulo exterior",
    prompt: "¿Cuánto mide el ángulo exterior señalado?",
    hint: "Un ángulo exterior es igual a la suma de los dos interiores no adyacentes.",
    answer: "115°",
    options: numericOptions(115, [31, 65, 115, 180], {
      "31°": "Restar 73° − 42° no usa la relación del ángulo exterior.",
      "65°": "65° es el ángulo interior adyacente; el exterior forma una línea con él.",
      "180°": "180° es el total de la línea, no solo la región exterior marcada.",
    }),
    success: "El exterior mide 42° + 73° = 115°.",
    visual: { type: "exterior-triangle", angles: [42, 65, 73], exterior: 115, missing: "exterior" },
    steps: [
      { eyebrow: "Paso 1 · selecciona los remotos", title: "Usa 42° y 73°", equation: "interiores remotos: 42° y 73°", text: "Son los dos ángulos interiores que no tocan el exterior señalado." },
      { eyebrow: "Paso 2 · aplica el teorema", title: "El exterior es su suma", equation: "exterior = 42° + 73°", text: "Esta relación evita calcular primero el interior adyacente." },
      { eyebrow: "Paso 3 · suma", title: "Encuentra la abertura exterior", equation: "42° + 73° = 115°", text: "También se comprueba porque 115° + 65° forma una línea de 180°." },
    ],
  },
  {
    id: "GM03-N3-22",
    family: "combined",
    level: 3,
    title: "Del exterior al interior remoto",
    prompt: "El exterior mide 130°. ¿Cuánto mide el ángulo C?",
    hint: "El exterior equivale a la suma de los dos interiores remotos.",
    answer: "72°",
    options: numericOptions(72, [50, 58, 72, 188], {
      "50°": "50° es el interior adyacente, porque 180° − 130° = 50°.",
      "58°": "58° es uno de los interiores remotos; aún debes encontrar el otro.",
      "188°": "Sumar 130° y 58° no aísla el ángulo desconocido.",
    }),
    success: "130° = 58° + C, por lo tanto C mide 72°.",
    visual: { type: "exterior-triangle", angles: [58, 50, 72], exterior: 130, missing: 2 },
    steps: [
      { eyebrow: "Paso 1 · escribe la relación", title: "Exterior igual a remotos", equation: "130° = 58° + C", text: "El ángulo C y el de 58° no son adyacentes al exterior." },
      { eyebrow: "Paso 2 · despeja C", title: "Quita 58° de ambos lados", equation: "C = 130° − 58°", text: "No necesitamos usar los tres interiores para resolverlo." },
      { eyebrow: "Paso 3 · calcula", title: "El remoto faltante mide 72°", equation: "C = 72°", text: "Comprobación: 58° + 72° = 130°." },
    ],
  },
  {
    id: "GM03-N3-23",
    family: "combined",
    level: 3,
    title: "Exterior de un isósceles",
    prompt: "El exterior mide 118°. ¿Cuánto mide el ángulo del vértice C?",
    hint: "Primero encuentra el interior adyacente y usa las marcas de lados iguales.",
    answer: "56°",
    options: numericOptions(56, [44, 56, 62, 118], {
      "44°": "El interior adyacente es 62°, no 68°; revisa 180° − 118°.",
      "62°": "62° es cada ángulo de la base. La pregunta pide el ángulo del vértice.",
      "118°": "El exterior no es igual al ángulo del vértice; incluye la suma de dos interiores remotos.",
    }),
    success: "El interior de la base es 62°; quedan 56° para el vértice.",
    visual: { type: "exterior-triangle", angles: [62, 62, 56], exterior: 118, missing: 2, isosceles: true },
    steps: [
      { eyebrow: "Paso 1 · completa la línea", title: "Encuentra el interior adyacente", equation: "180° − 118° = 62°", text: "El exterior y el ángulo interior de la base forman una línea." },
      { eyebrow: "Paso 2 · usa el isósceles", title: "Los dos ángulos de la base son iguales", equation: "A = B = 62°", text: "Las marcas indican dos lados inclinados iguales." },
      { eyebrow: "Paso 3 · completa el triángulo", title: "Resta ambos ángulos de la base", equation: "180° − 62° − 62° = 56°", text: "El ángulo del vértice C mide 56°." },
    ],
  },
  {
    id: "GM03-N3-24",
    family: "combined",
    level: 3,
    title: "El agudo de un triángulo rectángulo",
    prompt: "¿Cuánto mide el ángulo C?",
    hint: "Después de usar el ángulo recto, los otros dos deben completar 90°.",
    answer: "56°",
    options: numericOptions(56, [34, 46, 56, 146], {
      "34°": "No hay marcas que indiquen que los dos ángulos agudos sean iguales.",
      "46°": "90° − 34° es 56°, no 46°.",
      "146°": "146° es 180° − 34°, pero aún debes descontar el ángulo recto.",
    }),
    success: "En un triángulo rectángulo los dos agudos suman 90°: C mide 56°.",
    visual: { type: "triangle", angles: [90, 34, 56], missing: 2, rightIndex: 0 },
    steps: [
      { eyebrow: "Paso 1 · separa el ángulo recto", title: "Noventa grados ya están ocupados", equation: "180° − 90° = 90°", text: "Por eso los otros dos ángulos agudos deben sumar 90°." },
      { eyebrow: "Paso 2 · plantea el complemento", title: "Completa los 90° restantes", equation: "34° + C = 90°", text: "Ahora el problema se convierte en una relación complementaria." },
      { eyebrow: "Paso 3 · resta", title: "Encuentra C", equation: "C = 90° − 34° = 56°", text: "Comprobación: 90° + 34° + 56° = 180°." },
    ],
  },
];

export const GEOMETRY_QUESTIONS = questions.map((question, index) => ({
  ...question,
  number: index + 1,
  familyLabel: GEOMETRY_FAMILIES.find((family) => family.id === question.family)?.label,
}));
