const step = (eyebrow, title, equation, text) => ({ eyebrow, title, equation, text });

function question(config) {
  return {
    ...config,
    options: config.choices.map((value) => ({ value, feedback: value === config.answer ? null : config.wrongFeedback })),
    choices: undefined,
    wrongFeedback: undefined,
  };
}

export const NATURAL_OPERATION_FAMILIES = [
  { id: "add-subtract", label: "Suma y resta", short: "Sumar y restar" },
  { id: "multiplication", label: "Multiplicación", short: "Multiplicar" },
  { id: "division", label: "División", short: "Dividir" },
  { id: "multi-step", label: "Problemas de varios pasos", short: "Problemas" },
  { id: "estimation", label: "Estimación y comprobación", short: "Estimar" },
  { id: "error-analysis", label: "Análisis de errores", short: "Revisar errores" },
];

const questions = [
  question({
    id: "NO02-N1-01", family: "add-subtract", level: 1, title: "Reunir dos cantidades",
    prompt: "¿Cuál es el resultado de 347 + 286?", hint: "Alinea unidades, decenas y centenas.",
    answer: "633", choices: ["523", "623", "633", "6.330"],
    wrongFeedback: "Suma por columnas y reagrupa cuando una columna supera 9; en las unidades, 7 + 6 produce 13.",
    success: "347 + 286 = 633.",
    visual: { type: "column-operation", top: 347, bottom: 286, operation: "+" },
    steps: [
      step("Paso 1 · unidades", "Suma 7 y 6", "7 + 6 = 13", "Escribe 3 unidades y reagrupa 1 decena."),
      step("Paso 2 · decenas", "Incluye la decena reagrupada", "1 + 4 + 8 = 13", "Escribe 3 decenas y reagrupa 1 centena."),
      step("Paso 3 · centenas", "Completa la suma", "1 + 3 + 2 = 6", "El resultado formado es 633."),
    ],
  }),
  question({
    id: "NO02-N1-02", family: "add-subtract", level: 1, title: "Restar con reagrupación",
    prompt: "¿Cuánto es 900 − 478?", hint: "Necesitarás reagrupar desde las centenas.",
    answer: "422", choices: ["322", "412", "422", "532"],
    wrongFeedback: "No se puede hacer 0 − 8 directamente. Reagrupa 900 como 8 centenas, 9 decenas y 10 unidades.",
    success: "900 − 478 = 422.",
    visual: { type: "column-operation", top: 900, bottom: 478, operation: "−" },
    steps: [
      step("Paso 1 · reagrupa", "Descompón una centena", "900 = 8C + 9D + 10U", "La reagrupación permite restar las unidades."),
      step("Paso 2 · resta unidades y decenas", "Calcula de derecha a izquierda", "10 − 8 = 2; 9 − 7 = 2", "Obtenemos 2 unidades y 2 decenas."),
      step("Paso 3 · resta centenas", "Termina con las centenas", "8 − 4 = 4", "El resultado es 422."),
    ],
  }),
  question({
    id: "NO02-N2-03", family: "add-subtract", level: 2, title: "Encontrar una parte faltante",
    prompt: "¿Qué número completa 265 + ? = 700?", hint: "Puedes pensar cuánto falta desde 265 hasta 700.",
    answer: "435", choices: ["335", "425", "435", "965"],
    wrongFeedback: "La cantidad faltante se obtiene restando el sumando conocido al total: 700 − 265.",
    success: "265 + 435 = 700.",
    visual: { type: "missing-number", equation: ["265", "+", "?", "=", "700"], model: [265, 435], total: 700 },
    steps: [
      step("Paso 1 · invierte la relación", "Usa el total y la parte conocida", "? = 700 − 265", "La resta encuentra la parte que falta en una suma."),
      step("Paso 2 · calcula", "Resta por columnas", "700 − 265 = 435", "Reagrupa desde las centenas para completar la resta."),
      step("Paso 3 · comprueba", "Vuelve a sumar", "265 + 435 = 700", "La igualdad confirma que 435 es la parte faltante."),
    ],
  }),
  question({
    id: "NO02-N2-04", family: "add-subtract", level: 2, title: "Libros prestados y devueltos",
    prompt: "Una biblioteca tenía 1.250 libros disponibles, prestó 675 y recibió 238 devoluciones. ¿Cuántos tiene disponibles ahora?",
    hint: "Primero disminuye la cantidad y después vuelve a aumentarla.",
    answer: "813", choices: ["337", "575", "813", "1.687"],
    wrongFeedback: "Representa los cambios en orden: 1.250 − 675 + 238.",
    success: "Después de prestar y recibir devoluciones quedan 813 libros.",
    visual: { type: "change-bar", start: "1.250", changes: ["− 675", "+ 238"], end: "?" },
    steps: [
      step("Paso 1 · préstamo", "Resta los libros que salieron", "1.250 − 675 = 575", "Después del préstamo quedan 575 disponibles."),
      step("Paso 2 · devolución", "Suma los libros que regresaron", "575 + 238", "Las devoluciones aumentan la disponibilidad."),
      step("Paso 3 · calcula", "Ahora hay 813 libros", "575 + 238 = 813", "El orden de los cambios coincide con la historia."),
    ],
  }),
  question({
    id: "NO02-N1-05", family: "multiplication", level: 1, title: "Siete grupos iguales",
    prompt: "¿Cuánto es 36 × 7?", hint: "Descompón 36 en 30 y 6.",
    answer: "252", choices: ["42", "212", "242", "252"],
    wrongFeedback: "Distribuye el 7: 30 × 7 y 6 × 7; después suma los productos parciales.",
    success: "36 × 7 = 252.",
    visual: { type: "array-model", groups: 7, size: 36, decomposition: [30, 6] },
    steps: [
      step("Paso 1 · descompón", "Separa 36 en 30 y 6", "36 = 30 + 6", "La propiedad distributiva permite multiplicar partes más sencillas."),
      step("Paso 2 · multiplica las partes", "Calcula dos productos", "30 × 7 = 210; 6 × 7 = 42", "Ambos productos representan los siete grupos."),
      step("Paso 3 · reúne", "Suma los productos parciales", "210 + 42 = 252", "Por lo tanto, 36 × 7 = 252."),
    ],
  }),
  question({
    id: "NO02-N2-06", family: "multiplication", level: 2, title: "Multiplicar por quince",
    prompt: "¿Cuál es el producto de 24 × 15?", hint: "Puedes pensar en 15 como 10 + 5.",
    answer: "360", choices: ["120", "240", "300", "360"],
    wrongFeedback: "Calcula 24 × 10 y 24 × 5; el producto completo necesita ambas partes.",
    success: "24 × 15 = 360.",
    visual: { type: "area-product", factors: [24, 15], split: [10, 5] },
    steps: [
      step("Paso 1 · divide un factor", "Quince es diez más cinco", "24 × (10 + 5)", "Usamos una descomposición que facilita los productos."),
      step("Paso 2 · distribuye", "Multiplica 24 por cada parte", "240 + 120", "24 × 10 = 240 y 24 × 5 = 120."),
      step("Paso 3 · suma", "Combina los productos", "240 + 120 = 360", "El producto completo es 360."),
    ],
  }),
  question({
    id: "NO02-N2-07", family: "multiplication", level: 2, title: "Factor desconocido",
    prompt: "¿Qué número completa 18 × ? = 270?", hint: "La división deshace la multiplicación.",
    answer: "15", choices: ["12", "15", "18", "252"],
    wrongFeedback: "Divide el producto total entre el factor conocido: 270 ÷ 18.",
    success: "18 × 15 = 270.",
    visual: { type: "missing-number", equation: ["18", "×", "?", "=", "270"], model: [18, 15], total: 270 },
    steps: [
      step("Paso 1 · usa la operación inversa", "Convierte el problema en una división", "? = 270 ÷ 18", "Buscamos cuántos grupos de 18 forman 270."),
      step("Paso 2 · encuentra el cociente", "Descompón 270", "18 × 10 = 180; faltan 90", "Noventa contiene cinco grupos adicionales de 18."),
      step("Paso 3 · comprueba", "Diez más cinco son quince grupos", "18 × 15 = 270", "El factor faltante es 15."),
    ],
  }),
  question({
    id: "NO02-N1-08", family: "multiplication", level: 1, title: "Ocho paquetes",
    prompt: "Hay 8 paquetes con 125 fichas cada uno. ¿Cuántas fichas hay en total?",
    hint: "Todos los paquetes contienen la misma cantidad.",
    answer: "1.000", choices: ["133", "875", "1.000", "8.125"],
    wrongFeedback: "Ocho grupos de 125 se representan con 125 × 8, no con una suma de los dos números.",
    success: "8 × 125 = 1.000 fichas.",
    visual: { type: "array-model", groups: 8, size: 125, decomposition: [100, 25] },
    steps: [
      step("Paso 1 · representa", "Son ocho grupos iguales", "8 × 125", "La multiplicación resume la suma repetida."),
      step("Paso 2 · descompón", "Separa 125 en 100 y 25", "8 × 100 + 8 × 25", "Los productos parciales son 800 y 200."),
      step("Paso 3 · suma", "Reúne todas las fichas", "800 + 200 = 1.000", "Hay mil fichas en total."),
    ],
  }),
  question({
    id: "NO02-N1-09", family: "division", level: 1, title: "Reparto exacto",
    prompt: "¿Cuánto es 144 ÷ 12?", hint: "Busca qué número multiplicado por 12 produce 144.",
    answer: "12", choices: ["10", "12", "14", "132"],
    wrongFeedback: "Comprueba cada cociente multiplicándolo por 12. Solo 12 × 12 recupera 144.",
    success: "144 ÷ 12 = 12.",
    visual: { type: "division-groups", total: 144, groups: 12, groupSize: 12 },
    steps: [
      step("Paso 1 · interpreta", "Divide 144 en doce grupos", "144 ÷ 12", "Buscamos cuántos elementos recibe cada grupo."),
      step("Paso 2 · conecta con multiplicación", "Piensa en un hecho conocido", "12 × 12 = 144", "Multiplicación y división son operaciones inversas."),
      step("Paso 3 · responde", "Cada grupo recibe 12", "144 ÷ 12 = 12", "El reparto es exacto y no queda residuo."),
    ],
  }),
  question({
    id: "NO02-N2-10", family: "division", level: 2, title: "Veinticinco por grupo",
    prompt: "¿Cuál es el resultado de 275 ÷ 25?", hint: "Separa 275 en 250 y 25.",
    answer: "11", choices: ["9", "10", "11", "25"],
    wrongFeedback: "250 contiene diez grupos de 25 y los 25 restantes forman un grupo adicional.",
    success: "275 ÷ 25 = 11.",
    visual: { type: "division-groups", total: 275, groups: 11, groupSize: 25 },
    steps: [
      step("Paso 1 · encuentra diez grupos", "Diez grupos de 25 forman 250", "25 × 10 = 250", "Todavía quedan 25 por repartir."),
      step("Paso 2 · añade el restante", "Los 25 restantes forman otro grupo", "250 + 25 = 275", "En total hay once grupos."),
      step("Paso 3 · comprueba", "Multiplica cociente por divisor", "11 × 25 = 275", "El cociente correcto es 11."),
    ],
  }),
  question({
    id: "NO02-N2-11", family: "division", level: 2, title: "División con residuo",
    prompt: "Al repartir 157 objetos en grupos de 12, ¿cuántos grupos completos se forman y cuántos sobran?",
    hint: "Busca el mayor múltiplo de 12 que no supere 157.",
    answer: "13 grupos y sobra 1", choices: ["12 grupos y sobran 13", "13 grupos exactos", "13 grupos y sobra 1", "14 grupos y sobra 1"],
    wrongFeedback: "Doce por trece es 156. Compara ese producto con 157 y calcula la diferencia.",
    success: "12 × 13 = 156 y sobra 1 objeto.",
    visual: { type: "division-groups", total: 157, groups: 13, groupSize: 12, remainder: 1 },
    steps: [
      step("Paso 1 · busca un múltiplo cercano", "Trece grupos usan 156 objetos", "12 × 13 = 156", "Catorce grupos necesitarían 168, que supera el total."),
      step("Paso 2 · calcula el residuo", "Compara 157 con 156", "157 − 156 = 1", "Ese objeto no alcanza para formar otro grupo de 12."),
      step("Paso 3 · expresa", "Hay 13 grupos y sobra 1", "157 = 12 × 13 + 1", "El residuo siempre debe ser menor que el divisor."),
    ],
  }),
  question({
    id: "NO02-N2-12", family: "division", level: 2, title: "Reconstruir el total",
    prompt: "Un número dividido entre 8 da 45. ¿Cuál es el número?", hint: "Multiplica el cociente por el divisor.",
    answer: "360", choices: ["37", "53", "320", "360"],
    wrongFeedback: "Si total ÷ 8 = 45, entonces total = 45 × 8.",
    success: "360 ÷ 8 = 45.",
    visual: { type: "missing-number", equation: ["?", "÷", "8", "=", "45"], model: [45, 8], total: 360 },
    steps: [
      step("Paso 1 · identifica la relación", "El total contiene 45 grupos de 8", "? = 45 × 8", "La multiplicación reconstruye lo que se dividió."),
      step("Paso 2 · multiplica", "Calcula 45 por 8", "40 × 8 + 5 × 8", "Los productos parciales son 320 y 40."),
      step("Paso 3 · comprueba", "El total es 360", "360 ÷ 8 = 45", "La división original confirma el resultado."),
    ],
  }),
  question({
    id: "NO02-N2-13", family: "multi-step", level: 2, title: "Lápices después de usarlos",
    prompt: "Hay 6 cajas con 48 lápices cada una. Se usan 75. ¿Cuántos lápices quedan?",
    hint: "Primero encuentra cuántos lápices había en las seis cajas.",
    answer: "213", choices: ["123", "213", "288", "363"],
    wrongFeedback: "Calcula 6 × 48 para obtener el total inicial y después resta 75.",
    success: "6 × 48 − 75 = 213.",
    visual: { type: "multi-step-bar", parts: ["6 × 48", "− 75"], result: "?" },
    steps: [
      step("Paso 1 · total inicial", "Multiplica cajas por lápices", "6 × 48 = 288", "Antes de usarlos había 288 lápices."),
      step("Paso 2 · representa el cambio", "Se usaron 75", "288 − 75", "La cantidad debe disminuir."),
      step("Paso 3 · calcula", "Quedan 213 lápices", "288 − 75 = 213", "La respuesta es menor que el total inicial, como exige la historia."),
    ],
  }),
  question({
    id: "NO02-N3-14", family: "multi-step", level: 3, title: "Asientos ocupados",
    prompt: "Un teatro tiene 18 filas de 24 asientos. Si 37 están vacíos, ¿cuántos están ocupados?",
    hint: "Calcula primero la capacidad completa.",
    answer: "395", choices: ["358", "395", "432", "469"],
    wrongFeedback: "La capacidad es 18 × 24. Después resta los 37 asientos vacíos.",
    success: "18 × 24 − 37 = 395 asientos ocupados.",
    visual: { type: "multi-step-bar", parts: ["18 × 24", "− 37 vacíos"], result: "? ocupados" },
    steps: [
      step("Paso 1 · capacidad", "Multiplica filas por asientos", "18 × 24 = 432", "Esto cuenta todos los asientos del teatro."),
      step("Paso 2 · distingue vacíos", "Resta los que no están ocupados", "432 − 37", "No debemos sumar los vacíos al total."),
      step("Paso 3 · resuelve", "Hay 395 ocupados", "432 − 37 = 395", "Ocupados más vacíos vuelve a dar 432."),
    ],
  }),
  question({
    id: "NO02-N3-15", family: "multi-step", level: 3, title: "Inventario de cuadernos",
    prompt: "Una tienda recibe 15 paquetes de 36 cuadernos y vende 248. ¿Cuántos quedan?",
    hint: "La llegada aumenta el inventario y la venta lo disminuye.",
    answer: "292", choices: ["212", "292", "540", "788"],
    wrongFeedback: "Calcula primero 15 × 36 = 540 y resta después los 248 vendidos.",
    success: "540 − 248 = 292 cuadernos.",
    visual: { type: "multi-step-bar", parts: ["15 × 36", "− 248 vendidos"], result: "?" },
    steps: [
      step("Paso 1 · mercancía recibida", "Multiplica paquetes por unidades", "15 × 36 = 540", "La tienda recibe 540 cuadernos."),
      step("Paso 2 · ventas", "Quita los cuadernos vendidos", "540 − 248", "El inventario restante debe ser menor que 540."),
      step("Paso 3 · calcula", "Quedan 292", "540 − 248 = 292", "La suma 292 + 248 comprueba el total recibido."),
    ],
  }),
  question({
    id: "NO02-N3-16", family: "multi-step", level: 3, title: "Personas en un viaje",
    prompt: "Viajan 4 buses con 52 personas cada uno y 3 vans con 8 personas cada una. ¿Cuántas personas viajan?",
    hint: "Calcula cada tipo de vehículo por separado.",
    answer: "232", choices: ["208", "219", "232", "416"],
    wrongFeedback: "Suma dos productos: 4 × 52 para los buses y 3 × 8 para las vans.",
    success: "208 + 24 = 232 personas.",
    visual: { type: "multi-step-bar", parts: ["4 × 52", "+", "3 × 8"], result: "? personas" },
    steps: [
      step("Paso 1 · buses", "Cuenta las personas de los buses", "4 × 52 = 208", "Los cuatro buses tienen la misma cantidad."),
      step("Paso 2 · vans", "Cuenta las personas de las vans", "3 × 8 = 24", "Este grupo utiliza una capacidad diferente."),
      step("Paso 3 · reúne", "Suma ambos grupos", "208 + 24 = 232", "En total viajan 232 personas."),
    ],
  }),
  question({
    id: "NO02-N1-17", family: "estimation", level: 1, title: "Una suma cercana a mil",
    prompt: "¿Cuál es la mejor estimación de 398 + 603?", hint: "Redondea cada número a la centena más cercana.",
    answer: "1.000", choices: ["900", "1.000", "1.100", "10.000"],
    wrongFeedback: "398 se aproxima a 400 y 603 a 600; suma esos valores redondeados.",
    success: "400 + 600 = 1.000, muy cerca del resultado exacto 1.001.",
    visual: { type: "estimation", exact: [398, "+", 603], rounded: [400, "+", 600] },
    steps: [
      step("Paso 1 · redondea el primero", "398 está cerca de 400", "398 ≈ 400", "La diferencia es solo de dos unidades."),
      step("Paso 2 · redondea el segundo", "603 está cerca de 600", "603 ≈ 600", "La diferencia es de tres unidades."),
      step("Paso 3 · estima", "Suma los redondeados", "400 + 600 = 1.000", "El resultado exacto 1.001 confirma que la estimación es razonable."),
    ],
  }),
  question({
    id: "NO02-N2-18", family: "estimation", level: 2, title: "Estimar un producto",
    prompt: "¿Cuál es la mejor estimación de 49 × 21?", hint: "Redondea a decenas fáciles de multiplicar.",
    answer: "1.000", choices: ["100", "500", "1.000", "10.000"],
    wrongFeedback: "49 se aproxima a 50 y 21 a 20. Multiplica 50 × 20.",
    success: "50 × 20 = 1.000, cerca del producto exacto 1.029.",
    visual: { type: "estimation", exact: [49, "×", 21], rounded: [50, "×", 20] },
    steps: [
      step("Paso 1 · aproxima", "Cuarenta y nueve es casi cincuenta", "49 ≈ 50", "Elegimos un número compatible con la multiplicación mental."),
      step("Paso 2 · aproxima", "Veintiuno es casi veinte", "21 ≈ 20", "Ambos redondeos conservan el orden de magnitud."),
      step("Paso 3 · multiplica", "Cinco decenas por dos decenas", "50 × 20 = 1.000", "La estimación permite detectar productos demasiado pequeños o grandes."),
    ],
  }),
  question({
    id: "NO02-N3-19", family: "estimation", level: 3, title: "Elegir una diferencia razonable",
    prompt: "Sin hacer primero la resta exacta, ¿cuál resultado puede corresponder a 7.842 − 3.978?",
    hint: "Aproxima la operación como 7.800 − 4.000.",
    answer: "3.864", choices: ["386", "3.864", "4.964", "11.820"],
    wrongFeedback: "La diferencia debe estar cerca de 3.800. Descarta resultados con otro orden de magnitud o mayores que 7.842.",
    success: "3.864 es coherente con la estimación y es la diferencia exacta.",
    visual: { type: "estimation", exact: ["7.842", "−", "3.978"], rounded: ["7.800", "−", "4.000"] },
    steps: [
      step("Paso 1 · aproxima", "Usa números cercanos", "7.842 ≈ 7.800; 3.978 ≈ 4.000", "La resta estimada será un poco menor que 3.900."),
      step("Paso 2 · establece un rango", "La respuesta debe rondar 3.800", "7.800 − 4.000 ≈ 3.800", "Esto permite descartar 386, 4.964 y 11.820."),
      step("Paso 3 · verifica", "La opción razonable es 3.864", "7.842 − 3.978 = 3.864", "La estimación funcionó como control antes del cálculo exacto."),
    ],
  }),
  question({
    id: "NO02-N3-20", family: "estimation", level: 3, title: "Comprobar una multiplicación",
    prompt: "¿Cuál resultado es razonable para 126 × 39?", hint: "Compara con 126 × 40.",
    answer: "4.914", choices: ["491", "1.260", "4.914", "49.140"],
    wrongFeedback: "126 × 40 es 5.040, así que el producto por 39 debe ser un poco menor y del mismo orden.",
    success: "4.914 está ligeramente por debajo de 5.040 y es el producto exacto.",
    visual: { type: "estimation", exact: [126, "×", 39], rounded: [126, "×", 40] },
    steps: [
      step("Paso 1 · usa un factor cercano", "Treinta y nueve está cerca de cuarenta", "126 × 40 = 5.040", "Este producto funciona como referencia superior."),
      step("Paso 2 · ajusta", "Multiplicar por 39 es quitar un grupo de 126", "5.040 − 126", "La respuesta debe quedar cerca de cinco mil."),
      step("Paso 3 · calcula", "El producto es 4.914", "5.040 − 126 = 4.914", "La estimación descarta respuestas con ceros mal ubicados."),
    ],
  }),
  question({
    id: "NO02-N3-21", family: "error-analysis", level: 3, title: "Una resta mal reagrupada",
    prompt: "Mateo escribió 506 − 278 = 332. ¿Cuál es el resultado correcto?", hint: "Revisa especialmente las unidades: 6 − 8 necesita reagrupación.",
    answer: "228", choices: ["228", "232", "328", "332"],
    wrongFeedback: "Reagrupa 506 antes de restar. La comprobación correcta debe cumplir resultado + 278 = 506.",
    success: "506 − 278 = 228; Mateo no reagrupó correctamente.",
    visual: { type: "error-work", expression: "506 − 278", claimed: "332", note: "¿Dónde está el error?" },
    steps: [
      step("Paso 1 · detecta", "Seis unidades no alcanzan para quitar ocho", "6 − 8 requiere reagrupar", "Debemos convertir una centena en decenas y después una decena en unidades."),
      step("Paso 2 · resta correctamente", "Trabaja de derecha a izquierda", "16 − 8 = 8; 9 − 7 = 2; 4 − 2 = 2", "La reagrupación transforma 506 en 4C, 9D y 16U."),
      step("Paso 3 · comprueba", "Suma el resultado y lo restado", "228 + 278 = 506", "El resultado correcto es 228."),
    ],
  }),
  question({
    id: "NO02-N3-22", family: "error-analysis", level: 3, title: "Distribución incompleta",
    prompt: "Laura calculó 34 × 12 como 34 × 10 + 2 = 342. ¿Cuál es el producto correcto?",
    hint: "El 34 debe multiplicar a las dos partes de 12.",
    answer: "408", choices: ["342", "360", "398", "408"],
    wrongFeedback: "La descomposición correcta es 34 × 10 + 34 × 2, no 34 × 10 + 2.",
    success: "340 + 68 = 408.",
    visual: { type: "error-work", expression: "34 × 12", claimed: "34 × 10 + 2 = 342", note: "Falta distribuir 34" },
    steps: [
      step("Paso 1 · descompón", "Doce es diez más dos", "34 × (10 + 2)", "La descomposición de Laura sí comienza correctamente."),
      step("Paso 2 · distribuye a ambas partes", "Multiplica 34 dos veces", "34 × 10 + 34 × 2", "Laura añadió 2 en lugar de calcular 34 × 2."),
      step("Paso 3 · suma", "Combina 340 y 68", "340 + 68 = 408", "El producto correcto es 408."),
    ],
  }),
  question({
    id: "NO02-N3-23", family: "error-analysis", level: 3, title: "Un cociente demasiado grande",
    prompt: "Diego afirma que 196 ÷ 14 = 16. ¿Cuál es el cociente correcto?", hint: "Comprueba multiplicando 14 por el cociente propuesto.",
    answer: "14", choices: ["12", "14", "16", "182"],
    wrongFeedback: "14 × 16 = 224, que supera 196. Busca un múltiplo de 14 que sea exactamente 196.",
    success: "14 × 14 = 196, por eso el cociente es 14.",
    visual: { type: "error-work", expression: "196 ÷ 14", claimed: "16", note: "14 × 16 = 224" },
    steps: [
      step("Paso 1 · comprueba la afirmación", "Multiplica divisor por cociente", "14 × 16 = 224", "Como 224 no es 196, el cociente propuesto es incorrecto."),
      step("Paso 2 · ajusta", "Reduce dos grupos de 14", "224 − 28 = 196", "Dieciséis grupos menos dos grupos dejan catorce grupos."),
      step("Paso 3 · verifica", "Catorce por catorce da 196", "14 × 14 = 196", "El cociente correcto es 14."),
    ],
  }),
  question({
    id: "NO02-N2-24", family: "error-analysis", level: 2, title: "Elegir la operación adecuada",
    prompt: "Hay 48 cajas con 25 botellas cada una. ¿Qué cálculo encuentra el total de botellas?",
    hint: "Se repite la misma cantidad en cada caja.",
    answer: "48 × 25 = 1.200", choices: ["48 + 25 = 73", "48 − 25 = 23", "48 × 25 = 1.200", "48 ÷ 25 = 1,92"],
    wrongFeedback: "La situación describe 48 grupos iguales de 25; se necesita multiplicación, no sumar los dos datos una sola vez.",
    success: "48 grupos de 25 contienen 1.200 botellas.",
    visual: { type: "operation-choice", groups: 48, size: 25, labels: ["48 cajas", "25 por caja"] },
    steps: [
      step("Paso 1 · identifica la estructura", "Hay grupos iguales", "48 grupos de 25", "La cantidad 25 se repite una vez por cada caja."),
      step("Paso 2 · elige la operación", "La multiplicación resume la repetición", "48 × 25", "Sumar 48 + 25 no representa todas las cajas."),
      step("Paso 3 · calcula", "Descompón 48", "25 × 50 − 25 × 2 = 1.200", "El cálculo correcto es 48 × 25 = 1.200."),
    ],
  }),
];

export const NATURAL_OPERATION_QUESTIONS = questions.map((item, index) => ({
  ...item,
  number: index + 1,
  skillId: "NO02",
  familyLabel: NATURAL_OPERATION_FAMILIES.find((family) => family.id === item.family)?.label,
  skillLabel: "Operaciones con números naturales",
}));
