const fam=(id,label,short)=>({id,label,short});
export const RATIO_SKILL_DEFINITIONS=[
  {id:"RP01",title:"Razones y tasas unitarias",short:"Razones y tasas",symbol:"a:b",description:"Compara cantidades en el orden correcto y encuentra cuánto corresponde a una unidad.",families:[fam("ratio-read","Significado y escritura de razones","Leer razones"),fam("unit-rate","Tasa por una unidad","Tasa unitaria"),fam("ratio-table","Tablas de razones","Tablas"),fam("compare-rate","Comparación de tasas","Comparar tasas"),fam("ratio-scale","Escalar una situación","Escalar"),fam("rate-context","Velocidad, precio y rendimiento","Contextos")]},
  {id:"RP02",title:"Razones equivalentes",short:"Equivalencia",symbol:"=",description:"Escala ambos términos por el mismo factor y completa relaciones equivalentes.",families:[fam("scale-up","Ampliar razones","Ampliar"),fam("scale-down","Reducir razones","Reducir"),fam("missing-ratio","Término faltante","Valor faltante"),fam("equivalent-table","Tablas equivalentes","Tablas"),fam("double-line","Rectas numéricas dobles","Recta doble"),fam("equivalent-check","Comprobación de equivalencia","Comprobar")]},
  {id:"RP03",title:"Relaciones proporcionales",short:"Proporcionalidad",symbol:"k",description:"Reconoce una constante, conecta tabla, ecuación y gráfica, y descarta relaciones no proporcionales.",families:[fam("constant","Constante de proporcionalidad","Constante k"),fam("proportional-table","Tablas proporcionales","Tablas"),fam("proportional-equation","Ecuaciones y = kx","Ecuaciones"),fam("proportional-value","Valores desconocidos","Valores"),fam("proportional-graph","Lectura de gráficas","Gráficas"),fam("not-proportional","Relaciones no proporcionales","No proporcional")]},
  {id:"RP04",title:"Fracción, decimal y porcentaje",short:"Tres representaciones",symbol:"%",description:"Cambia entre fracción, decimal y porcentaje sin alterar el valor.",families:[fam("percent-from-fraction","Fracción a porcentaje","Fracción → %"),fam("percent-from-decimal","Decimal a porcentaje","Decimal → %"),fam("percent-to-fraction","Porcentaje a fracción","% → fracción"),fam("percent-compare","Comparar representaciones","Comparar"),fam("percent-order","Orden mixto","Ordenar"),fam("percent-grid","Cuadrículas de cien","Modelo de 100")]},
  {id:"RP05",title:"Aplicaciones de porcentajes",short:"Aplicar porcentajes",symbol:"% de",description:"Calcula partes, porcentajes, totales y cambios porcentuales en situaciones reales.",families:[fam("percent-of","Porcentaje de una cantidad","Calcular parte"),fam("find-percent","Qué porcentaje representa","Encontrar %"),fam("find-whole","Encontrar el total","Encontrar total"),fam("percent-change","Aumentos y disminuciones","Cambios"),fam("discount-tax","Descuentos e impuestos","Precio final"),fam("percent-error","Estimación y análisis de errores","Comprobar")]},
];

const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
const frac=(n,d)=>{const g=gcd(n,d);return d/g===1?`${n/g}`:`${n/g}/${d/g}`};
const dec=v=>Number(v.toFixed(4)).toString().replace(".",",");
function q(skillId,number,familyId,level,title,prompt,hint,answer,distractors,visual,models){const skill=RATIO_SKILL_DEFINITIONS.find(s=>s.id===skillId);const choices=[...new Set([answer,...distractors])].slice(0,4);while(choices.length<4)choices.push(`${choices.length+2}`);const shift=number%4;const ordered=[...choices.slice(shift),...choices.slice(0,shift)];return{id:`${skillId}-N${level}-${String(number).padStart(2,"0")}`,number,skillId,skillLabel:skill.title,family:familyId,familyLabel:skill.families.find(f=>f.id===familyId)?.label,level,title,prompt,hint,answer,visual,options:ordered.map(value=>({value,feedback:value===answer?null:`Revisa la relación: ${models[0]}. Después ${models[1]}.`})),success:`${models[2]}. Las cantidades conservan la misma relación.`,steps:models.map((equation,index)=>({eyebrow:`Paso ${index+1} · ${index===0?"identifica":index===1?"relaciona":"comprueba"}`,title:index===0?"Distingue las dos cantidades":index===1?"Conserva la razón":"Interpreta el resultado",equation,text:index===0?hint:index===1?"Aplica la misma operación a cantidades correspondientes.":`El resultado esperado es ${answer}.`}))}}

function buildRP01(){const r=[];
  [[3,5,"rojas","azules"],[4,7,"niñas","niños"],[2,9,"círculos","figuras"],[6,11,"libros","objetos"]].forEach(([a,b,x,y],j)=>r.push(q("RP01",j+1,"ratio-read",j<2?1:2,"Escribir en el orden pedido",`Hay ${a} ${x} y ${b} ${y}. ¿Cuál es la razón de ${x} a ${y}?`,"El orden de las palabras decide el orden de los números.",`${a}:${b}`,[`${b}:${a}`,`${a}:${a+b}`,`${a+b}:${b}`],{type:"ratio",left:{value:a,label:x},right:{value:b,label:y}},[`primera cantidad = ${a}`,`segunda cantidad = ${b}`,`razón = ${a}:${b}`])));
  [[12,3,"cuadernos","cajas"],[20,5,"kilómetros","horas"],[42,6,"dólares","entradas"],[96,8,"páginas","minutos"]].forEach(([total,units,x,y],j)=>{const ans=`${total/units} ${x} por ${y.slice(0,-1)}`;r.push(q("RP01",j+5,"unit-rate",j<2?1:2,"Reducir a una unidad",`${total} ${x} corresponden a ${units} ${y}. ¿Cuál es la tasa por 1 ${y.slice(0,-1)}?`,"Divide ambas cantidades entre el número de unidades.",ans,[`${units/total} ${x}`,`${total-units} ${x}`,`${total*units} ${x}`],{type:"operation",expression:`${total} ÷ ${units}`,stages:[`${total/units} por 1`,ans]},[`${units} → 1`,`divide entre ${units}`,`tasa = ${ans}`]))});
  [[2,6,5,15],[3,12,7,28],[4,10,10,25],[5,35,8,56]].forEach(([x1,y1,x2,y2],j)=>r.push(q("RP01",j+9,"ratio-table",j<2?2:3,"Leer una tabla de razón",`La tabla contiene (${x1}, ${y1}) y (${x2}, ${y2}). ¿Cuál es la tasa y por cada x?`,"Divide y entre x en cualquier fila.",`${y1/x1}`,[`${x1/y1}`,`${y2-y1}`,`${x1+x2}`],{type:"table",headers:["x","y"],rows:[[x1,y1],[x2,y2]]},[`${y1} ÷ ${x1}`,`${y2} ÷ ${x2}`,`tasa unitaria = ${y1/x1}`])));
  [[[180,3],[250,5]],[[84,4],[150,6]],[[56,7],[72,8]],[[144,12],[105,7]]].forEach(([a,b],j)=>{const ra=a[0]/a[1],rb=b[0]/b[1],ans=ra>rb?"La primera":"La segunda";r.push(q("RP01",j+13,"compare-rate",j<2?2:3,"Comparar tasas justamente",`Una opción produce ${a[0]} unidades en ${a[1]} horas y otra ${b[0]} en ${b[1]} horas. ¿Cuál tiene mayor tasa por hora?`,"Compara unidades por una hora, no los totales.",ans,[ans==="La primera"?"La segunda":"La primera","Son iguales","No se puede saber"],{type:"compare-rates",rates:[a,b]},[`${a[0]} ÷ ${a[1]} = ${ra}`,`${b[0]} ÷ ${b[1]} = ${rb}`,`${ans} tiene mayor tasa`]))});
  [[2,3,4],[3,5,3],[4,7,5],[5,8,6]].forEach(([a,b,k],j)=>r.push(q("RP01",j+17,"ratio-scale",j<2?1:2,"Escalar una mezcla",`Una mezcla usa ${a} tazas de concentrado por ${b} de agua. ¿Cuánta agua corresponde a ${a*k} tazas de concentrado?`,"Si una cantidad se multiplica, la otra debe cambiar por el mismo factor.",`${b*k} tazas`,[`${b+k} tazas`,`${a*k+b} tazas`,`${b} tazas`],{type:"double-line",top:[a,a*k],bottom:[b,b*k],labels:["concentrado","agua"]},[`${a} × ${k} = ${a*k}`,`${b} × ${k} = ${b*k}`,`agua = ${b*k} tazas`])));
  [[150,3,"km","h"],[24,6,"dólares","kg"],[360,8,"páginas","días"],[18,4,"L","min"]].forEach(([a,b,u,v],j)=>{const rate=a/b; r.push(q("RP01",j+21,"rate-context",j<2?2:3,"Interpretar una tasa",`Una relación muestra ${a} ${u} en ${b} ${v}. ¿Qué valor corresponde a 1 ${v.replace(/s$/,'')}?`,"Una tasa unitaria siempre expresa cuánto corresponde a uno.",`${rate} ${u}`,[`${a-b} ${u}`,`${a*b} ${u}`,`${b/a} ${u}`],{type:"ratio",left:{value:a,label:u},right:{value:b,label:v}},[`${a} ÷ ${b}`,`${b} ${v} → 1`, `tasa = ${rate} ${u}`]))});return r}

function buildRP02(){const r=[];
  [[2,3,4],[3,5,3],[4,7,2],[5,8,5]].forEach(([a,b,k],j)=>r.push(q("RP02",j+1,"scale-up",j<2?1:2,"Multiplicar ambos términos",`Amplía la razón ${a}:${b} por un factor de ${k}.`,"Multiplica los dos términos por el mismo número.",`${a*k}:${b*k}`,[`${a*k}:${b}`,`${a}:${b*k}`,`${a+k}:${b+k}`],{type:"double-line",top:[a,a*k],bottom:[b,b*k],labels:["primera","segunda"]},[`${a} × ${k}`,`${b} × ${k}`,`${a*k}:${b*k}`])));
  [[12,18,6],[20,30,10],[24,36,12],[35,49,7]].forEach(([a,b,k],j)=>r.push(q("RP02",j+5,"scale-down",j<2?1:2,"Reducir sin cambiar",`Reduce la razón ${a}:${b} dividiendo ambos términos entre ${k}.`,"La misma división conserva la relación.",`${a/k}:${b/k}`,[`${a/k}:${b}`,`${a}:${b/k}`,`${a-k}:${b-k}`],{type:"operation",expression:`${a}:${b} ÷ ${k}`,stages:[`${a/k}:${b/k}`]},[`${a} ÷ ${k}`,`${b} ÷ ${k}`,`razón reducida = ${a/k}:${b/k}`])));
  [[2,5,6],[3,4,20],[5,8,24],[7,9,45]].forEach(([a,b,target],j)=>{const k=target/b,ans=`${a*k}`;r.push(q("RP02",j+9,"missing-ratio",j<2?2:3,"Completar una proporción",`Completa ${a}/${b} = ?/${target}.`,"Encuentra el factor que transforma el denominador.",ans,[`${a+k}`,`${target-a}`,`${a*target}`],{type:"operation",expression:`${a}/${b} = ?/${target}`,stages:[`factor ${k}`,`${a} × ${k}`,ans]},[`${b} × ${k} = ${target}`,`${a} × ${k} = ${ans}`,`valor faltante = ${ans}`]))});
  [[2,6,5,15],[3,9,7,21],[4,10,12,30],[5,8,20,32]].forEach(([a,b,c,d],j)=>r.push(q("RP02",j+13,"equivalent-table",j<2?2:3,"Dos filas equivalentes",`¿La tabla con pares (${a}, ${b}) y (${c}, ${d}) conserva la misma razón?`,"Divide la segunda cantidad entre la primera en ambas filas.","Sí",["No","Solo la primera fila","No hay información suficiente"],{type:"table",headers:["x","y"],rows:[[a,b],[c,d]]},[`${b}/${a} = ${b/a}`,`${d}/${c} = ${d/c}`,"las tasas son iguales"])));
  [[1,4,5],[2,6,4],[3,12,5],[5,15,6]].forEach(([a,b,k],j)=>r.push(q("RP02",j+17,"double-line",j<2?2:3,"Leer dos escalas",`En una recta doble, ${a} unidades corresponden a ${b}. ¿Qué corresponde a ${a*k} unidades?`,"Ambas líneas avanzan con el mismo factor.",`${b*k}`,[`${b+k}`,`${a*k+b}`,`${b}`],{type:"double-line",top:[a,a*k],bottom:[b,b*k],labels:["cantidad A","cantidad B"]},[`${a} → ${a*k} es ×${k}`,`${b} × ${k}`,`corresponden ${b*k}`])));
  [[[2,3],[8,12]],[[3,5],[9,15]],[[4,7],[12,20]],[[5,6],[20,24]]].forEach(([a,b],j)=>{const eq=a[0]*b[1]===a[1]*b[0],ans=eq?"Son equivalentes":"No son equivalentes";r.push(q("RP02",j+21,"equivalent-check",j<2?2:3,"Producto cruzado",`Compara las razones ${a[0]}:${a[1]} y ${b[0]}:${b[1]}.`,"Los productos cruzados deben coincidir.",ans,[eq?"No son equivalentes":"Son equivalentes","La primera siempre es mayor","No se puede saber"],{type:"compare-ratios",ratios:[a,b]},[`${a[0]} × ${b[1]} = ${a[0]*b[1]}`,`${a[1]} × ${b[0]} = ${a[1]*b[0]}`,ans]))});return r}

function buildRP03(){const r=[];
  [[2,8],[3,15],[4,14],[6,9]].forEach(([x,y],j)=>r.push(q("RP03",j+1,"constant",j<2?1:2,"Encontrar k",`Si y = kx y el par es (${x}, ${y}), ¿cuánto vale k?`,"Divide y entre x.",`${y/x}`,[`${x/y}`,`${y-x}`,`${x+y}`],{type:"equation",expression:"y = kx",values:`${y} = k · ${x}`},[`k = y/x`,`k = ${y}/${x}`,`k = ${y/x}`])));
  [[[1,3],[2,6],[4,12]],[[2,5],[4,10],[6,15]],[[1,4],[2,9],[3,12]],[[3,8],[6,16],[9,24]]].forEach((rows,j)=>{const rates=rows.map(([x,y])=>y/x),ok=rates.every(v=>v===rates[0]),ans=ok?"Sí, es proporcional":"No es proporcional";r.push(q("RP03",j+5,"proportional-table",j<2?2:3,"Auditar una tabla",`¿La tabla ${rows.map(p=>`(${p[0]}, ${p[1]})`).join(", ")} representa una relación proporcional?`,"La razón y/x debe ser constante.",ans,[ok?"No es proporcional":"Sí, es proporcional","Solo aumenta","No se puede saber"],{type:"table",headers:["x","y"],rows},[`tasas: ${rates.join(", ")}`,"compara todas las tasas",ans]))});
  [[3,12],[5,20],[7,14],[9,27]].forEach(([k,target],j)=>r.push(q("RP03",j+9,"proportional-equation",j<2?1:2,"Usar y = kx",`La relación es y = ${k}x. ¿Cuánto vale y cuando x = ${target/k}?`,"Sustituye x y conserva la multiplicación por k.",`${target}`,[`${target/k+k}`,`${target/k}`,`${target*k}`],{type:"equation",expression:`y = ${k}x`,values:`x = ${target/k}`},[`x = ${target/k}`,`y = ${k} × ${target/k}`,`y = ${target}`])));
  [[4,7,9],[6,5,8],[3,11,7],[8,4,15]].forEach(([x1,y1,x2],j)=>{const k=y1/x1,ans=dec(k*x2);r.push(q("RP03",j+13,"proportional-value",j<2?2:3,"Predecir otro valor",`En una relación proporcional, x = ${x1} corresponde a y = ${y1}. ¿Qué y corresponde a x = ${x2}?`,"Primero encuentra la constante y/x.",ans,[dec(y1/x2),dec(y1+x2),dec(k+x2)],{type:"double-line",top:[x1,x2],bottom:[y1,ans],labels:["x","y"]},[`k = ${y1}/${x1} = ${dec(k)}`,`y = ${dec(k)} × ${x2}`,`y = ${ans}`]))});
  [[2,"pasa por el origen"],[4,"forma una línea recta que pasa por el origen"],[3,"no pasa por el origen"],[5,"tiene una curva"]].forEach(([k,desc],j)=>{const ok=desc.includes("origen")&&!desc.startsWith("no"),ans=ok?"Puede ser proporcional":"No es proporcional";r.push(q("RP03",j+17,"proportional-graph",j<2?2:3,"Reconocer una gráfica proporcional",`Una gráfica ${desc}. ¿Qué conclusión es correcta?`,"Una relación proporcional forma una recta que atraviesa (0,0).",ans,[ok?"No es proporcional":"Puede ser proporcional","Toda gráfica creciente es proporcional","No se puede analizar"],{type:"graph",proportional:ok,k},["busca una recta","verifica el origen (0,0)",ans]))});
  [["y = 3x + 2","No es proporcional"],["y = 5x","Es proporcional"],["costo = 4x + 10","No es proporcional"],["distancia = 7x","Es proporcional"]].forEach(([expr,ans],j)=>r.push(q("RP03",j+21,"not-proportional",j<2?2:3,"Detectar una cantidad fija",`La relación es ${expr}. ¿Es proporcional?`,"Una cantidad sumada impide que la gráfica pase por el origen.",ans,[ans==="Es proporcional"?"No es proporcional":"Es proporcional","Depende de x","Siempre es proporcional"],{type:"equation",expression:expr,values:"revisa el término fijo"},["compara con y = kx","busca suma o costo inicial",ans])));return r}

function buildRP04(){const r=[];
  [[1,2],[1,4],[3,5],[7,10]].forEach(([n,d],j)=>{const ans=`${n/d*100}%`;r.push(q("RP04",j+1,"percent-from-fraction",j<2?1:2,"De fracción a cien",`Convierte ${n}/${d} en porcentaje.`,"Busca cuántas centésimas representa.",ans,[`${n/d}%`,`${d/n*10}%`,`${n*10}%`],{type:"percent-grid",percent:n/d*100},[`${n} ÷ ${d} = ${dec(n/d)}`,`${dec(n/d)} × 100`,`${n}/${d} = ${ans}`]))});
  [[.35,.08,.625,1.2][0],[.35,.08,.625,1.2][1],[.35,.08,.625,1.2][2],[.35,.08,.625,1.2][3]].forEach((v,j)=>{const ans=`${v*100}%`;r.push(q("RP04",j+5,"percent-from-decimal",j<2?1:2,"Decimal a porcentaje",`Convierte ${dec(v)} en porcentaje.`,"Multiplica el decimal por cien.",ans,[`${v}%`,`${v*10}%`,`${v/100}%`],{type:"percent-grid",percent:Math.min(v*100,100)},[`${dec(v)} × 100`,`${v*100} de cada 100`,ans]))});
  [[25,40,60,75][0],[25,40,60,75][1],[25,40,60,75][2],[25,40,60,75][3]].forEach((p,j)=>{const ans=frac(p,100);r.push(q("RP04",j+9,"percent-to-fraction",j<2?1:2,"Porcentaje a fracción",`Simplifica ${p}% como fracción.`,"Escribe el porcentaje sobre cien y reduce.",ans,[`${p}/10`,`${100}/${p}`,`${p}/100`],{type:"percent-grid",percent:p},[`${p}% = ${p}/100`,"simplifica factores comunes",`fracción = ${ans}`]))});
  [[[1,2],45],[[3,4],80],[[2,5],35],[[7,8],82]].forEach(([f,p],j)=>{const fp=f[0]/f[1]*100,sign=fp>p?">":"<",ans=`${frac(...f)} ${sign} ${p}%`;r.push(q("RP04",j+13,"percent-compare",j<2?2:3,"Comparar dos formatos",`Completa la comparación entre ${frac(...f)} y ${p}%.`,"Convierte ambos a porcentaje.",ans,[ans.replace(">","TEMP").replace("<",">").replace("TEMP","<"),`${frac(...f)} = ${p}%`,`No se puede comparar`],{type:"compare-values",values:[frac(...f),`${p}%`]},[`${frac(...f)} = ${fp}%`,`${fp}% ${sign} ${p}%`,ans]))});
  [[[1,4],.4,60],[[1,2],.75,80],[[2,5],.3,50],[[3,4],.7,90]].forEach(([f,d,p],j)=>{const vals=[{s:frac(...f),v:f[0]/f[1]},{s:dec(d),v:d},{s:`${p}%`,v:p/100}].sort((a,b)=>a.v-b.v);const ans=vals.map(v=>v.s).join(", ");r.push(q("RP04",j+17,"percent-order",j<2?2:3,"Ordenar tres formatos",`Ordena de menor a mayor: ${frac(...f)}, ${dec(d)}, ${p}%.`,"Convierte temporalmente a decimales o porcentajes.",ans,[ans.split(", ").reverse().join(", "),`${frac(...f)}, ${dec(d)}, ${p}%`,`Todos son iguales`],{type:"compare-values",values:[frac(...f),dec(d),`${p}%`]},["convierte las tres cantidades","compara su magnitud",`orden = ${ans}`]))});
  [18,32,67,85].forEach((p,j)=>r.push(q("RP04",j+21,"percent-grid",j<2?1:2,"Leer una cuadrícula",`En una cuadrícula de 100 casillas hay ${p} sombreadas. ¿Qué porcentaje representa?`,"Cada casilla equivale a uno por ciento.",`${p}%`,[`${100-p}%`,`${p/10}%`,`${p}/100%`],{type:"percent-grid",percent:p},[`total = 100`,`sombreadas = ${p}`,`porcentaje = ${p}%`])));return r}

function buildRP05(){const r=[];
  [[10,80],[25,60],[30,150],[15,240]].forEach(([p,total],j)=>{const ans=`${p/100*total}`;r.push(q("RP05",j+1,"percent-of",j<2?1:2,"Calcular una parte",`¿Cuánto es ${p}% de ${total}?`,"Convierte el porcentaje en decimal y multiplica.",ans,[`${total-p}`,`${p+total}`,`${p/total}`],{type:"operation",expression:`${p}% × ${total}`,stages:[`${p/100} × ${total}`,ans]},[`${p}% = ${dec(p/100)}`,`${dec(p/100)} × ${total}`,`parte = ${ans}`]))});
  [[15,60],[18,72],[35,140],[48,160]].forEach(([part,total],j)=>{const ans=`${part/total*100}%`;r.push(q("RP05",j+5,"find-percent",j<2?2:3,"Encontrar el porcentaje",`${part} representa qué porcentaje de ${total}?`,"Divide la parte entre el total y multiplica por cien.",ans,[`${total/part}%`,`${part/total}%`,`${total-part}%`],{type:"operation",expression:`${part} ÷ ${total}`,stages:[dec(part/total),ans]},[`parte/total = ${part}/${total}`,`decimal = ${dec(part/total)}`,`porcentaje = ${ans}`]))});
  [[12,20],[18,30],[45,25],[72,40]].forEach(([part,p],j)=>{const total=part/(p/100),ans=`${total}`;r.push(q("RP05",j+9,"find-whole",j<2?2:3,"Reconstruir el total",`${part} es el ${p}% de una cantidad. ¿Cuál es el total?`,"Divide la parte entre el porcentaje escrito como decimal.",ans,[`${part*p/100}`,`${part+p}`,`${part/(p)}`],{type:"operation",expression:`${part} ÷ ${dec(p/100)}`,stages:[ans,"100%"]},[`${p}% = ${dec(p/100)}`,`${part} ÷ ${dec(p/100)}`,`total = ${ans}`]))});
  [[100,20,"aumenta"],[250,10,"disminuye"],[80,25,"aumenta"],[300,15,"disminuye"]].forEach(([start,p,kind],j)=>{const change=start*p/100,final=kind==="aumenta"?start+change:start-change,ans=`${final}`;r.push(q("RP05",j+13,"percent-change",j<2?2:3,"Aplicar un cambio porcentual",`Una cantidad de ${start} ${kind} ${p}%. ¿Cuál es el nuevo valor?`,"Calcula primero el cambio y decide si se suma o se resta.",ans,[`${change}`,`${start-change}`,`${start+change}`],{type:"change",start,p,kind,final},[`cambio = ${p}% de ${start}`,`cambio = ${change}`,`nuevo valor = ${final}`]))});
  [[120,25,"descuento"],[200,19,"impuesto"],[80,15,"descuento"],[350,8,"impuesto"]].forEach(([price,p,kind],j)=>{const change=price*p/100,final=kind==="descuento"?price-change:price+change,ans=`$${final}`;r.push(q("RP05",j+17,"discount-tax",j<2?2:3,"Precio final",`Un producto cuesta $${price} y tiene ${p}% de ${kind}. ¿Cuál es el precio final?`,"Un descuento se resta; un impuesto se suma.",ans,[`$${change}`,`$${price-change}`,`$${price+change}`],{type:"change",start:price,p,kind,final},[`${p}% de ${price} = ${change}`,`${kind==="descuento"?"resta":"suma"} ${change}`,`precio final = $${final}`]))});
  [["20% de 50 = 20","10"],["50% de 30 = 60","15"],["10 es 10% de 50","20%"],["un descuento de 25% sobre 80 deja 25","60"]].forEach(([claim,answer],j)=>r.push(q("RP05",j+21,"percent-error",j<2?2:3,"Detectar un resultado imposible",`Se afirmó: «${claim}». ¿Cuál es la corrección?`,"Estima: el resultado debe respetar el tamaño del porcentaje.",answer,[claim.split(" = ").pop(),`${Number(j)+5}`,`${Number(j)+25}%`],{type:"error",claim,check:"usa parte = porcentaje × total"},["identifica parte, porcentaje y total","aplica la relación correcta",`corrección = ${answer}`])));return r}

const builders=[buildRP01,buildRP02,buildRP03,buildRP04,buildRP05];
export const RATIO_SKILLS=RATIO_SKILL_DEFINITIONS.map((skill,index)=>({...skill,questions:builders[index]()}));
export const RATIO_QUESTIONS=RATIO_SKILLS.flatMap(skill=>skill.questions);
