"use client";

import { useState } from "react";
import Link from "next/link";
import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { LogoWordmark } from "@/components/Logo";
import AlgebraReasoningBoard from "@/components/math/AlgebraReasoningBoard";
import FractionText from "@/components/math/FractionText";
import { ALGEBRA_QUESTIONS, ALGEBRA_SKILLS } from "@/lib/algebraQuestions";

export default function AlgebraPrototypePage() {
  const [questionIndex, setQuestionIndex] = useState(0);
  const [selected, setSelected] = useState(null);
  const [step, setStep] = useState(0);
  const reduceMotion = useReducedMotion();
  const question = ALGEBRA_QUESTIONS[questionIndex];
  const skill = ALGEBRA_SKILLS.find((item) => item.id === question.skillId);
  const current = step > 0 ? question.steps[step - 1] : null;
  const selectedOption = question.options.find((option) => option.value === selected);
  const correct = selected === question.answer;

  function go(index) { const normalized = (index + ALGEBRA_QUESTIONS.length) % ALGEBRA_QUESTIONS.length; setQuestionIndex(normalized); setSelected(null); setStep(0); }
  function goSkill(id) { const index = ALGEBRA_QUESTIONS.findIndex((item) => item.skillId === id); if (index >= 0) go(index); }
  function goFamily(id) { const index = ALGEBRA_QUESTIONS.findIndex((item) => item.skillId === question.skillId && item.family === id); if (index >= 0) go(index); }
  function choose(value) { if (selected) return; setSelected(value); setStep(1); }
  function advance() { if (step < 3) setStep((value) => value + 1); else go(questionIndex + 1); }

  return <main className="min-h-screen bg-[#f8f5ee] pb-16"><div className="mx-auto max-w-6xl px-4 py-5 sm:px-6 sm:py-7">
    <header className="flex items-center justify-between gap-3"><Link href="/"><LogoWordmark size={34}/></Link><span className="rounded-full bg-coral-soft px-3 py-2 text-[11px] font-extrabold uppercase tracking-wide text-coral sm:px-4 sm:text-xs">Banco de {ALGEBRA_QUESTIONS.length} ejercicios</span></header>

    <nav className="mt-6 grid gap-2 sm:grid-cols-2 lg:grid-cols-4" aria-label="Temas de álgebra">{ALGEBRA_SKILLS.map((item) => { const active = item.id === question.skillId; return <button key={item.id} type="button" onClick={() => goSkill(item.id)} className={`flex min-h-16 items-center gap-3 rounded-2xl border px-4 py-3 text-left transition ${active ? "border-coral bg-coral text-white shadow-soft" : "border-ink/10 bg-white text-ink hover:border-coral/40"}`}><span className={`grid h-10 w-10 shrink-0 place-items-center rounded-xl font-display text-sm font-black ${active ? "bg-white/15 text-white" : "bg-coral-soft text-coral"}`}>{item.symbol}</span><span><span className={`block text-[10px] font-extrabold uppercase tracking-wide ${active ? "text-white/70" : "text-muted"}`}>{item.id} · 24 preguntas</span><span className="block text-sm font-extrabold leading-tight">{item.title}</span></span></button>; })}</nav>

    <section className="mt-6 overflow-hidden rounded-[2rem] bg-night px-5 py-5 text-white shadow-soft sm:flex sm:items-center sm:justify-between sm:gap-6 sm:px-7"><div className="flex items-center gap-4"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-white/10 font-display text-xl font-black text-honey">{skill.symbol}</span><div><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-honey">Álgebra · {skill.id}</p><h1 className="mt-1 font-display text-2xl font-bold sm:text-3xl">{skill.title}</h1><p className="mt-1 text-sm text-white/65">{skill.description}</p></div></div><div className="mt-4 grid grid-cols-3 gap-2 sm:mt-0 sm:min-w-64">{[[6, "base"], [10, "aplicación"], [8, "razonamiento"]].map(([value, label]) => <div key={label} className="rounded-2xl bg-white/10 px-2 py-3 text-center"><strong className="block font-display text-xl text-honey">{value}</strong><span className="text-[10px] font-bold uppercase tracking-wide text-white/60">{label}</span></div>)}</div></section>

    <nav className="mt-6" aria-label="Familias de álgebra"><div className="no-scrollbar flex gap-2 overflow-x-auto pb-2">{skill.families.map((item) => <button key={item.id} type="button" onClick={() => goFamily(item.id)} className={`shrink-0 rounded-full border px-4 py-2 text-sm font-bold transition ${question.family === item.id ? "border-night bg-night text-white shadow-sm" : "border-ink/10 bg-white text-muted hover:border-coral/40 hover:text-coral"}`}>{item.short}</button>)}</div></nav>

    <div className="mt-3 flex items-center justify-between rounded-2xl border border-ink/10 bg-white px-3 py-2 shadow-sm sm:px-4"><button type="button" onClick={() => go(questionIndex - 1)} className="grid h-10 w-10 place-items-center rounded-xl bg-cream text-xl font-bold text-ink" aria-label="Pregunta anterior">←</button><div className="min-w-0 px-3 text-center"><p className="text-xs font-extrabold uppercase tracking-wide text-coral">Pregunta {question.number} de 24</p><p className="truncate text-sm font-bold text-ink">{question.familyLabel}</p></div><button type="button" onClick={() => go(questionIndex + 1)} className="grid h-10 w-10 place-items-center rounded-xl bg-cream text-xl font-bold text-ink" aria-label="Pregunta siguiente">→</button></div>

    <section className="mt-5 grid items-start gap-6 lg:grid-cols-[minmax(0,1.04fr)_minmax(360px,.96fr)]"><motion.article key={question.id} initial={reduceMotion ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="rounded-[2rem] bg-white p-5 shadow-soft sm:p-8"><div className="flex items-center gap-3"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-night font-display text-lg font-bold text-honey">{skill.symbol}</span><div className="min-w-0"><p className="truncate text-xs font-extrabold uppercase tracking-wide text-muted">{question.familyLabel}</p><p className="text-sm text-muted">{question.skillLabel} · Nivel {question.level}</p></div></div><p className="mt-6 text-sm font-bold text-coral">{question.title}</p><h2 className="mt-1 font-display text-3xl font-bold leading-tight text-ink sm:text-4xl"><FractionText>{question.prompt}</FractionText></h2><p className="mt-2 leading-relaxed text-muted"><FractionText>{question.hint}</FractionText></p><div className="mt-6"><AlgebraReasoningBoard question={question} step={step}/></div>

      <div className="mt-6 grid grid-cols-1 gap-3 sm:grid-cols-2">{question.options.map((option, index) => { const picked = selected === option.value; const reveal = selected && option.value === question.answer; return <motion.button key={`${option.value}-${index}`} type="button" disabled={Boolean(selected)} whileTap={selected ? undefined : { scale: 0.98 }} onClick={() => choose(option.value)} className={`min-h-16 rounded-2xl border-2 px-3 py-4 text-left font-display text-base font-bold transition sm:px-4 sm:text-lg ${reveal ? "border-teal bg-teal-soft text-teal" : picked ? "border-coral bg-coral-soft text-coral" : "border-ink/10 bg-cream text-ink enabled:hover:border-honey"}`}><span className="mr-2 text-xs text-muted sm:mr-3 sm:text-sm">{String.fromCharCode(65 + index)}</span><FractionText>{option.value}</FractionText></motion.button>; })}</div>
      <AnimatePresence>{selected && <motion.div initial={reduceMotion ? false : { opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className={`mt-5 rounded-2xl p-4 ${correct ? "bg-teal-soft" : "bg-honey-soft"}`}><p className="font-display text-lg font-bold text-ink">{correct ? "Correcto: comprobemos por qué" : "Revisemos la relación"}</p><p className="mt-1 text-sm leading-relaxed text-ink/75"><FractionText>{correct ? question.success : selectedOption?.feedback}</FractionText></p></motion.div>}</AnimatePresence>
    </motion.article>

    <aside className="rounded-[2rem] bg-night p-5 text-white shadow-soft sm:p-7 lg:sticky lg:top-6"><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-extrabold uppercase tracking-[0.15em] text-honey">Explicación animada</p><h2 className="mt-1 font-display text-2xl font-bold">Conserva la relación</h2></div><span className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-white/10 font-display text-lg font-bold text-honey">{step}/3</span></div><div className="mt-6 flex gap-2">{[1, 2, 3].map((value) => <span key={value} className={`h-2 flex-1 rounded-full ${step >= value ? "bg-honey" : "bg-white/15"}`}/>)}</div><div className="mt-6 min-h-[280px]"><AnimatePresence mode="wait">{!current ? <motion.div key="empty" initial={false} className="rounded-3xl border border-dashed border-white/20 bg-white/5 p-6 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white/10 font-display text-2xl font-black text-honey">x</span><p className="mt-4 font-display text-xl font-bold">Elige una respuesta</p><p className="mt-2 text-sm leading-relaxed text-white/60">Después veremos cómo representar, transformar y comprobar la relación algebraica.</p></motion.div> : <motion.div key={`${question.id}-${step}`} initial={reduceMotion ? false : { opacity: 0, x: 24 }} animate={{ opacity: 1, x: 0 }} className="rounded-3xl bg-white p-6 text-ink"><p className="text-xs font-extrabold uppercase tracking-[0.14em] text-coral">{current.eyebrow}</p><h3 className="mt-2 font-display text-2xl font-bold">{current.title}</h3><div className="mt-5 rounded-2xl bg-honey-soft px-3 py-5 text-center font-display text-2xl font-bold text-night sm:text-3xl"><FractionText>{current.equation}</FractionText></div><p className="mt-4 leading-relaxed text-muted"><FractionText>{current.text}</FractionText></p></motion.div>}</AnimatePresence></div>{selected && <button type="button" onClick={advance} className="mt-5 w-full rounded-full bg-honey px-6 py-3.5 font-display text-lg font-bold text-night transition hover:bg-honey-deep hover:text-white">{step < 3 ? "Ver siguiente paso →" : "Siguiente pregunta →"}</button>}</aside></section>
  </div></main>;
}
